using HumanLanguages.LanguageNames;

namespace HumanLanguages
{
    public static class Languages
    {
        public static Dictionary<LanguageIsoCode, LanguageProperties> LanguagePropertiesDictionary = new()
        {
            {
                LanguageIsoCode.aa,
                AA.LanguageProperties
            },
            {
                LanguageIsoCode.af,
                AF.LanguageProperties
            },
            {
                LanguageIsoCode.agq,
                AGQ.LanguageProperties
            },
            {
                LanguageIsoCode.ak,
                AK.LanguageProperties
            },
            {
                LanguageIsoCode.am,
                AM.LanguageProperties
            },
            {
                LanguageIsoCode.ar,
                AR.LanguageProperties
            },
            {
                LanguageIsoCode.arn,
                ARN.LanguageProperties
            },
            {
                LanguageIsoCode.@as,
                AS.LanguageProperties
            },
            {
                LanguageIsoCode.asa,
                ASA.LanguageProperties
            },
            {
                LanguageIsoCode.ast,
                AST.LanguageProperties
            },
            {
                LanguageIsoCode.az,
                AZ.LanguageProperties
            },
            {
                LanguageIsoCode.ba,
                BA.LanguageProperties
            },
            {
                LanguageIsoCode.bas,
                BAS.LanguageProperties
            },
            {
                LanguageIsoCode.be,
                BE.LanguageProperties
            },
            {
                LanguageIsoCode.bem,
                BEM.LanguageProperties
            },
            {
                LanguageIsoCode.bez,
                BEZ.LanguageProperties
            },
            {
                LanguageIsoCode.bg,
                BG.LanguageProperties
            },
            {
                LanguageIsoCode.bin,
                BIN.LanguageProperties
            },
            {
                LanguageIsoCode.bm,
                BM.LanguageProperties
            },
            {
                LanguageIsoCode.bn,
                BN.LanguageProperties
            },
            {
                LanguageIsoCode.bo,
                BO.LanguageProperties
            },
            {
                LanguageIsoCode.br,
                BR.LanguageProperties
            },
            {
                LanguageIsoCode.brx,
                BRX.LanguageProperties
            },
            {
                LanguageIsoCode.bs,
                BS.LanguageProperties
            },
            {
                LanguageIsoCode.byn,
                BYN.LanguageProperties
            },
            {
                LanguageIsoCode.ca,
                CA.LanguageProperties
            },
            {
                LanguageIsoCode.ccp,
                CCP.LanguageProperties
            },
            {
                LanguageIsoCode.ce,
                CE.LanguageProperties
            },
            {
                LanguageIsoCode.ceb,
                CEB.LanguageProperties
            },
            {
                LanguageIsoCode.cgg,
                CGG.LanguageProperties
            },
            {
                LanguageIsoCode.chr,
                CHR.LanguageProperties
            },
            {
                LanguageIsoCode.ckb,
                CKB.LanguageProperties
            },
            {
                LanguageIsoCode.co,
                CO.LanguageProperties
            },
            {
                LanguageIsoCode.cs,
                CS.LanguageProperties
            },
            {
                LanguageIsoCode.cu,
                CU.LanguageProperties
            },
            {
                LanguageIsoCode.cy,
                CY.LanguageProperties
            },
            {
                LanguageIsoCode.da,
                DA.LanguageProperties
            },
            {
                LanguageIsoCode.dav,
                DAV.LanguageProperties
            },
            {
                LanguageIsoCode.de,
                DE.LanguageProperties
            },
            {
                LanguageIsoCode.dje,
                DJE.LanguageProperties
            },
            {
                LanguageIsoCode.doi,
                DOI.LanguageProperties
            },
            {
                LanguageIsoCode.dsb,
                DSB.LanguageProperties
            },
            {
                LanguageIsoCode.dua,
                DUA.LanguageProperties
            },
            {
                LanguageIsoCode.dv,
                DV.LanguageProperties
            },
            {
                LanguageIsoCode.dz,
                DZ.LanguageProperties
            },
            {
                LanguageIsoCode.ebu,
                EBU.LanguageProperties
            },
            {
                LanguageIsoCode.ee,
                EE.LanguageProperties
            },
            {
                LanguageIsoCode.el,
                EL.LanguageProperties
            },
            {
                LanguageIsoCode.en,
                EN.LanguageProperties
            },
            {
                LanguageIsoCode.eo,
                EO.LanguageProperties
            },
            {
                LanguageIsoCode.es,
                ES.LanguageProperties
            },
            {
                LanguageIsoCode.et,
                ET.LanguageProperties
            },
            {
                LanguageIsoCode.eu,
                EU.LanguageProperties
            },
            {
                LanguageIsoCode.ewo,
                EWO.LanguageProperties
            },
            {
                LanguageIsoCode.fa,
                FA.LanguageProperties
            },
            {
                LanguageIsoCode.ff,
                FF.LanguageProperties
            },
            {
                LanguageIsoCode.fi,
                FI.LanguageProperties
            },
            {
                LanguageIsoCode.fil,
                FIL.LanguageProperties
            },
            {
                LanguageIsoCode.fo,
                FO.LanguageProperties
            },
            {
                LanguageIsoCode.fr,
                FR.LanguageProperties
            },
            {
                LanguageIsoCode.fur,
                FUR.LanguageProperties
            },
            {
                LanguageIsoCode.fy,
                FY.LanguageProperties
            },
            {
                LanguageIsoCode.ga,
                GA.LanguageProperties
            },
            {
                LanguageIsoCode.gd,
                GD.LanguageProperties
            },
            {
                LanguageIsoCode.gl,
                GL.LanguageProperties
            },
            {
                LanguageIsoCode.gn,
                GN.LanguageProperties
            },
            {
                LanguageIsoCode.gsw,
                GSW.LanguageProperties
            },
            {
                LanguageIsoCode.gu,
                GU.LanguageProperties
            },
            {
                LanguageIsoCode.guz,
                GUZ.LanguageProperties
            },
            {
                LanguageIsoCode.gv,
                GV.LanguageProperties
            },
            {
                LanguageIsoCode.ha,
                HA.LanguageProperties
            },
            {
                LanguageIsoCode.haw,
                HAW.LanguageProperties
            },
            {
                LanguageIsoCode.he,
                HE.LanguageProperties
            },
            {
                LanguageIsoCode.hi,
                HI.LanguageProperties
            },
            {
                LanguageIsoCode.hr,
                HR.LanguageProperties
            },
            {
                LanguageIsoCode.hsb,
                HSB.LanguageProperties
            },
            {
                LanguageIsoCode.hu,
                HU.LanguageProperties
            },
            {
                LanguageIsoCode.hy,
                HY.LanguageProperties
            },
            {
                LanguageIsoCode.ia,
                IA.LanguageProperties
            },
            {
                LanguageIsoCode.ibb,
                IBB.LanguageProperties
            },
            {
                LanguageIsoCode.id,
                ID.LanguageProperties
            },
            {
                LanguageIsoCode.ig,
                IG.LanguageProperties
            },
            {
                LanguageIsoCode.ii,
                II.LanguageProperties
            },
            {
                LanguageIsoCode.@is,
                IS.LanguageProperties
            },
            {
                LanguageIsoCode.it,
                IT.LanguageProperties
            },
            {
                LanguageIsoCode.iu,
                IU.LanguageProperties
            },
            {
                LanguageIsoCode.ja,
                JA.LanguageProperties
            },
            {
                LanguageIsoCode.jgo,
                JGO.LanguageProperties
            },
            {
                LanguageIsoCode.jmc,
                JMC.LanguageProperties
            },
            {
                LanguageIsoCode.jv,
                JV.LanguageProperties
            },
            {
                LanguageIsoCode.ka,
                KA.LanguageProperties
            },
            {
                LanguageIsoCode.kab,
                KAB.LanguageProperties
            },
            {
                LanguageIsoCode.kam,
                KAM.LanguageProperties
            },
            {
                LanguageIsoCode.kde,
                KDE.LanguageProperties
            },
            {
                LanguageIsoCode.kea,
                KEA.LanguageProperties
            },
            {
                LanguageIsoCode.khq,
                KHQ.LanguageProperties
            },
            {
                LanguageIsoCode.ki,
                KI.LanguageProperties
            },
            {
                LanguageIsoCode.kk,
                KK.LanguageProperties
            },
            {
                LanguageIsoCode.kkj,
                KKJ.LanguageProperties
            },
            {
                LanguageIsoCode.kl,
                KL.LanguageProperties
            },
            {
                LanguageIsoCode.kln,
                KLN.LanguageProperties
            },
            {
                LanguageIsoCode.km,
                KM.LanguageProperties
            },
            {
                LanguageIsoCode.kn,
                KN.LanguageProperties
            },
            {
                LanguageIsoCode.ko,
                KO.LanguageProperties
            },
            {
                LanguageIsoCode.kok,
                KOK.LanguageProperties
            },
            {
                LanguageIsoCode.kr,
                KR.LanguageProperties
            },
            {
                LanguageIsoCode.ks,
                KS.LanguageProperties
            },
            {
                LanguageIsoCode.ksb,
                KSB.LanguageProperties
            },
            {
                LanguageIsoCode.ksf,
                KSF.LanguageProperties
            },
            {
                LanguageIsoCode.ksh,
                KSH.LanguageProperties
            },
            {
                LanguageIsoCode.kw,
                KW.LanguageProperties
            },
            {
                LanguageIsoCode.ky,
                KY.LanguageProperties
            },
            {
                LanguageIsoCode.la,
                LA.LanguageProperties
            },
            {
                LanguageIsoCode.lag,
                LAG.LanguageProperties
            },
            {
                LanguageIsoCode.lb,
                LB.LanguageProperties
            },
            {
                LanguageIsoCode.lg,
                LG.LanguageProperties
            },
            {
                LanguageIsoCode.lkt,
                LKT.LanguageProperties
            },
            {
                LanguageIsoCode.ln,
                LN.LanguageProperties
            },
            {
                LanguageIsoCode.lo,
                LO.LanguageProperties
            },
            {
                LanguageIsoCode.lrc,
                LRC.LanguageProperties
            },
            {
                LanguageIsoCode.lt,
                LT.LanguageProperties
            },
            {
                LanguageIsoCode.luo,
                LUO.LanguageProperties
            },
            {
                LanguageIsoCode.luy,
                LUY.LanguageProperties
            },
            {
                LanguageIsoCode.lv,
                LV.LanguageProperties
            },
            {
                LanguageIsoCode.mai,
                MAI.LanguageProperties
            },
            {
                LanguageIsoCode.mas,
                MAS.LanguageProperties
            },
            {
                LanguageIsoCode.mer,
                MER.LanguageProperties
            },
            {
                LanguageIsoCode.mfe,
                MFE.LanguageProperties
            },
            {
                LanguageIsoCode.mg,
                MG.LanguageProperties
            },
            {
                LanguageIsoCode.mgo,
                MGO.LanguageProperties
            },
            {
                LanguageIsoCode.mi,
                MI.LanguageProperties
            },
            {
                LanguageIsoCode.mk,
                MK.LanguageProperties
            },
            {
                LanguageIsoCode.ml,
                ML.LanguageProperties
            },
            {
                LanguageIsoCode.mn,
                MN.LanguageProperties
            },
            {
                LanguageIsoCode.mni,
                MNI.LanguageProperties
            },
            {
                LanguageIsoCode.moh,
                MOH.LanguageProperties
            },
            {
                LanguageIsoCode.mr,
                MR.LanguageProperties
            },
            {
                LanguageIsoCode.ms,
                MS.LanguageProperties
            },
            {
                LanguageIsoCode.mt,
                MT.LanguageProperties
            },
            {
                LanguageIsoCode.mua,
                MUA.LanguageProperties
            },
            {
                LanguageIsoCode.my,
                MY.LanguageProperties
            },
            {
                LanguageIsoCode.mzn,
                MZN.LanguageProperties
            },
            {
                LanguageIsoCode.naq,
                NAQ.LanguageProperties
            },
            {
                LanguageIsoCode.nb,
                NB.LanguageProperties
            },
            {
                LanguageIsoCode.nd,
                ND.LanguageProperties
            },
            {
                LanguageIsoCode.nds,
                NDS.LanguageProperties
            },
            {
                LanguageIsoCode.ne,
                NE.LanguageProperties
            },
            {
                LanguageIsoCode.nl,
                NL.LanguageProperties
            },
            {
                LanguageIsoCode.nmg,
                NMG.LanguageProperties
            },
            {
                LanguageIsoCode.nn,
                NN.LanguageProperties
            },
            {
                LanguageIsoCode.nnh,
                NNH.LanguageProperties
            },
            {
                LanguageIsoCode.nqo,
                NQO.LanguageProperties
            },
            {
                LanguageIsoCode.nr,
                NR.LanguageProperties
            },
            {
                LanguageIsoCode.nso,
                NSO.LanguageProperties
            },
            {
                LanguageIsoCode.nus,
                NUS.LanguageProperties
            },
            {
                LanguageIsoCode.nyn,
                NYN.LanguageProperties
            },
            {
                LanguageIsoCode.oc,
                OC.LanguageProperties
            },
            {
                LanguageIsoCode.om,
                OM.LanguageProperties
            },
            {
                LanguageIsoCode.or,
                OR.LanguageProperties
            },
            {
                LanguageIsoCode.os,
                OS.LanguageProperties
            },
            {
                LanguageIsoCode.pa,
                PA.LanguageProperties
            },
            {
                LanguageIsoCode.pap,
                PAP.LanguageProperties
            },
            {
                LanguageIsoCode.pcm,
                PCM.LanguageProperties
            },
            {
                LanguageIsoCode.pl,
                PL.LanguageProperties
            },
            {
                LanguageIsoCode.prg,
                PRG.LanguageProperties
            },
            {
                LanguageIsoCode.ps,
                PS.LanguageProperties
            },
            {
                LanguageIsoCode.pt,
                PT.LanguageProperties
            },
            {
                LanguageIsoCode.qu,
                QU.LanguageProperties
            },
            {
                LanguageIsoCode.quc,
                QUC.LanguageProperties
            },
            {
                LanguageIsoCode.rm,
                RM.LanguageProperties
            },
            {
                LanguageIsoCode.rn,
                RN.LanguageProperties
            },
            {
                LanguageIsoCode.ro,
                RO.LanguageProperties
            },
            {
                LanguageIsoCode.rof,
                ROF.LanguageProperties
            },
            {
                LanguageIsoCode.ru,
                RU.LanguageProperties
            },
            {
                LanguageIsoCode.rw,
                RW.LanguageProperties
            },
            {
                LanguageIsoCode.rwk,
                RWK.LanguageProperties
            },
            {
                LanguageIsoCode.sa,
                SA.LanguageProperties
            },
            {
                LanguageIsoCode.sah,
                SAH.LanguageProperties
            },
            {
                LanguageIsoCode.saq,
                SAQ.LanguageProperties
            },
            {
                LanguageIsoCode.sat,
                SAT.LanguageProperties
            },
            {
                LanguageIsoCode.sbp,
                SBP.LanguageProperties
            },
            {
                LanguageIsoCode.sd,
                SD.LanguageProperties
            },
            {
                LanguageIsoCode.se,
                SE.LanguageProperties
            },
            {
                LanguageIsoCode.seh,
                SEH.LanguageProperties
            },
            {
                LanguageIsoCode.ses,
                SES.LanguageProperties
            },
            {
                LanguageIsoCode.sg,
                SG.LanguageProperties
            },
            {
                LanguageIsoCode.shi,
                SHI.LanguageProperties
            },
            {
                LanguageIsoCode.si,
                SI.LanguageProperties
            },
            {
                LanguageIsoCode.sk,
                SK.LanguageProperties
            },
            {
                LanguageIsoCode.sl,
                SL.LanguageProperties
            },
            {
                LanguageIsoCode.sma,
                SMA.LanguageProperties
            },
            {
                LanguageIsoCode.smj,
                SMJ.LanguageProperties
            },
            {
                LanguageIsoCode.smn,
                SMN.LanguageProperties
            },
            {
                LanguageIsoCode.sms,
                SMS.LanguageProperties
            },
            {
                LanguageIsoCode.sn,
                SN.LanguageProperties
            },
            {
                LanguageIsoCode.so,
                SO.LanguageProperties
            },
            {
                LanguageIsoCode.sq,
                SQ.LanguageProperties
            },
            {
                LanguageIsoCode.sr,
                SR.LanguageProperties
            },
            {
                LanguageIsoCode.ss,
                SS.LanguageProperties
            },
            {
                LanguageIsoCode.ssy,
                SSY.LanguageProperties
            },
            {
                LanguageIsoCode.st,
                ST.LanguageProperties
            },
            {
                LanguageIsoCode.su,
                SU.LanguageProperties
            },
            {
                LanguageIsoCode.sv,
                SV.LanguageProperties
            },
            {
                LanguageIsoCode.sw,
                SW.LanguageProperties
            },
            {
                LanguageIsoCode.syr,
                SYR.LanguageProperties
            },
            {
                LanguageIsoCode.ta,
                TA.LanguageProperties
            },
            {
                LanguageIsoCode.te,
                TE.LanguageProperties
            },
            {
                LanguageIsoCode.teo,
                TEO.LanguageProperties
            },
            {
                LanguageIsoCode.tg,
                TG.LanguageProperties
            },
            {
                LanguageIsoCode.th,
                TH.LanguageProperties
            },
            {
                LanguageIsoCode.ti,
                TI.LanguageProperties
            },
            {
                LanguageIsoCode.tig,
                TIG.LanguageProperties
            },
            {
                LanguageIsoCode.tk,
                TK.LanguageProperties
            },
            {
                LanguageIsoCode.tn,
                TN.LanguageProperties
            },
            {
                LanguageIsoCode.to,
                TO.LanguageProperties
            },
            {
                LanguageIsoCode.tr,
                TR.LanguageProperties
            },
            {
                LanguageIsoCode.ts,
                TS.LanguageProperties
            },
            {
                LanguageIsoCode.tt,
                TT.LanguageProperties
            },
            {
                LanguageIsoCode.twq,
                TWQ.LanguageProperties
            },
            {
                LanguageIsoCode.tzm,
                TZM.LanguageProperties
            },
            {
                LanguageIsoCode.ug,
                UG.LanguageProperties
            },
            {
                LanguageIsoCode.uk,
                UK.LanguageProperties
            },
            {
                LanguageIsoCode.ur,
                UR.LanguageProperties
            },
            {
                LanguageIsoCode.uz,
                UZ.LanguageProperties
            },
            {
                LanguageIsoCode.vai,
                VAI.LanguageProperties
            },
            {
                LanguageIsoCode.ve,
                VE.LanguageProperties
            },
            {
                LanguageIsoCode.vi,
                VI.LanguageProperties
            },
            {
                LanguageIsoCode.vo,
                VO.LanguageProperties
            },
            {
                LanguageIsoCode.vun,
                VUN.LanguageProperties
            },
            {
                LanguageIsoCode.wae,
                WAE.LanguageProperties
            },
            {
                LanguageIsoCode.wal,
                WAL.LanguageProperties
            },
            {
                LanguageIsoCode.wo,
                WO.LanguageProperties
            },
            {
                LanguageIsoCode.xh,
                XH.LanguageProperties
            },
            {
                LanguageIsoCode.xog,
                XOG.LanguageProperties
            },
            {
                LanguageIsoCode.yav,
                YAV.LanguageProperties
            },
            {
                LanguageIsoCode.yi,
                YI.LanguageProperties
            },
            {
                LanguageIsoCode.yo,
                YO.LanguageProperties
            },
            {
                LanguageIsoCode.zgh,
                ZGH.LanguageProperties
            },
            {
                LanguageIsoCode.zh,
                ZH.LanguageProperties
            },
            {
                LanguageIsoCode.zu,
                ZU.LanguageProperties
            }
        };
    }
}
