namespace HumanLanguages.LanguageNames
{
	public sealed class AA
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Afar" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "afar" },
				{ LanguageIsoCode.af, "Ver" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "አፋር" },
				{ LanguageIsoCode.ar, "بعيد" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Afar" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Здалёк" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "отдалеч" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "আফার" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Afar" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "De lluny" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Layo" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "luntanu" },
				{ LanguageIsoCode.cs, "Afar" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Afar" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "In der Ferne" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Μακρυά" },
				{ LanguageIsoCode.eo, "Malproksime" },
				{ LanguageIsoCode.es, "Lejos" },
				{ LanguageIsoCode.et, "Kaugelt" },
				{ LanguageIsoCode.eu, "urrun" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "آفر" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Kaukana" },
				{ LanguageIsoCode.fil, "Malayo" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Au loin" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Afar" },
				{ LanguageIsoCode.ga, "i gcéin" },
				{ LanguageIsoCode.gd, "Afar" },
				{ LanguageIsoCode.gl, "De lonxe" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "આફર" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Afar" },
				{ LanguageIsoCode.haw, "Afar" },
				{ LanguageIsoCode.he, "רחוק" },
				{ LanguageIsoCode.hi, "दूर" },
				{ LanguageIsoCode.hr, "Izdaleka" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Messze" },
				{ LanguageIsoCode.hy, "Աֆար" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Jauh" },
				{ LanguageIsoCode.ig, "Afar" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Afar" },
				{ LanguageIsoCode.it, "Lontano" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "遠くまで" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Afar" },
				{ LanguageIsoCode.ka, "აფარი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Афар" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ឆ្ងាយ" },
				{ LanguageIsoCode.kn, "ದೂರ" },
				{ LanguageIsoCode.ko, "멀리" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Афар" },
				{ LanguageIsoCode.la, "Longe" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "A wäit" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ໄກ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Toli" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Tālu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "lavitra" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Tawhiti" },
				{ LanguageIsoCode.mk, "Далеку" },
				{ LanguageIsoCode.ml, "അകലെ" },
				{ LanguageIsoCode.mn, "Афар" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "अफार" },
				{ LanguageIsoCode.ms, "Jauh" },
				{ LanguageIsoCode.mt, "Afar" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "အဝေး" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Afar" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "अफार" },
				{ LanguageIsoCode.nl, "Ver weg" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଆଫାର୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਅਫਾਰ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Daleko" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "افار" },
				{ LanguageIsoCode.pt, "Longe" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "departe" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "издалека" },
				{ LanguageIsoCode.rw, "Afar" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "آفر" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ඈත" },
				{ LanguageIsoCode.sk, "Afar" },
				{ LanguageIsoCode.sl, "Od daleč" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Afar" },
				{ LanguageIsoCode.so, "Afar" },
				{ LanguageIsoCode.sq, "Afar" },
				{ LanguageIsoCode.sr, "Афар" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Hole" },
				{ LanguageIsoCode.su, "Kajauhan" },
				{ LanguageIsoCode.sv, "Fjärran" },
				{ LanguageIsoCode.sw, "Mbali" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "தூரம்" },
				{ LanguageIsoCode.te, "దూరం" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Афар" },
				{ LanguageIsoCode.th, "ไกล" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Afar" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Uzaktan" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Афар" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Afar" },
				{ LanguageIsoCode.uk, "Здалеку" },
				{ LanguageIsoCode.ur, "افار" },
				{ LanguageIsoCode.uz, "Afar" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Xa" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Kude" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "אפאר" },
				{ LanguageIsoCode.yo, "Afar" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "阿法尔" },
				{ LanguageIsoCode.zu, "Kude" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.DJ, "Afar (Djibouti)" },
				{ LanguageVariationIsoCode.ER, "Afar (Eritrea)" },
				{ LanguageVariationIsoCode.ET, "Afar (Ethiopia)" },
			});
	}
}
