namespace HumanLanguages.LanguageNames
{
	public sealed class AR
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Arabic" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "arabisk" },
				{ LanguageIsoCode.af, "Arabies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "አረብኛ" },
				{ LanguageIsoCode.ar, "العربية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "ərəb" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "арабская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "арабски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "আরবি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "arapski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "àrab" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Arabiko" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Arabu" },
				{ LanguageIsoCode.cs, "arabština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Arabeg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Arabisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "αραβικός" },
				{ LanguageIsoCode.eo, "la araba" },
				{ LanguageIsoCode.es, "Arábica" },
				{ LanguageIsoCode.et, "araabia keel" },
				{ LanguageIsoCode.eu, "arabiera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "عربی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "arabialainen" },
				{ LanguageIsoCode.fil, "Arabic" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "arabe" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Arabysk" },
				{ LanguageIsoCode.ga, "Araibis" },
				{ LanguageIsoCode.gd, "Arabach" },
				{ LanguageIsoCode.gl, "árabe" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "અરબી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Larabci" },
				{ LanguageIsoCode.haw, "Apapika" },
				{ LanguageIsoCode.he, "עֲרָבִית" },
				{ LanguageIsoCode.hi, "अरबी" },
				{ LanguageIsoCode.hr, "arapski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "arab" },
				{ LanguageIsoCode.hy, "արաբերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Arab" },
				{ LanguageIsoCode.ig, "Arabic" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "arabíska" },
				{ LanguageIsoCode.it, "Arabo" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "アラビア語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Arab" },
				{ LanguageIsoCode.ka, "არაბული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "араб" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ភាសាអារ៉ាប់" },
				{ LanguageIsoCode.kn, "ಅರೇಬಿಕ್" },
				{ LanguageIsoCode.ko, "아라비아 말" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Арабча" },
				{ LanguageIsoCode.la, "Arabice" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Arabesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ອາຣັບ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "arabiškas" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "arābu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Arabo" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Arapi" },
				{ LanguageIsoCode.mk, "арапски" },
				{ LanguageIsoCode.ml, "അറബി" },
				{ LanguageIsoCode.mn, "Араб" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "अरबी" },
				{ LanguageIsoCode.ms, "bahasa arab" },
				{ LanguageIsoCode.mt, "Għarbi" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "အာရဗီ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "arabisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "अरबी" },
				{ LanguageIsoCode.nl, "Arabisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଆରବୀ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਅਰਬੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "arabski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "عربي" },
				{ LanguageIsoCode.pt, "árabe" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "arabic" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "арабский" },
				{ LanguageIsoCode.rw, "Icyarabu" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "عربي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "අරාබි" },
				{ LanguageIsoCode.sk, "arabčina" },
				{ LanguageIsoCode.sl, "arabsko" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiArabic" },
				{ LanguageIsoCode.so, "Carabi" },
				{ LanguageIsoCode.sq, "arabisht" },
				{ LanguageIsoCode.sr, "арапски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Searabia" },
				{ LanguageIsoCode.su, "Arab" },
				{ LanguageIsoCode.sv, "arabiska" },
				{ LanguageIsoCode.sw, "Kiarabu" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "அரபு" },
				{ LanguageIsoCode.te, "అరబిక్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "арабӣ" },
				{ LanguageIsoCode.th, "ภาษาอาหรับ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Arapça" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Arapça" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Гарәп" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "ئەرەبچە" },
				{ LanguageIsoCode.uk, "арабська" },
				{ LanguageIsoCode.ur, "عربی" },
				{ LanguageIsoCode.uz, "arabcha" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "tiếng Ả Rập" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiArabhu" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "אַראַביש" },
				{ LanguageIsoCode.yo, "Larubawa" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "阿拉伯" },
				{ LanguageIsoCode.zu, "Isi-Arabhu" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.AE, "Arabic (United Arab Emirates)" },
				{ LanguageVariationIsoCode.BH, "Arabic (Bahrain)" },
				{ LanguageVariationIsoCode.DJ, "Arabic (Djibouti)" },
				{ LanguageVariationIsoCode.DZ, "Arabic (Algeria)" },
				{ LanguageVariationIsoCode.EG, "Arabic (Egypt)" },
				{ LanguageVariationIsoCode.ER, "Arabic (Eritrea)" },
				{ LanguageVariationIsoCode.IL, "Arabic (Israel)" },
				{ LanguageVariationIsoCode.IQ, "Arabic (Iraq)" },
				{ LanguageVariationIsoCode.JO, "Arabic (Jordan)" },
				{ LanguageVariationIsoCode.KM, "Arabic (Comoros)" },
				{ LanguageVariationIsoCode.KW, "Arabic (Kuwait)" },
				{ LanguageVariationIsoCode.LB, "Arabic (Lebanon)" },
				{ LanguageVariationIsoCode.LY, "Arabic (Libya)" },
				{ LanguageVariationIsoCode.MA, "Arabic (Morocco)" },
				{ LanguageVariationIsoCode.MR, "Arabic (Mauritania)" },
				{ LanguageVariationIsoCode.OM, "Arabic (Oman)" },
				{ LanguageVariationIsoCode.PS, "Arabic (Palestinian Authority)" },
				{ LanguageVariationIsoCode.QA, "Arabic (Qatar)" },
				{ LanguageVariationIsoCode.SA, "Arabic (Saudi Arabia)" },
				{ LanguageVariationIsoCode.SD, "Arabic (Sudan)" },
				{ LanguageVariationIsoCode.SO, "Arabic (Somalia)" },
				{ LanguageVariationIsoCode.SS, "Arabic (South Sudan)" },
				{ LanguageVariationIsoCode.SY, "Arabic (Syria)" },
				{ LanguageVariationIsoCode.TD, "Arabic (Chad)" },
				{ LanguageVariationIsoCode.TN, "Arabic (Tunisia)" },
				{ LanguageVariationIsoCode.YE, "Arabic (Yemen)" },
			});
	}
}
