namespace HumanLanguages.LanguageNames
{
	public sealed class CKB
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Central Kurdish" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "central kurdisk" },
				{ LanguageIsoCode.af, "Sentraal-Koerdies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ማዕከላዊ ኩርዲሽ" },
				{ LanguageIsoCode.ar, "الكردية المركزية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Mərkəzi kürd" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Цэнтральнакурд" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "централен кюрдски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "মধ্য কুর্দি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Central Kurdish" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "kurd central" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Sentral nga Kurdish" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "کوردیی ناوەندی" },
				{ LanguageIsoCode.co, "Curdu cintrali" },
				{ LanguageIsoCode.cs, "střední kurdština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Cwrdeg canolog" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Zentralkurdisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Κεντρικό Κουρδικό" },
				{ LanguageIsoCode.eo, "Centra kurda" },
				{ LanguageIsoCode.es, "Kurdo central" },
				{ LanguageIsoCode.et, "keskkurdi keel" },
				{ LanguageIsoCode.eu, "Erdialdeko kurduera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "کردی مرکزی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Keskikurdi" },
				{ LanguageIsoCode.fil, "Gitnang Kurdish" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Kurde central" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Sintraal Koerdysk" },
				{ LanguageIsoCode.ga, "Coirdis Láir" },
				{ LanguageIsoCode.gd, "Meadhan Kurdish" },
				{ LanguageIsoCode.gl, "kurdo central" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "મધ્ય કુર્દિશ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Kurdawa ta tsakiya" },
				{ LanguageIsoCode.haw, "Kuredi waena" },
				{ LanguageIsoCode.he, "כורדית מרכזית" },
				{ LanguageIsoCode.hi, "सेंट्रल कुर्दिश" },
				{ LanguageIsoCode.hr, "središnji kurdski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "közép kurd" },
				{ LanguageIsoCode.hy, "Կենտրոնական քրդ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Kurdi Tengah" },
				{ LanguageIsoCode.ig, "Central Kurdish" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Mið-Kúrda" },
				{ LanguageIsoCode.it, "Curdo centrale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "中央クルド人" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Kurdi Tengah" },
				{ LanguageIsoCode.ka, "ცენტრალური ქურთული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Орталық күрд" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ឃឺដកណ្តាល" },
				{ LanguageIsoCode.kn, "ಮಧ್ಯ ಕುರ್ದಿಷ್" },
				{ LanguageIsoCode.ko, "중앙 쿠르드어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Борбордук күрт" },
				{ LanguageIsoCode.la, "Centralis Kurdish" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Zentral kurdesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ຊາວເຄີດກາງ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "centrinis kurdas" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Centrālā kurdi" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Kiorda afovoany" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Kurdish Central" },
				{ LanguageIsoCode.mk, "централно курдско" },
				{ LanguageIsoCode.ml, "മധ്യ കുർദിഷ്" },
				{ LanguageIsoCode.mn, "Төв курд хэл" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "मध्य कुर्दिश" },
				{ LanguageIsoCode.ms, "Kurdish tengah" },
				{ LanguageIsoCode.mt, "Kurd Ċentrali" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဗဟိုကာ့ဒ်" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Sentralkurdisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "केन्द्रीय कुर्दिश" },
				{ LanguageIsoCode.nl, "Centraal Koerdisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "କେନ୍ଦ୍ରୀୟ କୁର୍ଦ୍ଦ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਕੇਂਦਰੀ ਕੁਰਦਿਸ਼" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Środkowy kurdyjski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "مرکزي کرد" },
				{ LanguageIsoCode.pt, "Curdo Central" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "kurdă centrală" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Центральный курдский" },
				{ LanguageIsoCode.rw, "Kurdish Hagati" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "مرڪزي کردش" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "මධ්යම කුර්දි" },
				{ LanguageIsoCode.sk, "Stredná kurdská" },
				{ LanguageIsoCode.sl, "osrednji kurdski" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Central Kurdish" },
				{ LanguageIsoCode.so, "Kurdida dhexe" },
				{ LanguageIsoCode.sq, "kurde qendrore" },
				{ LanguageIsoCode.sr, "Централ Курдисх" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Central Kurdish" },
				{ LanguageIsoCode.su, "Kurdi Tengah" },
				{ LanguageIsoCode.sv, "Centralkurdiska" },
				{ LanguageIsoCode.sw, "Kikurdi cha Kati" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "மத்திய குர்திஷ்" },
				{ LanguageIsoCode.te, "సెంట్రల్ కుర్దిష్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Курди марказӣ" },
				{ LanguageIsoCode.th, "เคิร์ดกลาง" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Merkezi Kürt" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Orta Kürtçe" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Centralзәк Көрд" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Central Kurdish" },
				{ LanguageIsoCode.uk, "центральнокурд" },
				{ LanguageIsoCode.ur, "وسطی کرد" },
				{ LanguageIsoCode.uz, "Markaziy kurd" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Kurd miền trung" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiKurdish esiseMbindini" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "צענטראל קורדיש" },
				{ LanguageIsoCode.yo, "Central Kurdish" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "中库尔德语" },
				{ LanguageIsoCode.zu, "I-Central Kurdish" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.IQ, "Central Kurdish (Iraq)" },
				{ LanguageVariationIsoCode.IR, "Central Kurdish (Iran)" },
			});
	}
}
