namespace HumanLanguages.LanguageNames
{
	public sealed class CU
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Church Slavic" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "kirkeslavisk" },
				{ LanguageIsoCode.af, "Kerk Slawies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ቤተ ክርስቲያን ስላቪክ" },
				{ LanguageIsoCode.ar, "الكنيسة السلافية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Slavyan kilsəsi" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "царкоўнаслав" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "църковнославянски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "চার্চ স্লাভিক" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "crkvenoslovenski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Eslau eclesiàstic" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Slavic sa Simbahan" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Chjesa slava" },
				{ LanguageIsoCode.cs, "církevní slovanština" },
				{ LanguageIsoCode.cu, "Church Slavic" },
				{ LanguageIsoCode.cy, "Slafeg Eglwysig" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Kirchenslawisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "εκκλησιαστική σλαβική" },
				{ LanguageIsoCode.eo, "Eklezia slava" },
				{ LanguageIsoCode.es, "Eslavo eclesiástico" },
				{ LanguageIsoCode.et, "kirikuslaavi" },
				{ LanguageIsoCode.eu, "Eliza eslaviarra" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "اسلاوی کلیسا" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Kirkon slaavilainen" },
				{ LanguageIsoCode.fil, "Slavic ng simbahan" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Église slave" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Tsjerke Slavyske" },
				{ LanguageIsoCode.ga, "Slavacha Eaglaise" },
				{ LanguageIsoCode.gd, "Slavic na h-Eaglais" },
				{ LanguageIsoCode.gl, "Eslavo eclesiástico" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ચર્ચ સ્લેવિક" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Cocin Slavic" },
				{ LanguageIsoCode.haw, "Slavic Ekalesia" },
				{ LanguageIsoCode.he, "כנסייה סלבית" },
				{ LanguageIsoCode.hi, "चर्च स्लाविक" },
				{ LanguageIsoCode.hr, "crkvenoslavenski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "egyházi szláv" },
				{ LanguageIsoCode.hy, "Եկեղեցական սլավոնական" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Slavia Gereja" },
				{ LanguageIsoCode.ig, "Ụka Slavic" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Kirkjuslavneska" },
				{ LanguageIsoCode.it, "Slavo ecclesiastico" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "教会スラブ語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Gréja Slavik" },
				{ LanguageIsoCode.ka, "საეკლესიო სლავური" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Шіркеу славян" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "សាសនាចក្រស្លាវី" },
				{ LanguageIsoCode.kn, "ಚರ್ಚ್ ಸ್ಲಾವಿಕ್" },
				{ LanguageIsoCode.ko, "교회 슬라브어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Чиркөө славян" },
				{ LanguageIsoCode.la, "Ecclesia Slavica" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Kierch Slavic" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ໂບດ Slavic" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Bažnyčios slavų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Baznīcas slāvu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Fiangonana Slavika" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Hahi Slavic" },
				{ LanguageIsoCode.mk, "црковнословенски" },
				{ LanguageIsoCode.ml, "ചർച്ച് സ്ലാവിക്" },
				{ LanguageIsoCode.mn, "Сүмийн славян" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "चर्च स्लाव्हिक" },
				{ LanguageIsoCode.ms, "Gereja Slavik" },
				{ LanguageIsoCode.mt, "Slavi tal-Knisja" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဘုရားကျောင်း Slavic" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Kirkeslavisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "चर्च स्लाभिक" },
				{ LanguageIsoCode.nl, "Kerkslavisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଚର୍ଚ୍ଚ ସ୍ଲାଭିକ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਚਰਚ ਸਲਾਵਿਕ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Cerkiewnosłowiańska" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "د کلیسا سلاوی" },
				{ LanguageIsoCode.pt, "Igreja eslava" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "slavă bisericească" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "церковнославянский" },
				{ LanguageIsoCode.rw, "Itorero ry'Abasilave" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "چرچ Slavic" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "පල්ලිය ස්ලාවික්" },
				{ LanguageIsoCode.sk, "cirkevná slovančina" },
				{ LanguageIsoCode.sl, "cerkveno slovansko" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Chechi yeSlavic" },
				{ LanguageIsoCode.so, "Kaniisadda Slavic" },
				{ LanguageIsoCode.sq, "sllave kishtare" },
				{ LanguageIsoCode.sr, "црквенословенски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Kereke ea Slavic" },
				{ LanguageIsoCode.su, "Garéja Slavia" },
				{ LanguageIsoCode.sv, "Kyrkoslavisk" },
				{ LanguageIsoCode.sw, "Slavic ya Kanisa" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "சர்ச் ஸ்லாவிக்" },
				{ LanguageIsoCode.te, "చర్చి స్లావిక్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Калисои славянӣ" },
				{ LanguageIsoCode.th, "คริสตจักรสลาฟ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Slawýan buthanasy" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Kilise Slav" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Славян чиркәве" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "چېركاۋ سىلاۋىيان" },
				{ LanguageIsoCode.uk, "церковнослов'янська" },
				{ LanguageIsoCode.ur, "چرچ سلاویک" },
				{ LanguageIsoCode.uz, "Slavyan cherkovi" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Nhà thờ Slav" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Icawa yeSlavic" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "קהילה סלאַוויש" },
				{ LanguageIsoCode.yo, "Ijo Slavic" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "教会斯拉夫语" },
				{ LanguageIsoCode.zu, "Isonto lamaSlavic" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.RU, "Church Slavic (Russia)" },
			});
	}
}
