namespace HumanLanguages.LanguageNames
{
	public sealed class DE
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "German" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "tysk" },
				{ LanguageIsoCode.af, "Duits" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ጀርመንኛ" },
				{ LanguageIsoCode.ar, "ألمانية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "alman" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "нямецкі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Немски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "জার্মান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "njemački" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "alemany" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Aleman" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Tedescu" },
				{ LanguageIsoCode.cs, "Němec" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Almaeneg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Deutsch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Γερμανός" },
				{ LanguageIsoCode.eo, "germana" },
				{ LanguageIsoCode.es, "Alemán" },
				{ LanguageIsoCode.et, "saksa keel" },
				{ LanguageIsoCode.eu, "alemana" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "آلمانی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Saksan kieli" },
				{ LanguageIsoCode.fil, "Aleman" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Allemand" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Dútsk" },
				{ LanguageIsoCode.ga, "Gearmáinis" },
				{ LanguageIsoCode.gd, "Gearmailteach" },
				{ LanguageIsoCode.gl, "alemán" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "જર્મન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Jamusanci" },
				{ LanguageIsoCode.haw, "Alemania" },
				{ LanguageIsoCode.he, "גֶרמָנִיָת" },
				{ LanguageIsoCode.hi, "जर्मन" },
				{ LanguageIsoCode.hr, "njemački" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "német" },
				{ LanguageIsoCode.hy, "գերմաներեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Jerman" },
				{ LanguageIsoCode.ig, "German" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "þýska, Þjóðverji, þýskur" },
				{ LanguageIsoCode.it, "Tedesco" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ドイツ人" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Jerman" },
				{ LanguageIsoCode.ka, "გერმანული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "неміс" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "អាឡឺម៉ង់" },
				{ LanguageIsoCode.kn, "ಜರ್ಮನ್" },
				{ LanguageIsoCode.ko, "독일 사람" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Немисче" },
				{ LanguageIsoCode.la, "German" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Däitsch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ເຢຍລະມັນ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "vokiečių" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "vācu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Anarana" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Tiamana" },
				{ LanguageIsoCode.mk, "германски" },
				{ LanguageIsoCode.ml, "ജർമ്മൻ" },
				{ LanguageIsoCode.mn, "Герман" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "जर्मन" },
				{ LanguageIsoCode.ms, "Jerman" },
				{ LanguageIsoCode.mt, "Ġermaniż" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဂျာမန်" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "tysk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "जर्मन" },
				{ LanguageIsoCode.nl, "Duits" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଜର୍ମାନ୍" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਜਰਮਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Niemiecki" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "جرمني" },
				{ LanguageIsoCode.pt, "Alemão" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "limba germana" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Немецкий" },
				{ LanguageIsoCode.rw, "Ikidage" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "جرمني" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ජර්මානු" },
				{ LanguageIsoCode.sk, "nemecký" },
				{ LanguageIsoCode.sl, "nemški" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiJerimani" },
				{ LanguageIsoCode.so, "Jarmal" },
				{ LanguageIsoCode.sq, "gjermanisht" },
				{ LanguageIsoCode.sr, "Немачки" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sejeremane" },
				{ LanguageIsoCode.su, "Jerman" },
				{ LanguageIsoCode.sv, "tysk" },
				{ LanguageIsoCode.sw, "Kijerumani" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஜெர்மன்" },
				{ LanguageIsoCode.te, "జర్మన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "олмонӣ" },
				{ LanguageIsoCode.th, "เยอรมัน" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Nemes" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Almanca" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Немец" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "German" },
				{ LanguageIsoCode.uk, "Німецький" },
				{ LanguageIsoCode.ur, "جرمن" },
				{ LanguageIsoCode.uz, "nemis" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "tiếng Đức" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiJamani" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "דײַטש" },
				{ LanguageIsoCode.yo, "Jẹmánì" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "德语" },
				{ LanguageIsoCode.zu, "IsiJalimane" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.AT, "German (Austria)" },
				{ LanguageVariationIsoCode.BE, "German (Belgium)" },
				{ LanguageVariationIsoCode.CH, "German (Switzerland)" },
				{ LanguageVariationIsoCode.DE, "German (Germany)" },
				{ LanguageVariationIsoCode.IT, "German (Italy)" },
				{ LanguageVariationIsoCode.LI, "German (Liechtenstein)" },
				{ LanguageVariationIsoCode.LU, "German (Luxembourg)" },
			});
	}
}
