namespace HumanLanguages.LanguageNames
{
	public sealed class DSB
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Lower Sorbian" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nedersorbisk" },
				{ LanguageIsoCode.af, "Laer-sorbies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "የታችኛው የሶርቢያን" },
				{ LanguageIsoCode.ar, "الصوربية السفلى" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Aşağı sorb dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "ніжнелужыцкая" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "долнолужицки" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "নিম্ন সরবিয়ান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Lower Sorbian" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "baix sòrab" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Ubos nga Sorbian" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Bassorabu" },
				{ LanguageIsoCode.cs, "Dolní lužická srbština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sorbeg Isaf" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Niedersorbisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "dolnoserbšćina" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Κάτω Σορβικά" },
				{ LanguageIsoCode.eo, "Malsupra soraba" },
				{ LanguageIsoCode.es, "bajo sorabo" },
				{ LanguageIsoCode.et, "alamsorbi" },
				{ LanguageIsoCode.eu, "behe sorabiera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "زبان سوربی پایین" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "alempi sorbi" },
				{ LanguageIsoCode.fil, "Lower Sorbian" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Bas sorabe" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Nedersorbysk" },
				{ LanguageIsoCode.ga, "Sorbais Íochtarach" },
				{ LanguageIsoCode.gd, "Sorbais Iarach" },
				{ LanguageIsoCode.gl, "baixo sorabo" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "લોઅર સોર્બિયન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Ƙasar Sorbian" },
				{ LanguageIsoCode.haw, "Sorbian lalo" },
				{ LanguageIsoCode.he, "סורבית תחתית" },
				{ LanguageIsoCode.hi, "निचला सोरबियन" },
				{ LanguageIsoCode.hr, "donjolužičkosrpski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "alsó szorb" },
				{ LanguageIsoCode.hy, "Ստորին սորբերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Sorbia Bawah" },
				{ LanguageIsoCode.ig, "Sorbian dị ala" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "lágsorbneska" },
				{ LanguageIsoCode.it, "Sorabo inferiore" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "下ソルブ語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Sorbian ngisor" },
				{ LanguageIsoCode.ka, "ქვედა სორბიული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Төменгі сорб" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "សូបៀនទាប" },
				{ LanguageIsoCode.kn, "ಲೋವರ್ ಸೋರ್ಬಿಯನ್" },
				{ LanguageIsoCode.ko, "하부소르비아어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Төмөнкү сорб" },
				{ LanguageIsoCode.la, "Inferius Sorbian" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Niedersorbesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ເຊີເບຍລຸ່ມ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Žemutinė sorbų kalba" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "lejassorbu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Sorbian ambany" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Sorbian Raro" },
				{ LanguageIsoCode.mk, "долнолужички" },
				{ LanguageIsoCode.ml, "ലോവർ സോർബിയൻ" },
				{ LanguageIsoCode.mn, "Доод сорб" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "लोअर सॉर्बियन" },
				{ LanguageIsoCode.ms, "Sorbian Bawah" },
				{ LanguageIsoCode.mt, "Lower Sorbian" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Lower Sorbian" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nedre sorbisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "तल्लो सोर्बियन" },
				{ LanguageIsoCode.nl, "Nedersorbisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଲୋୟର ସୋର୍ବିଆନ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਲੋਅਰ ਸੋਰਬੀਅਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "dolnołużycki" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "ښکته سوربیان" },
				{ LanguageIsoCode.pt, "Baixo Sórábio" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "soraba inferioară" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Нижнесербский" },
				{ LanguageIsoCode.rw, "Sorbian yo hepfo" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "لوئر سوربين" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "පහළ සෝර්බියානු" },
				{ LanguageIsoCode.sk, "Dolnolužická srbčina" },
				{ LanguageIsoCode.sl, "spodnjelužiško srbščino" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Lower Sorbian" },
				{ LanguageIsoCode.so, "Sorbian hoose" },
				{ LanguageIsoCode.sq, "Sorbishte e Ulët" },
				{ LanguageIsoCode.sr, "доњолужички језик" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sorbian ea Tlase" },
				{ LanguageIsoCode.su, "Sorbian handap" },
				{ LanguageIsoCode.sv, "lägre sorbiska" },
				{ LanguageIsoCode.sw, "Sorbian ya chini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "கீழ் சோர்பியன்" },
				{ LanguageIsoCode.te, "దిగువ సోర్బియన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Сорби поён" },
				{ LanguageIsoCode.th, "ซอร์เบียตอนล่าง" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Aşaky Sorbian" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Aşağı Sorbca" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Түбән Сорбиан" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Lower Sorbian" },
				{ LanguageIsoCode.uk, "нижньолужицька" },
				{ LanguageIsoCode.ur, "لوئر سوربین" },
				{ LanguageIsoCode.uz, "Quyi sorb" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Hạ Sorbia" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiSorbian esisezantsi" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "נידעריקער סאָרביש" },
				{ LanguageIsoCode.yo, "Sorbian isalẹ" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "下索布语" },
				{ LanguageIsoCode.zu, "I-Lower Sorbian" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.DE, "Lower Sorbian (Germany)" },
			});
	}
}
