namespace HumanLanguages.LanguageNames
{
	public sealed class EN
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.af, "" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "" },
				{ LanguageIsoCode.ar, "" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "" },
				{ LanguageIsoCode.cs, "" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "" },
				{ LanguageIsoCode.da, "" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "" },
				{ LanguageIsoCode.en, "English" },
				{ LanguageIsoCode.eo, "" },
				{ LanguageIsoCode.es, "" },
				{ LanguageIsoCode.et, "" },
				{ LanguageIsoCode.eu, "" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "" },
				{ LanguageIsoCode.fil, "" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "" },
				{ LanguageIsoCode.ga, "" },
				{ LanguageIsoCode.gd, "" },
				{ LanguageIsoCode.gl, "" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "" },
				{ LanguageIsoCode.haw, "" },
				{ LanguageIsoCode.he, "" },
				{ LanguageIsoCode.hi, "" },
				{ LanguageIsoCode.hr, "" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "" },
				{ LanguageIsoCode.hy, "" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "" },
				{ LanguageIsoCode.ig, "" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "" },
				{ LanguageIsoCode.it, "" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "" },
				{ LanguageIsoCode.ka, "" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "" },
				{ LanguageIsoCode.kn, "" },
				{ LanguageIsoCode.ko, "" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "" },
				{ LanguageIsoCode.la, "" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "" },
				{ LanguageIsoCode.mk, "" },
				{ LanguageIsoCode.ml, "" },
				{ LanguageIsoCode.mn, "" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "" },
				{ LanguageIsoCode.ms, "" },
				{ LanguageIsoCode.mt, "" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "" },
				{ LanguageIsoCode.nl, "" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "" },
				{ LanguageIsoCode.pt, "" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "" },
				{ LanguageIsoCode.rw, "" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "" },
				{ LanguageIsoCode.sk, "" },
				{ LanguageIsoCode.sl, "" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "" },
				{ LanguageIsoCode.so, "" },
				{ LanguageIsoCode.sq, "" },
				{ LanguageIsoCode.sr, "" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "" },
				{ LanguageIsoCode.su, "" },
				{ LanguageIsoCode.sv, "" },
				{ LanguageIsoCode.sw, "" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "" },
				{ LanguageIsoCode.te, "" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "" },
				{ LanguageIsoCode.th, "" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "" },
				{ LanguageIsoCode.uk, "" },
				{ LanguageIsoCode.ur, "" },
				{ LanguageIsoCode.uz, "" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "" },
				{ LanguageIsoCode.yo, "" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "" },
				{ LanguageIsoCode.zu, "" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.AE, "English (United Arab Emirates)" },
				{ LanguageVariationIsoCode.AG, "English (Antigua & Barbuda)" },
				{ LanguageVariationIsoCode.AI, "English (Anguilla)" },
				{ LanguageVariationIsoCode.AS, "English (American Samoa)" },
				{ LanguageVariationIsoCode.AT, "English (Austria)" },
				{ LanguageVariationIsoCode.AU, "English (Australia)" },
				{ LanguageVariationIsoCode.BB, "English (Barbados)" },
				{ LanguageVariationIsoCode.BE, "English (Belgium)" },
				{ LanguageVariationIsoCode.BI, "English (Burundi)" },
				{ LanguageVariationIsoCode.BM, "English (Bermuda)" },
				{ LanguageVariationIsoCode.BS, "English (Bahamas)" },
				{ LanguageVariationIsoCode.BW, "English (Botswana)" },
				{ LanguageVariationIsoCode.BZ, "English (Belize)" },
				{ LanguageVariationIsoCode.CA, "English (Canada)" },
				{ LanguageVariationIsoCode.CC, "English (Cocos [Keeling] Islands)" },
				{ LanguageVariationIsoCode.CH, "English (Switzerland)" },
				{ LanguageVariationIsoCode.CK, "English (Cook Islands)" },
				{ LanguageVariationIsoCode.CM, "English (Cameroon)" },
				{ LanguageVariationIsoCode.CX, "English (Christmas Island)" },
				{ LanguageVariationIsoCode.CY, "English (Cyprus)" },
				{ LanguageVariationIsoCode.DE, "English (Germany)" },
				{ LanguageVariationIsoCode.DK, "English (Denmark)" },
				{ LanguageVariationIsoCode.DM, "English (Dominica)" },
				{ LanguageVariationIsoCode.ER, "English (Eritrea)" },
				{ LanguageVariationIsoCode.FI, "English (Finland)" },
				{ LanguageVariationIsoCode.FJ, "English (Fiji)" },
				{ LanguageVariationIsoCode.FK, "English (Falkland Islands)" },
				{ LanguageVariationIsoCode.FM, "English (Micronesia)" },
				{ LanguageVariationIsoCode.GB, "English (United Kingdom)" },
				{ LanguageVariationIsoCode.GD, "English (Grenada)" },
				{ LanguageVariationIsoCode.GG, "English (Guernsey)" },
				{ LanguageVariationIsoCode.GH, "English (Ghana)" },
				{ LanguageVariationIsoCode.GI, "English (Gibraltar)" },
				{ LanguageVariationIsoCode.GM, "English (Gambia)" },
				{ LanguageVariationIsoCode.GU, "English (Guam)" },
				{ LanguageVariationIsoCode.GY, "English (Guyana)" },
				{ LanguageVariationIsoCode.HK, "English (Hong Kong SAR)" },
				{ LanguageVariationIsoCode.ID, "English (Indonesia)" },
				{ LanguageVariationIsoCode.IE, "English (Ireland)" },
				{ LanguageVariationIsoCode.IL, "English (Israel)" },
				{ LanguageVariationIsoCode.IM, "English (Isle of Man)" },
				{ LanguageVariationIsoCode.IN, "English (India)" },
				{ LanguageVariationIsoCode.IO, "English (British Indian Ocean Territory)" },
				{ LanguageVariationIsoCode.JE, "English (Jersey)" },
				{ LanguageVariationIsoCode.JM, "English (Jamaica)" },
				{ LanguageVariationIsoCode.KE, "English (Kenya)" },
				{ LanguageVariationIsoCode.KI, "English (Kiribati)" },
				{ LanguageVariationIsoCode.KN, "English (St. Kitts & Nevis)" },
				{ LanguageVariationIsoCode.KY, "English (Cayman Islands)" },
				{ LanguageVariationIsoCode.LC, "English (St. Lucia)" },
				{ LanguageVariationIsoCode.LR, "English (Liberia)" },
				{ LanguageVariationIsoCode.LS, "English (Lesotho)" },
				{ LanguageVariationIsoCode.MG, "English (Madagascar)" },
				{ LanguageVariationIsoCode.MH, "English (Marshall Islands)" },
				{ LanguageVariationIsoCode.MO, "English (Macao SAR)" },
				{ LanguageVariationIsoCode.MP, "English (Northern Mariana Islands)" },
				{ LanguageVariationIsoCode.MS, "English (Montserrat)" },
				{ LanguageVariationIsoCode.MT, "English (Malta)" },
				{ LanguageVariationIsoCode.MU, "English (Mauritius)" },
				{ LanguageVariationIsoCode.MW, "English (Malawi)" },
				{ LanguageVariationIsoCode.MY, "English (Malaysia)" },
				{ LanguageVariationIsoCode.NA, "English (Namibia)" },
				{ LanguageVariationIsoCode.NF, "English (Norfolk Island)" },
				{ LanguageVariationIsoCode.NG, "English (Nigeria)" },
				{ LanguageVariationIsoCode.NL, "English (Netherlands)" },
				{ LanguageVariationIsoCode.NR, "English (Nauru)" },
				{ LanguageVariationIsoCode.NU, "English (Niue)" },
				{ LanguageVariationIsoCode.NZ, "English (New Zealand)" },
				{ LanguageVariationIsoCode.PG, "English (Papua New Guinea)" },
				{ LanguageVariationIsoCode.PH, "English (Philippines)" },
				{ LanguageVariationIsoCode.PK, "English (Pakistan)" },
				{ LanguageVariationIsoCode.PN, "English (Pitcairn Islands)" },
				{ LanguageVariationIsoCode.PR, "English (Puerto Rico)" },
				{ LanguageVariationIsoCode.PW, "English (Palau)" },
				{ LanguageVariationIsoCode.RW, "English (Rwanda)" },
				{ LanguageVariationIsoCode.SB, "English (Solomon Islands)" },
				{ LanguageVariationIsoCode.SC, "English (Seychelles)" },
				{ LanguageVariationIsoCode.SD, "English (Sudan)" },
				{ LanguageVariationIsoCode.SE, "English (Sweden)" },
				{ LanguageVariationIsoCode.SG, "English (Singapore)" },
				{ LanguageVariationIsoCode.SH, "English (St. Helena)" },
				{ LanguageVariationIsoCode.SI, "English (Slovenia)" },
				{ LanguageVariationIsoCode.SL, "English (Sierra Leone)" },
				{ LanguageVariationIsoCode.SS, "English (South Sudan)" },
				{ LanguageVariationIsoCode.SX, "English (Sint Maarten)" },
				{ LanguageVariationIsoCode.SZ, "English (Eswatini)" },
				{ LanguageVariationIsoCode.TC, "English (Turks & Caicos Islands)" },
				{ LanguageVariationIsoCode.TK, "English (Tokelau)" },
				{ LanguageVariationIsoCode.TO, "English (Tonga)" },
				{ LanguageVariationIsoCode.TT, "English (Trinidad & Tobago)" },
				{ LanguageVariationIsoCode.TV, "English (Tuvalu)" },
				{ LanguageVariationIsoCode.TZ, "English (Tanzania)" },
				{ LanguageVariationIsoCode.UG, "English (Uganda)" },
				{ LanguageVariationIsoCode.UM, "English (U.S. Outlying Islands)" },
				{ LanguageVariationIsoCode.US, "English (United States)" },
				{ LanguageVariationIsoCode.VC, "English (St. Vincent & Grenadines)" },
				{ LanguageVariationIsoCode.VG, "English (British Virgin Islands)" },
				{ LanguageVariationIsoCode.VI, "English (U.S. Virgin Islands)" },
				{ LanguageVariationIsoCode.VU, "English (Vanuatu)" },
				{ LanguageVariationIsoCode.WS, "English (Samoa)" },
				{ LanguageVariationIsoCode.ZA, "English (South Africa)" },
				{ LanguageVariationIsoCode.ZM, "English (Zambia)" },
				{ LanguageVariationIsoCode.ZW, "English (Zimbabwe)" },
			});
	}
}
