namespace HumanLanguages.LanguageNames
{
	public sealed class ES
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Spanish" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "spansk" },
				{ LanguageIsoCode.af, "Spaans" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ስፓንኛ" },
				{ LanguageIsoCode.ar, "الأسبانية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "ispan dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "іспанскі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "испански" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "স্পেনীয়" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "španski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "espanyol" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Kinatsila" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Spagnolu" },
				{ LanguageIsoCode.cs, "španělština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sbaeneg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Spanisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Ισπανικά" },
				{ LanguageIsoCode.eo, "hispana" },
				{ LanguageIsoCode.es, "español" },
				{ LanguageIsoCode.et, "hispaania keel" },
				{ LanguageIsoCode.eu, "gaztelania" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "اسپانیایی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Espanja" },
				{ LanguageIsoCode.fil, "Espanyol" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Espagnol" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Spaansk" },
				{ LanguageIsoCode.ga, "Spainnis" },
				{ LanguageIsoCode.gd, "Spàinneach" },
				{ LanguageIsoCode.gl, "castelán" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સ્પૅનિશ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Mutanen Espanya" },
				{ LanguageIsoCode.haw, "Kepania" },
				{ LanguageIsoCode.he, "ספרדית" },
				{ LanguageIsoCode.hi, "स्पैनिश" },
				{ LanguageIsoCode.hr, "španjolski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "spanyol" },
				{ LanguageIsoCode.hy, "իսպաներեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Orang Spanyol" },
				{ LanguageIsoCode.ig, "Spanish" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "spænska, spænskt" },
				{ LanguageIsoCode.it, "spagnolo" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "スペイン語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Spanyol" },
				{ LanguageIsoCode.ka, "ესპანური" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "испан" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ភាសាអេស្ប៉ាញ" },
				{ LanguageIsoCode.kn, "ಸ್ಪ್ಯಾನಿಷ್" },
				{ LanguageIsoCode.ko, "스페인의" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Испанча" },
				{ LanguageIsoCode.la, "hispanice" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Spuenesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ແອສປາໂຍນ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "ispanų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "spāņu valoda" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Fikarohana" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Paniora" },
				{ LanguageIsoCode.mk, "шпански" },
				{ LanguageIsoCode.ml, "സ്പാനിഷ്" },
				{ LanguageIsoCode.mn, "Испани" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "स्पॅनिश" },
				{ LanguageIsoCode.ms, "bahasa Sepanyol" },
				{ LanguageIsoCode.mt, "Spanjol" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ငပိ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "spansk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "स्पेनिस" },
				{ LanguageIsoCode.nl, "Spaans" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସ୍ପାନିସ୍" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਸਪੇਨੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "hiszpański" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "هسپانیه ایی" },
				{ LanguageIsoCode.pt, "Espanhol" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Spaniolă" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "испанский" },
				{ LanguageIsoCode.rw, "Icyesipanyoli" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اندلسي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ස්පාඤ්ඤ" },
				{ LanguageIsoCode.sk, "španielčina" },
				{ LanguageIsoCode.sl, "španski" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiSpanish" },
				{ LanguageIsoCode.so, "Isbaanish" },
				{ LanguageIsoCode.sq, "Spanjisht" },
				{ LanguageIsoCode.sr, "Шпански" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sepanish" },
				{ LanguageIsoCode.su, "Spanyol" },
				{ LanguageIsoCode.sv, "spanska" },
				{ LanguageIsoCode.sw, "Kihispania" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஸ்பானிஷ்" },
				{ LanguageIsoCode.te, "స్పానిష్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "испанӣ" },
				{ LanguageIsoCode.th, "สเปน" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Ispan" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "İspanyol" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Испан" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "ئىسپانچە" },
				{ LanguageIsoCode.uk, "Іспанська" },
				{ LanguageIsoCode.ur, "ہسپانوی" },
				{ LanguageIsoCode.uz, "ispancha" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "người Tây Ban Nha" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Spanish" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "שפּאַניש" },
				{ LanguageIsoCode.yo, "Sipeeni" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "西班牙语" },
				{ LanguageIsoCode.zu, "ISpanishi" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.AR, "Spanish (Argentina)" },
				{ LanguageVariationIsoCode.BO, "Spanish (Bolivia)" },
				{ LanguageVariationIsoCode.BR, "Spanish (Brazil)" },
				{ LanguageVariationIsoCode.BZ, "Spanish (Belize)" },
				{ LanguageVariationIsoCode.CL, "Spanish (Chile)" },
				{ LanguageVariationIsoCode.CO, "Spanish (Colombia)" },
				{ LanguageVariationIsoCode.CR, "Spanish (Costa Rica)" },
				{ LanguageVariationIsoCode.CU, "Spanish (Cuba)" },
				{ LanguageVariationIsoCode.DO, "Spanish (Dominican Republic)" },
				{ LanguageVariationIsoCode.EC, "Spanish (Ecuador)" },
				{ LanguageVariationIsoCode.ES, "Spanish (Spain)" },
				{ LanguageVariationIsoCode.GQ, "Spanish (Equatorial Guinea)" },
				{ LanguageVariationIsoCode.GT, "Spanish (Guatemala)" },
				{ LanguageVariationIsoCode.HN, "Spanish (Honduras)" },
				{ LanguageVariationIsoCode.MX, "Spanish (Mexico)" },
				{ LanguageVariationIsoCode.NI, "Spanish (Nicaragua)" },
				{ LanguageVariationIsoCode.PA, "Spanish (Panama)" },
				{ LanguageVariationIsoCode.PE, "Spanish (Peru)" },
				{ LanguageVariationIsoCode.PH, "Spanish (Philippines)" },
				{ LanguageVariationIsoCode.PR, "Spanish (Puerto Rico)" },
				{ LanguageVariationIsoCode.PY, "Spanish (Paraguay)" },
				{ LanguageVariationIsoCode.SV, "Spanish (El Salvador)" },
				{ LanguageVariationIsoCode.US, "Spanish (United States)" },
				{ LanguageVariationIsoCode.UY, "Spanish (Uruguay)" },
				{ LanguageVariationIsoCode.VE, "Spanish (Venezuela)" },
			});
	}
}
