namespace HumanLanguages.LanguageNames
{
	public sealed class FF
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Fulah" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "fulah" },
				{ LanguageIsoCode.af, "Fulah" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ፉላህ" },
				{ LanguageIsoCode.ar, "فولا" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Fulah" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Фула" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Фула" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "ফুলা" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Fulah" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Fulah" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Fulah" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Fulah" },
				{ LanguageIsoCode.cs, "Fulah" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Ffwlah" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Fulah" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Φούλα" },
				{ LanguageIsoCode.eo, "Fulah" },
				{ LanguageIsoCode.es, "Fulá" },
				{ LanguageIsoCode.et, "Fulah" },
				{ LanguageIsoCode.eu, "Fula" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "فولا" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Fulah" },
				{ LanguageIsoCode.fil, "Fulah" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Peul" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Fulah" },
				{ LanguageIsoCode.ga, "Fulah" },
				{ LanguageIsoCode.gd, "Fulah" },
				{ LanguageIsoCode.gl, "Fula" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ફુલાહ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Fulah" },
				{ LanguageIsoCode.haw, "ʻO Fulah" },
				{ LanguageIsoCode.he, "פולה" },
				{ LanguageIsoCode.hi, "फुलाह" },
				{ LanguageIsoCode.hr, "Fulah" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Fulah" },
				{ LanguageIsoCode.hy, "Ֆուլահ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Fulah" },
				{ LanguageIsoCode.ig, "Fulah" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Fúla" },
				{ LanguageIsoCode.it, "Fulah" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "フラ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Fulah" },
				{ LanguageIsoCode.ka, "ფულა" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Фула" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ហ្វូឡា" },
				{ LanguageIsoCode.kn, "ಫುಲಾಹ್" },
				{ LanguageIsoCode.ko, "풀라" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Fulah" },
				{ LanguageIsoCode.la, "Fulah" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Fulah" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ຟູລາ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Fulah" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Fulah" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Fulah" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Fulah" },
				{ LanguageIsoCode.mk, "Фулах" },
				{ LanguageIsoCode.ml, "ഫുലാഹ്" },
				{ LanguageIsoCode.mn, "Фула" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "फुला" },
				{ LanguageIsoCode.ms, "Fulah" },
				{ LanguageIsoCode.mt, "Fulah" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဖူလာ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Fulah" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "फुलह" },
				{ LanguageIsoCode.nl, "Fula" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଫୁଲା" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਫੁਲਹ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Fula" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "فوله" },
				{ LanguageIsoCode.pt, "Fulá" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Fulah" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Фула" },
				{ LanguageIsoCode.rw, "Fulah" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "ڦل" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ෆුලා" },
				{ LanguageIsoCode.sk, "Fulah" },
				{ LanguageIsoCode.sl, "Fulah" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Fulah" },
				{ LanguageIsoCode.so, "Fulah" },
				{ LanguageIsoCode.sq, "Fulah" },
				{ LanguageIsoCode.sr, "Фулах" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Fulah" },
				{ LanguageIsoCode.su, "Fulah" },
				{ LanguageIsoCode.sv, "Fulah" },
				{ LanguageIsoCode.sw, "Fula" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஃபுலா" },
				{ LanguageIsoCode.te, "ఫూలా" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Фулах" },
				{ LanguageIsoCode.th, "ฟูลาห์" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Fulah" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Fula" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Фула" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Fulah" },
				{ LanguageIsoCode.uk, "Фула" },
				{ LanguageIsoCode.ur, "فلاہ" },
				{ LanguageIsoCode.uz, "Fula" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Fulah" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiFula" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "פולה" },
				{ LanguageIsoCode.yo, "Fulah" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "富拉" },
				{ LanguageIsoCode.zu, "Fulah" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ADLM, "Fulah (Adlam)" },
				{ LanguageVariationIsoCode.BF, "Fulah (Adlam, Burkina Faso)" },
				{ LanguageVariationIsoCode.CM, "Fulah (Adlam, Cameroon)" },
				{ LanguageVariationIsoCode.GH, "Fulah (Adlam, Ghana)" },
				{ LanguageVariationIsoCode.GM, "Fulah (Adlam, Gambia)" },
				{ LanguageVariationIsoCode.GN, "Fulah (Adlam, Guinea)" },
				{ LanguageVariationIsoCode.GW, "Fulah (Adlam, Guinea-Bissau)" },
				{ LanguageVariationIsoCode.LR, "Fulah (Adlam, Liberia)" },
				{ LanguageVariationIsoCode.MR, "Fulah (Adlam, Mauritania)" },
				{ LanguageVariationIsoCode.NE, "Fulah (Adlam, Niger)" },
				{ LanguageVariationIsoCode.NG, "Fulah (Adlam, Nigeria)" },
				{ LanguageVariationIsoCode.SL, "Fulah (Adlam, Sierra Leone)" },
				{ LanguageVariationIsoCode.SN, "Fulah (Adlam, Senegal)" },
				{ LanguageVariationIsoCode.LATN, "Fulah (Latin)" },
			});
	}
}
