namespace HumanLanguages.LanguageNames
{
	public sealed class FO
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Faroese" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "færøsk" },
				{ LanguageIsoCode.af, "Faroëes" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ፋሮኢዝ" },
				{ LanguageIsoCode.ar, "جزر فارو" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "farer dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Фарэрская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "фарьорски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "ফারোইজ" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Faroese" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "feroès" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Faroese" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Faroese" },
				{ LanguageIsoCode.cs, "faerské" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Ffaroaidd" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Färöisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Φερόε" },
				{ LanguageIsoCode.eo, "feroa" },
				{ LanguageIsoCode.es, "feroés" },
				{ LanguageIsoCode.et, "fääri saarlased" },
				{ LanguageIsoCode.eu, "Faroeera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "فاروئی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Färsaaret" },
				{ LanguageIsoCode.fil, "Faroese" },
				{ LanguageIsoCode.fo, "føroyskt" },
				{ LanguageIsoCode.fr, "Féroïen" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Faroese" },
				{ LanguageIsoCode.ga, "Faróis" },
				{ LanguageIsoCode.gd, "Fàrach" },
				{ LanguageIsoCode.gl, "feroés" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ફરોઝ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Faroese" },
				{ LanguageIsoCode.haw, "Faroese" },
				{ LanguageIsoCode.he, "פארואי" },
				{ LanguageIsoCode.hi, "फिरोज़ी" },
				{ LanguageIsoCode.hr, "farski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "feröeri" },
				{ LanguageIsoCode.hy, "Ֆարերերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "orang Faroe" },
				{ LanguageIsoCode.ig, "Ndị Faroese" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "færeyska" },
				{ LanguageIsoCode.it, "Faroese" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "フェロー語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "wong Faroe" },
				{ LanguageIsoCode.ka, "ფარერული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "фарер" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ហ្វារ៉ូស" },
				{ LanguageIsoCode.kn, "ಫರೋಸ್" },
				{ LanguageIsoCode.ko, "페로어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "фарерче" },
				{ LanguageIsoCode.la, "Faroese" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Färöer" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ຟາໂຣ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Farerų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Fēru salu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Zavatra" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Faroese" },
				{ LanguageIsoCode.mk, "фарски" },
				{ LanguageIsoCode.ml, "ഫറോസ്" },
				{ LanguageIsoCode.mn, "Фарер хэл" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "फारोसी" },
				{ LanguageIsoCode.ms, "Faroese" },
				{ LanguageIsoCode.mt, "Faroese" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဖာရိုစီ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "færøysk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "फारोइज" },
				{ LanguageIsoCode.nl, "Faeröer" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଫାରୁସ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਫ਼ਰੋਜ਼" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "farerski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "فیروز" },
				{ LanguageIsoCode.pt, "Feroês" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "feroeză" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "фарерский" },
				{ LanguageIsoCode.rw, "Faroese" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "فيروز" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ෆැරෝස්" },
				{ LanguageIsoCode.sk, "faerské" },
				{ LanguageIsoCode.sl, "ferski" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Faroese" },
				{ LanguageIsoCode.so, "Faroese" },
				{ LanguageIsoCode.sq, "Faroese" },
				{ LanguageIsoCode.sr, "Фароесе" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sefaroese" },
				{ LanguageIsoCode.su, "Faroese" },
				{ LanguageIsoCode.sv, "färöiska" },
				{ LanguageIsoCode.sw, "Kifaroe" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஃபரோஸ்" },
				{ LanguageIsoCode.te, "ఫారోస్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "форей" },
				{ LanguageIsoCode.th, "แฟโร" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Faruz" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Faroe dili" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Фарер" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Faroese" },
				{ LanguageIsoCode.uk, "Фарерська" },
				{ LanguageIsoCode.ur, "فیروزی" },
				{ LanguageIsoCode.uz, "farer" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Faroe" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiFaroese" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "פערױזיש" },
				{ LanguageIsoCode.yo, "Faroese" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "法罗语" },
				{ LanguageIsoCode.zu, "IsiFaroese" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.DK, "Faroese (Denmark)" },
				{ LanguageVariationIsoCode.FO, "Faroese (Faroe Islands)" },
			});
	}
}
