namespace HumanLanguages.LanguageNames
{
	public sealed class FR
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.af, "" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "" },
				{ LanguageIsoCode.ar, "" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "" },
				{ LanguageIsoCode.cs, "" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "" },
				{ LanguageIsoCode.da, "" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "" },
				{ LanguageIsoCode.en, "French" },
				{ LanguageIsoCode.eo, "" },
				{ LanguageIsoCode.es, "" },
				{ LanguageIsoCode.et, "" },
				{ LanguageIsoCode.eu, "" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "" },
				{ LanguageIsoCode.fil, "" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "français" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "" },
				{ LanguageIsoCode.ga, "" },
				{ LanguageIsoCode.gd, "" },
				{ LanguageIsoCode.gl, "" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "" },
				{ LanguageIsoCode.haw, "" },
				{ LanguageIsoCode.he, "" },
				{ LanguageIsoCode.hi, "" },
				{ LanguageIsoCode.hr, "" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "" },
				{ LanguageIsoCode.hy, "" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "" },
				{ LanguageIsoCode.ig, "" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "" },
				{ LanguageIsoCode.it, "" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "" },
				{ LanguageIsoCode.ka, "" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "" },
				{ LanguageIsoCode.kn, "" },
				{ LanguageIsoCode.ko, "" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "" },
				{ LanguageIsoCode.la, "" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "" },
				{ LanguageIsoCode.mk, "" },
				{ LanguageIsoCode.ml, "" },
				{ LanguageIsoCode.mn, "" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "" },
				{ LanguageIsoCode.ms, "" },
				{ LanguageIsoCode.mt, "" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "" },
				{ LanguageIsoCode.nl, "" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "" },
				{ LanguageIsoCode.pt, "" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "" },
				{ LanguageIsoCode.rw, "" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "" },
				{ LanguageIsoCode.sk, "" },
				{ LanguageIsoCode.sl, "" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "" },
				{ LanguageIsoCode.so, "" },
				{ LanguageIsoCode.sq, "" },
				{ LanguageIsoCode.sr, "" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "" },
				{ LanguageIsoCode.su, "" },
				{ LanguageIsoCode.sv, "" },
				{ LanguageIsoCode.sw, "" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "" },
				{ LanguageIsoCode.te, "" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "" },
				{ LanguageIsoCode.th, "" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "" },
				{ LanguageIsoCode.uk, "" },
				{ LanguageIsoCode.ur, "" },
				{ LanguageIsoCode.uz, "" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "" },
				{ LanguageIsoCode.yo, "" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "" },
				{ LanguageIsoCode.zu, "" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.BE, "français (Belgique)" },
				{ LanguageVariationIsoCode.BF, "français (Burkina Faso)" },
				{ LanguageVariationIsoCode.BI, "français (Burundi)" },
				{ LanguageVariationIsoCode.BJ, "français (Bénin)" },
				{ LanguageVariationIsoCode.BL, "français (Saint-Barthélemy)" },
				{ LanguageVariationIsoCode.CA, "français (Canada)" },
				{ LanguageVariationIsoCode.CD, "français (Congo [République démocratique du])" },
				{ LanguageVariationIsoCode.CF, "français (République centrafricaine)" },
				{ LanguageVariationIsoCode.CG, "français (Congo)" },
				{ LanguageVariationIsoCode.CH, "français (Suisse)" },
				{ LanguageVariationIsoCode.CI, "français (Côte d’Ivoire)" },
				{ LanguageVariationIsoCode.CM, "français (Cameroun)" },
				{ LanguageVariationIsoCode.DJ, "français (Djibouti)" },
				{ LanguageVariationIsoCode.DZ, "français (Algérie)" },
				{ LanguageVariationIsoCode.FR, "français (France)" },
				{ LanguageVariationIsoCode.GA, "français (Gabon)" },
				{ LanguageVariationIsoCode.GF, "français (Guyane française)" },
				{ LanguageVariationIsoCode.GN, "français (Guinée)" },
				{ LanguageVariationIsoCode.GP, "français (Guadeloupe)" },
				{ LanguageVariationIsoCode.GQ, "français (Guinée équatoriale)" },
				{ LanguageVariationIsoCode.HT, "français (Haïti)" },
				{ LanguageVariationIsoCode.KM, "français (Comores)" },
				{ LanguageVariationIsoCode.LU, "français (Luxembourg)" },
				{ LanguageVariationIsoCode.MA, "français (Maroc)" },
				{ LanguageVariationIsoCode.MC, "français (Monaco)" },
				{ LanguageVariationIsoCode.MF, "français (Saint-Martin)" },
				{ LanguageVariationIsoCode.MG, "français (Madagascar)" },
				{ LanguageVariationIsoCode.ML, "français (Mali)" },
				{ LanguageVariationIsoCode.MQ, "français (Martinique)" },
				{ LanguageVariationIsoCode.MR, "français (Mauritanie)" },
				{ LanguageVariationIsoCode.MU, "français (Maurice)" },
				{ LanguageVariationIsoCode.NC, "français (Nouvelle-Calédonie)" },
				{ LanguageVariationIsoCode.NE, "français (Niger)" },
				{ LanguageVariationIsoCode.PF, "français (Polynésie française)" },
				{ LanguageVariationIsoCode.PM, "français (Saint-Pierre-et-Miquelon)" },
				{ LanguageVariationIsoCode.RE, "français (La Réunion)" },
				{ LanguageVariationIsoCode.RW, "français (Rwanda)" },
				{ LanguageVariationIsoCode.SC, "français (Seychelles)" },
				{ LanguageVariationIsoCode.SN, "français (Sénégal)" },
				{ LanguageVariationIsoCode.SY, "français (Syrie)" },
				{ LanguageVariationIsoCode.TD, "français (Tchad)" },
				{ LanguageVariationIsoCode.TG, "français (Togo)" },
				{ LanguageVariationIsoCode.TN, "français (Tunisie)" },
				{ LanguageVariationIsoCode.VU, "français (Vanuatu)" },
				{ LanguageVariationIsoCode.WF, "français (Wallis-et-Futuna)" },
				{ LanguageVariationIsoCode.YT, "français (Mayotte)" },
			});
	}
}
