namespace HumanLanguages.LanguageNames
{
	public sealed class FY
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Western Frisian" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "vestfrisisk" },
				{ LanguageIsoCode.af, "Wes-Fries" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ምዕራባዊ ፍሪሲያን" },
				{ LanguageIsoCode.ar, "الفريزية الغربية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Qərbi friz dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "заходнефрызская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "западен фризийски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "পশ্চিম ফ্রিজিয়ান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "zapadnofrizijski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "frisó occidental" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Kasadpang Frisian" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Frisone occidentale" },
				{ LanguageIsoCode.cs, "západní fríština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Ffriseg y Gorllewin" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Westfriesisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Δυτικό Φριζ" },
				{ LanguageIsoCode.eo, "okcidenta frisa" },
				{ LanguageIsoCode.es, "Frisia occidental" },
				{ LanguageIsoCode.et, "läänefriisi keel" },
				{ LanguageIsoCode.eu, "Mendebaldeko frisiera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "فریزی غربی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "läntinen friisi" },
				{ LanguageIsoCode.fil, "Kanlurang Frisian" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Frison occidental" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Frysk" },
				{ LanguageIsoCode.ga, "Freaslainnis Iartharach" },
				{ LanguageIsoCode.gd, "Frisian an Iar" },
				{ LanguageIsoCode.gl, "frisona occidental" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "પશ્ચિમી ફ્રિશિયન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Farisa ta Yamma" },
				{ LanguageIsoCode.haw, "Frisian Komohana" },
				{ LanguageIsoCode.he, "מערב פריזית" },
				{ LanguageIsoCode.hi, "पश्चिमी फ़्रिसियाई" },
				{ LanguageIsoCode.hr, "zapadnofrizijski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "nyugati fríz" },
				{ LanguageIsoCode.hy, "արևմտյան ֆրիզ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Frisia Barat" },
				{ LanguageIsoCode.ig, "Western Frisia" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "vesturfrískir" },
				{ LanguageIsoCode.it, "Frisone occidentale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "西フリジア語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Frisian Kulon" },
				{ LanguageIsoCode.ka, "დასავლეთფრიზიული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Батыс фриз" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ហ្វ្រីសៀនខាងលិច" },
				{ LanguageIsoCode.kn, "ಪಶ್ಚಿಮ ಫ್ರಿಸಿಯನ್" },
				{ LanguageIsoCode.ko, "서부 프리지아어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Батыш фриз" },
				{ LanguageIsoCode.la, "Occidentalis Frisian" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Westfriesesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ຕາເວັນຕົກ Frisian" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Vakarų fryzų kalba" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Rietumfrīzu valoda" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Frisian tandrefana" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Frisian ki te hauauru" },
				{ LanguageIsoCode.mk, "западнофризиски" },
				{ LanguageIsoCode.ml, "പടിഞ്ഞാറൻ ഫ്രിസിയൻ" },
				{ LanguageIsoCode.mn, "Баруун Фриз хэл" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "वेस्टर्न फ्रिशियन" },
				{ LanguageIsoCode.ms, "Frisian Barat" },
				{ LanguageIsoCode.mt, "Friżjan tal-Punent" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Western Frisian" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "vestfrisisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "पश्चिमी फ्रिसियन" },
				{ LanguageIsoCode.nl, "West-Fries" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ପାଶ୍ଚାତ୍ୟ ଫ୍ରିସିଆନ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਪੱਛਮੀ ਫ੍ਰੀਸੀਅਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Zachodniofryzyjski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "لويديځ فريسيان" },
				{ LanguageIsoCode.pt, "Frísio Ocidental" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "frizona de vest" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Западно-фризский" },
				{ LanguageIsoCode.rw, "Iburengerazuba" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "مغربي فريسي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "බටහිර ෆ්‍රිසියානු" },
				{ LanguageIsoCode.sk, "západné frízske" },
				{ LanguageIsoCode.sl, "zahodnofrizijščina" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Western Frisian" },
				{ LanguageIsoCode.so, "Galbeedka Frisian" },
				{ LanguageIsoCode.sq, "frizianisht perëndimore" },
				{ LanguageIsoCode.sr, "западнофризијски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sefrisia sa Bophirimela" },
				{ LanguageIsoCode.su, "Frisian Kulon" },
				{ LanguageIsoCode.sv, "västfrisiska" },
				{ LanguageIsoCode.sw, "Kifrisia cha Magharibi" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "மேற்கத்திய ஃப்ரிஷியன்" },
				{ LanguageIsoCode.te, "పశ్చిమ ఫ్రిసియన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Фризи Ғарбӣ" },
				{ LanguageIsoCode.th, "ฟริเซียนตะวันตก" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Günbatar friz" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Batı Frizcesi" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Көнбатыш Фриз" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Western Frisian" },
				{ LanguageIsoCode.uk, "західнофризька" },
				{ LanguageIsoCode.ur, "مغربی فریسیائی" },
				{ LanguageIsoCode.uz, "G'arbiy friz" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tây Frisian" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiFrisian saseNtshona" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "מערב פריזיש" },
				{ LanguageIsoCode.yo, "Western Frisia" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "西弗里斯兰语" },
				{ LanguageIsoCode.zu, "IsiFrisian saseNtshonalanga" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.NL, "Western Frisian (Netherlands)" },
			});
	}
}
