namespace HumanLanguages.LanguageNames
{
	public sealed class GD
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Scottish Gaelic" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "skotsk gælisk" },
				{ LanguageIsoCode.af, "Skotse Gaelies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ስኮትላንዳዊ ጌሊክ" },
				{ LanguageIsoCode.ar, "الغيلية الاسكتلندية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Şotlandiya Qael dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "шатландская гэльская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "шотландски келтски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "স্কটস - গ্যেলিক" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Scottish Gaelic" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Gaèlic escocès" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Scottish Gaelic" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "gaelicu scozzese" },
				{ LanguageIsoCode.cs, "skotská gaelština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Gaeleg yr Alban" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "schottisch Gälisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Σκωτσέζικη Γαελική" },
				{ LanguageIsoCode.eo, "Skotgaela" },
				{ LanguageIsoCode.es, "gaélico escocés" },
				{ LanguageIsoCode.et, "šoti gaeli keel" },
				{ LanguageIsoCode.eu, "Eskoziako gaelikoa" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "گیلیک اسکاتلندی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Skotlannin gaeli" },
				{ LanguageIsoCode.fil, "Scottish Gaelic" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Gaélique écossais" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Skotsk Gaelic" },
				{ LanguageIsoCode.ga, "Gaeilge na hAlban" },
				{ LanguageIsoCode.gd, "Gàidhlig" },
				{ LanguageIsoCode.gl, "Gaélico escocés" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સ્કોટિશ ગેલિક" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Scottish Gaelic" },
				{ LanguageIsoCode.haw, "Gaelika Sekotia" },
				{ LanguageIsoCode.he, "גאלית סקוטית" },
				{ LanguageIsoCode.hi, "स्कॉटिश गेलिक" },
				{ LanguageIsoCode.hr, "škotski galski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "skót gael" },
				{ LanguageIsoCode.hy, "Շոտլանդական Գելերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Gaelik Skotlandia" },
				{ LanguageIsoCode.ig, "Scottish Gaelic" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "skosk gelíska" },
				{ LanguageIsoCode.it, "Gaelico Scozzese" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "スコットランド・ゲール語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Gaelik Skotlandia" },
				{ LanguageIsoCode.ka, "შოტლანდიური გალური" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Шотландтық гал" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ស្កុតឡេក" },
				{ LanguageIsoCode.kn, "ಸ್ಕಾಟಿಷ್ ಗೇಲಿಕ್" },
				{ LanguageIsoCode.ko, "스코틀랜드 게일어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Шотландиялык галец" },
				{ LanguageIsoCode.la, "Scotica Gaelic" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Schottesch Gaelesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Scottish Gaelic" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "škotų gėlų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "skotu gēlu valoda" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Gaelika Scottish" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Scottish Gaelic" },
				{ LanguageIsoCode.mk, "Шкотско галски" },
				{ LanguageIsoCode.ml, "സ്കോട്ടിഷ് ഗാലിക്" },
				{ LanguageIsoCode.mn, "Шотландын Гел хэл" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "स्कॉटिश गेलिक" },
				{ LanguageIsoCode.ms, "Gaelik Scotland" },
				{ LanguageIsoCode.mt, "Galliku Skoċċiż" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Scottish Gaelic" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "skotsk gælisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "स्कटिश गेलिक" },
				{ LanguageIsoCode.nl, "Schots-Gaelisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସ୍କଟିସ୍ ଗେଲିକ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਸਕਾਟਿਸ਼ ਗੇਲਿਕ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "szkocki gaelicki" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "سکاټلینډي ګیلیک" },
				{ LanguageIsoCode.pt, "gaélico escocês" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "gaelic scoțian" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Шотландский гэльский" },
				{ LanguageIsoCode.rw, "Abanya-Gaelic" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اسڪاٽش گيلڪ" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ස්කොට්ලන්ත ගේලික්" },
				{ LanguageIsoCode.sk, "škótska galčina" },
				{ LanguageIsoCode.sl, "škotska gelščina" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiGaelic cheScottish" },
				{ LanguageIsoCode.so, "Scottish Gaelic" },
				{ LanguageIsoCode.sq, "gaelishte skoceze" },
				{ LanguageIsoCode.sr, "шкотски галски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Segaeli sa Scotland" },
				{ LanguageIsoCode.su, "Gaelik Skotlandia" },
				{ LanguageIsoCode.sv, "skotsk gaeliska" },
				{ LanguageIsoCode.sw, "Kigaeli cha Kiskoti" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஸ்காட்டிஷ் கேலிக்" },
				{ LanguageIsoCode.te, "స్కాటిష్ గేలిక్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Гаэли Шотландия" },
				{ LanguageIsoCode.th, "เกลิคสก๊อตแลนด์" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Şotlandiýaly Gael" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "İskoç Galcesi" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Шотландия Гэль" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "شوتلاندىيە گال تىلى" },
				{ LanguageIsoCode.uk, "Шотландська гельська" },
				{ LanguageIsoCode.ur, "سکاٹش گیلک" },
				{ LanguageIsoCode.uz, "Shotlandiya gael tili" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Gaelic của Scotland" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiGaelic saseScottish" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "סקאַטיש גאעליש" },
				{ LanguageIsoCode.yo, "Scotland Gaelic" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "苏格兰盖尔语" },
				{ LanguageIsoCode.zu, "IsiScottish Gaelic" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.GB, "Scottish Gaelic (United Kingdom)" },
			});
	}
}
