namespace HumanLanguages.LanguageNames
{
	public sealed class HSB
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Upper Sorbian" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "oversorbisk" },
				{ LanguageIsoCode.af, "Bo-Sorbies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "የላይኛው ሶርቢያን" },
				{ LanguageIsoCode.ar, "الصوربية العليا" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Yuxarı sorb dili" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Верхнелужыцкая" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "горнолужицки" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "আপার সোরবিয়ান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Gornjolužički jezik" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "alt sòrab" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Ibabaw nga Sorbian" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "U sorabu superiore" },
				{ LanguageIsoCode.cs, "hornolužická srbština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sorbeg Uchaf" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Obersorbisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Άνω Σορβικά" },
				{ LanguageIsoCode.eo, "Supra soraba" },
				{ LanguageIsoCode.es, "alto sorabo" },
				{ LanguageIsoCode.et, "ülemsorbi" },
				{ LanguageIsoCode.eu, "Goi sorabiera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "زبان سوربی بالایی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Yläsorbi" },
				{ LanguageIsoCode.fil, "Upper Sorbian" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Haut-sorabe" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Heechsorbysk" },
				{ LanguageIsoCode.ga, "Sorbian Uachtarach" },
				{ LanguageIsoCode.gd, "Sorbais Uarach" },
				{ LanguageIsoCode.gl, "alto sorabo" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "અપર સોર્બિયન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Babban Sorbian" },
				{ LanguageIsoCode.haw, "Sorbian luna" },
				{ LanguageIsoCode.he, "סורבית עליון" },
				{ LanguageIsoCode.hi, "ऊपरी सोरबियन" },
				{ LanguageIsoCode.hr, "gornjolužičkosrpski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "felső szorb" },
				{ LanguageIsoCode.hy, "Վերին սորբիերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Sorbia Atas" },
				{ LanguageIsoCode.ig, "Oke Sorbian" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "hásorbneska" },
				{ LanguageIsoCode.it, "Alto sorabo" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "上ソルブ語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Sorbian ndhuwur" },
				{ LanguageIsoCode.ka, "ზემო სორბიული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Жоғарғы сорб" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Sorbian ខាងលើ" },
				{ LanguageIsoCode.kn, "ಮೇಲಿನ ಸೋರ್ಬಿಯನ್" },
				{ LanguageIsoCode.ko, "어퍼 소르비안" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Жогорку сорб" },
				{ LanguageIsoCode.la, "Superior Sorbian" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Uewersorbesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ເຊີເບຍເທິງ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Aukštutinė sorbų kalba" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Augšsorbs" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Sorbian ambony" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Sorbian runga" },
				{ LanguageIsoCode.mk, "горнолужички" },
				{ LanguageIsoCode.ml, "അപ്പർ സോർബിയൻ" },
				{ LanguageIsoCode.mn, "Дээд сорб" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "अप्पर सॉर्बियन" },
				{ LanguageIsoCode.ms, "Sorbian Atas" },
				{ LanguageIsoCode.mt, "Sorbjan ta’ Fuq" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Upper Sorbian" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "øvre sorbisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "माथिल्लो सोर्बियन" },
				{ LanguageIsoCode.nl, "Boven-Sorbisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଉପର ସୋର୍ବିଆନ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਅਪਰ ਸੋਰਬੀਅਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Górnołużycki" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "پورتنی سوربیان" },
				{ LanguageIsoCode.pt, "Alto Sorbio" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "sorab superior" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Верхнелужский" },
				{ LanguageIsoCode.rw, "Sorbian yo hejuru" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اپر سوربين" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ඉහළ Sorbian" },
				{ LanguageIsoCode.sk, "hornolužická srbčina" },
				{ LanguageIsoCode.sl, "gornja lužiška srbščina" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Upper Sorbian" },
				{ LanguageIsoCode.so, "Sorbian sare" },
				{ LanguageIsoCode.sq, "sorbishte e sipërme" },
				{ LanguageIsoCode.sr, "горњолужички" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Upper Sorbian" },
				{ LanguageIsoCode.su, "Sorbian Luhur" },
				{ LanguageIsoCode.sv, "övre sorbiska" },
				{ LanguageIsoCode.sw, "Upper Sorbian" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "அப்பர் சோர்பியன்" },
				{ LanguageIsoCode.te, "ఎగువ సోర్బియన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Сорби боло" },
				{ LanguageIsoCode.th, "ซอร์เบียนตอนบน" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Sorokarky Sorbian" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Yukarı Sorbca" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Upperгары Сорбия" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Upper Sorbian" },
				{ LanguageIsoCode.uk, "Верхньолужицька" },
				{ LanguageIsoCode.ur, "اوپری سوربین" },
				{ LanguageIsoCode.uz, "Yuqori sorb" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Thượng Sorbia" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Upper Sorbian" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "אויבערסארביש" },
				{ LanguageIsoCode.yo, "Sorbian oke" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "上索布语" },
				{ LanguageIsoCode.zu, "Upper Sorbian" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.DE, "Upper Sorbian (Germany)" },
			});
	}
}
