namespace HumanLanguages.LanguageNames
{
	public sealed class KHQ
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Koyra Chiini" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "koyra chiini" },
				{ LanguageIsoCode.af, "Koyra Chiini" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ኮይራ ቺኒ" },
				{ LanguageIsoCode.ar, "كويرا تشييني" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Koyra Chiini" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Койра Чыіні" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Койра Чиини" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "কয়রা চিনি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Koyra Chiini" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Koyra Chiini" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Koyra Chiini" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Koyra Chiini" },
				{ LanguageIsoCode.cs, "Koyra Chiini" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Koyra Chiini" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Koyra Chiini" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Koyra Chiini" },
				{ LanguageIsoCode.eo, "Koyra Chiini" },
				{ LanguageIsoCode.es, "Koyra Chiini" },
				{ LanguageIsoCode.et, "Koyra Chiini" },
				{ LanguageIsoCode.eu, "Koyra Chiini" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "کویرا چینی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Koyra Chiini" },
				{ LanguageIsoCode.fil, "Koyra Chiini" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Koyra Chiini" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Koyra Chiini" },
				{ LanguageIsoCode.ga, "ses Chiini" },
				{ LanguageIsoCode.gd, "ses Chiini" },
				{ LanguageIsoCode.gl, "Koyra Chiini" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "કોયરા ચીની" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Koyra Chiini" },
				{ LanguageIsoCode.haw, "Koyra Chiini" },
				{ LanguageIsoCode.he, "קוירה קייני" },
				{ LanguageIsoCode.hi, "कोयरा चीनी" },
				{ LanguageIsoCode.hr, "Koyra Chiini" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Koyra Chiini" },
				{ LanguageIsoCode.hy, "Կոյրա Չինին" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Koyra Chiini" },
				{ LanguageIsoCode.ig, "Koyra Chiini" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Koyra Chiini" },
				{ LanguageIsoCode.it, "Koyra Chiini" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "コイラ・チーニ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Koyra Chiini" },
				{ LanguageIsoCode.ka, "კოირა ჩიინი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Койра Чиини" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "កុយរ៉ាជីនី" },
				{ LanguageIsoCode.kn, "ಕೊಯ್ರಾ ಚಿನಿ" },
				{ LanguageIsoCode.ko, "코이라 치이니" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Койра Чиини" },
				{ LanguageIsoCode.la, "Koyra Chiini" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Koyra Chiini" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Koyra Chiini" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Koyra Chiini" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Koira Čīni" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Koyra Chiini" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Koyra Chiini" },
				{ LanguageIsoCode.mk, "Којра Чиини" },
				{ LanguageIsoCode.ml, "കൊയ്റ ചിയിനി" },
				{ LanguageIsoCode.mn, "Койра Чиини" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "कोयरा चिनी" },
				{ LanguageIsoCode.ms, "Koyra Chiini" },
				{ LanguageIsoCode.mt, "Koyra Chiini" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Koyra Chiini" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Koyra Chiini" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "कोयरा चिनी" },
				{ LanguageIsoCode.nl, "Koyra Chiini" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "କୋୟ୍ରା ଚିଇନି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਕੋਇਰਾ ਚੀਨੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Koyrę Chiini" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "کویره چیني" },
				{ LanguageIsoCode.pt, "Koyra Chiini" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Koyra Chiini" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Койра Киини" },
				{ LanguageIsoCode.rw, "Koyra Chiini" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "ڪويرا چني" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "කොයිරා චිනී" },
				{ LanguageIsoCode.sk, "Koyra Chiini" },
				{ LanguageIsoCode.sl, "Koyra Chiini" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Koyra Chiini" },
				{ LanguageIsoCode.so, "Koyra Chiini" },
				{ LanguageIsoCode.sq, "Koyra Chiini" },
				{ LanguageIsoCode.sr, "Коира Цхиини" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Koyra Chiini" },
				{ LanguageIsoCode.su, "Koyra Chiini" },
				{ LanguageIsoCode.sv, "Koyra Chiini" },
				{ LanguageIsoCode.sw, "Koyra Chiini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "கொய்ரா சினி" },
				{ LanguageIsoCode.te, "కోయిరా చిని" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Койра Чиини" },
				{ LanguageIsoCode.th, "คอยรา ชิอินี่" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Koýra Çini" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Koyra Chiini" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Койра Чини" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Koyra Chiini" },
				{ LanguageIsoCode.uk, "Койра Чіні" },
				{ LanguageIsoCode.ur, "کوئرہ چینی" },
				{ LanguageIsoCode.uz, "Koyra Chiini" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Koyra Chiini" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Koyra Chiini" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "קויראַ טשייני" },
				{ LanguageIsoCode.yo, "Koyra Chiini" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "科伊拉·奇尼" },
				{ LanguageIsoCode.zu, "Koyra Chiini" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ML, "Koyra Chiini (Mali)" },
			});
	}
}
