namespace HumanLanguages.LanguageNames
{
	public sealed class LRC
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Northern Luri" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nordlige luri" },
				{ LanguageIsoCode.af, "Noordelike Luri" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሰሜናዊ ሉሪ" },
				{ LanguageIsoCode.ar, "لوري الشمالية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Şimali Luri" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Паўночны Луры" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Северно Лури" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "উত্তর লুরি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Northern Luri" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Luri del Nord" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Northern Luri" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Luri di u Nordu" },
				{ LanguageIsoCode.cs, "Severní Luri" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Gogledd Luri" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Nördliches Luri" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Βόρεια Λούρι" },
				{ LanguageIsoCode.eo, "Norda Luri" },
				{ LanguageIsoCode.es, "luri del norte" },
				{ LanguageIsoCode.et, "Põhja-Luri" },
				{ LanguageIsoCode.eu, "Iparraldeko Luri" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "لر شمالی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Pohjois-Luri" },
				{ LanguageIsoCode.fil, "Hilagang Luri" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Luri du Nord" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Noardlike Luri" },
				{ LanguageIsoCode.ga, "Luri Thuaidh" },
				{ LanguageIsoCode.gd, "Luri a Tuath" },
				{ LanguageIsoCode.gl, "Luri do Norte" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ઉત્તરીય લુરી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Arewacin Luri" },
				{ LanguageIsoCode.haw, "Luri Akau" },
				{ LanguageIsoCode.he, "לורי הצפוני" },
				{ LanguageIsoCode.hi, "उत्तरी लूरी" },
				{ LanguageIsoCode.hr, "Sjeverni Luri" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Északi Luri" },
				{ LanguageIsoCode.hy, "Հյուսիսային Լուրի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Luri Utara" },
				{ LanguageIsoCode.ig, "Northern Luri" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Norður Luri" },
				{ LanguageIsoCode.it, "Luri settentrionale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "北ルリ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Lur Utara" },
				{ LanguageIsoCode.ka, "ჩრდილოეთ ლურს" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Солтүстік Лури" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "លូរីខាងជើង" },
				{ LanguageIsoCode.kn, "ಉತ್ತರ ಲೂರಿ" },
				{ LanguageIsoCode.ko, "북부 루리" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Түндүк Лури" },
				{ LanguageIsoCode.la, "Septentrionalium Luri" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Norden Luri" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ລູຣີເໜືອ" },
				{ LanguageIsoCode.lrc, "لۊری شومالی" },
				{ LanguageIsoCode.lt, "Šiaurės Luris" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Ziemeļu Luri" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Luri Avaratra" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Ruri ki te Raki" },
				{ LanguageIsoCode.mk, "Северен Лури" },
				{ LanguageIsoCode.ml, "വടക്കൻ ലൂറി" },
				{ LanguageIsoCode.mn, "Хойд Лури" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "उत्तर लुरी" },
				{ LanguageIsoCode.ms, "Luri Utara" },
				{ LanguageIsoCode.mt, "Luri tat-Tramuntana" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Luri မြောက်ပိုင်း" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nordlige Luri" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "उत्तरी लुरी" },
				{ LanguageIsoCode.nl, "Noordelijke Luri" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଉତ୍ତର ଲୁରୀ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਉੱਤਰੀ ਲੂਰੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Północne Luri" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "شمالي لوری" },
				{ LanguageIsoCode.pt, "Luri do Norte" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Northern Luri" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Северный Лури" },
				{ LanguageIsoCode.rw, "Amajyaruguru ya Luri" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اتر لوري" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "උතුරු ලුරි" },
				{ LanguageIsoCode.sk, "Severný Luri" },
				{ LanguageIsoCode.sl, "Severni Luri" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Northern Luri" },
				{ LanguageIsoCode.so, "Waqooyiga Luri" },
				{ LanguageIsoCode.sq, "Luri verior" },
				{ LanguageIsoCode.sr, "Нортхерн Лури" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Luri e ka Leboea" },
				{ LanguageIsoCode.su, "Luri kalér" },
				{ LanguageIsoCode.sv, "Norra Luri" },
				{ LanguageIsoCode.sw, "Luri ya Kaskazini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "வடக்கு லூரி" },
				{ LanguageIsoCode.te, "ఉత్తర లూరి" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Лури Шимолӣ" },
				{ LanguageIsoCode.th, "ภาคเหนือ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Demirgazyk Luri" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Kuzey Luri" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Төньяк Лури" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "شىمالىي لۇرى" },
				{ LanguageIsoCode.uk, "Північний Лурі" },
				{ LanguageIsoCode.ur, "شمالی لوری" },
				{ LanguageIsoCode.uz, "Shimoliy Luri" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Bắc Luri" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "ILuri yaseMantla" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "צפון לורי" },
				{ LanguageIsoCode.yo, "Northern Luri" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "北卢里" },
				{ LanguageIsoCode.zu, "I-Northern Luri" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.IQ, "Northern Luri (Iraq)" },
				{ LanguageVariationIsoCode.IR, "Northern Luri (Iran)" },
			});
	}
}
