namespace HumanLanguages.LanguageNames
{
	public sealed class NB
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "norsk bokmål" },
				{ LanguageIsoCode.af, "Noorse Bokmål" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "የኖርዌይ ቦክሜ" },
				{ LanguageIsoCode.ar, "النرويجية بوكمال" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Norveç BokmÃ¥l" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Нарвежская букмал" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Норвежки BokmÃ¥l" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "নরওয়েজিয়ান বোকমাল" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "norveški bokmÃ¥l" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "BokmÃ¥l noruec" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Norwegian nga BokmÃ¥l" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.cs, "norský bokmil" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Norwy BokmÃ¥l" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Norwegisches Bokmål" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Νορβηγικό Μποκμλ" },
				{ LanguageIsoCode.eo, "norvega bokmÃ¥l" },
				{ LanguageIsoCode.es, "BokmÃ¥l noruego" },
				{ LanguageIsoCode.et, "Norra BokmÃ¥l" },
				{ LanguageIsoCode.eu, "Norvegiako bokmÃ¥l" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "نروژی BokmÃ¥l" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "norjalainen BokmÃ¥l" },
				{ LanguageIsoCode.fil, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "bokmål norvégien" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Noarsk Bokmål" },
				{ LanguageIsoCode.ga, "Ioruais BokmÃ¥l" },
				{ LanguageIsoCode.gd, "BokmÃ¥l Nirribhidh" },
				{ LanguageIsoCode.gl, "noruegués bokmÃ¥l" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "નોર્વેજીયન બોકમાલ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Yaren mutanen Norway BokmÃ¥l" },
				{ LanguageIsoCode.haw, "Norewai BokmÃ¥l" },
				{ LanguageIsoCode.he, "בוקמאל הנורבגית" },
				{ LanguageIsoCode.hi, "नॉर्वेजियन बोकमाल" },
				{ LanguageIsoCode.hr, "norveški bokmÃ¥l" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "norvég BokmÃ¥l" },
				{ LanguageIsoCode.hy, "Նորվեգական Բոկմլ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "BokmÃ¥l Norwegia" },
				{ LanguageIsoCode.ig, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Norsk BokmÃ¥l" },
				{ LanguageIsoCode.it, "Bokmål norvegese" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ノルウェー語ブークミル" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.ka, "ნორვეგიული ბოკმილ" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Норвегиялық бокмал" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ន័រវែស BokmÃ¥l" },
				{ LanguageIsoCode.kn, "ನಾರ್ವೇಜಿಯನ್ ಬೊಕ್ಮಾಲ್" },
				{ LanguageIsoCode.ko, "노르웨이 보크몰" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.la, "Norvegica BokmÃ¥l" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Norwegesch Bokmål" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Norvegijos BokmÃ¥l" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "norvēģu BokmÃ¥l" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "BokmÃ¥l norvezianina" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "BokmÃ¥l Norwegian" },
				{ LanguageIsoCode.mk, "Норвешки Бокмел" },
				{ LanguageIsoCode.ml, "നോർവീജിയൻ ബോക്മാൽ" },
				{ LanguageIsoCode.mn, "Норвегийн Бокмал" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "नॉर्वेजियन बोकमाल" },
				{ LanguageIsoCode.ms, "BokmÃ¥l Norway" },
				{ LanguageIsoCode.mt, "Norveġiż BokmÃ¥l" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Norsk Bokmål" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "नर्वेजियन बोक्माएल" },
				{ LanguageIsoCode.nl, "Noorse BokmÃ¥l" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ନରୱେ ବୋକମ Ã l |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਨਾਰਵੇਜਿਅਨ ਬੋਕਮਾਲ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Norweski bokmÃ¥l" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "نارویژی بوکمل" },
				{ LanguageIsoCode.pt, "Bokmål Norueguês" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Norvegiana BokmÃ¥l" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Норвежский букмоль" },
				{ LanguageIsoCode.rw, "Norvege BokmÃ ¥ l" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "نارويجي بوڪمل" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "නෝර්වීජියානු BokmÃ¥l" },
				{ LanguageIsoCode.sk, "nórsky bokmÃ¥l" },
				{ LanguageIsoCode.sl, "norveški bokmÃ¥l" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.so, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.sq, "Bokmül norvegjeze" },
				{ LanguageIsoCode.sr, "норвешки бокмА¥л" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.su, "BokmÃ¥l Norwegia" },
				{ LanguageIsoCode.sv, "Norska Bokmål" },
				{ LanguageIsoCode.sw, "BokmÃ¥l ya Norway" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "நார்வேஜியன் போக்மால்" },
				{ LanguageIsoCode.te, "నార్వేజియన్ బోక్మాల్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Бокмали Норвегия" },
				{ LanguageIsoCode.th, "นอร์เวย์ BokmÃ¥l" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Norwegiýaly BokmÃl" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Norveçli Bokmål" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Норвегия БокмÃл" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "نورۋېگىيە بوك Ã l" },
				{ LanguageIsoCode.uk, "норвезька букмол" },
				{ LanguageIsoCode.ur, "نارویجن بوکمل" },
				{ LanguageIsoCode.uz, "Norvegiya BokmÃ¥l" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "BokmÃ¥l Na Uy" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "isiNorway BokmÃ¥l" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "נאָרוועגיש באָקמאַל" },
				{ LanguageIsoCode.yo, "Norwegian BokmÃ¥l" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "挪威语博克马尔语" },
				{ LanguageIsoCode.zu, "I-Norwegian BokmÃ¥l" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.NO, "Norwegian Bokmål (Norway)" },
				{ LanguageVariationIsoCode.SJ, "Norwegian Bokmål (Svalbard & Jan Mayen)" },
			});
	}
}
