namespace HumanLanguages.LanguageNames
{
	public sealed class ND
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "North Ndebele" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nordlige ndebele" },
				{ LanguageIsoCode.af, "Noord-Ndebele" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሰሜን ንደበለ" },
				{ LanguageIsoCode.ar, "شمال نديبيلي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Şimali Ndebele" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Паўночны Ндэбеле" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Северен Ндебеле" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "উত্তর এনদেবেলে" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "North Ndebele" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Ndebele del Nord" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Amihanan nga Ndebele" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Ndebele di u Nordu" },
				{ LanguageIsoCode.cs, "Severní Ndebele" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Ndebele Gogleddol" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Nord-Ndebele" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Βόρεια Ndebele" },
				{ LanguageIsoCode.eo, "Norda Ndebele" },
				{ LanguageIsoCode.es, "Ndebele del norte" },
				{ LanguageIsoCode.et, "Põhja-Ndebele" },
				{ LanguageIsoCode.eu, "Ipar Ndebele" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "اندبله شمالی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Pohjois-Ndebele" },
				{ LanguageIsoCode.fil, "Hilagang Ndebele" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Ndébélé Nord" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Noard Ndebele" },
				{ LanguageIsoCode.ga, "Ndebele Thuaidh" },
				{ LanguageIsoCode.gd, "Ndebele a Tuath" },
				{ LanguageIsoCode.gl, "Ndebele do Norte" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ઉત્તર Ndebele" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "North Ndebele" },
				{ LanguageIsoCode.haw, "Ndebele ʻĀkau" },
				{ LanguageIsoCode.he, "צפון נדבלה" },
				{ LanguageIsoCode.hi, "उत्तर नडेबेले" },
				{ LanguageIsoCode.hr, "Sjeverni Ndebele" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Észak-Ndebele" },
				{ LanguageIsoCode.hy, "Հյուսիսային Նդեբելե" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Ndebele Utara" },
				{ LanguageIsoCode.ig, "North Ndebele" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Norður Ndebele" },
				{ LanguageIsoCode.it, "Ndebele settentrionale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "北ンデベレ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Ndebele Utara" },
				{ LanguageIsoCode.ka, "ჩრდილოეთ ნდებელე" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Солтүстік Ндебеле" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ខាងជើង Ndebele" },
				{ LanguageIsoCode.kn, "ಉತ್ತರ Ndebele" },
				{ LanguageIsoCode.ko, "노스 은데벨레" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Түндүк Ндебеле" },
				{ LanguageIsoCode.la, "Septentrionalis Ndebele" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Nord Ndebele" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Ndebele ເໜືອ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Šiaurės Ndebele" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Ziemeļu Ndebele" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Ndebele Avaratra" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Ndebele ki te Raki" },
				{ LanguageIsoCode.mk, "Северен Ндебеле" },
				{ LanguageIsoCode.ml, "നോർത്ത് എൻഡെബെലെ" },
				{ LanguageIsoCode.mn, "Хойд Ндебеле" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "उत्तर Ndebele" },
				{ LanguageIsoCode.ms, "Ndebele Utara" },
				{ LanguageIsoCode.mt, "North Ndebele" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "မြောက်ဘက် Ndebele" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nord-Ndebele" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "उत्तर Ndebele" },
				{ LanguageIsoCode.nl, "Noord-Ndebele" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଉତ୍ତର Ndebele" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਉੱਤਰੀ ਨਡੇਬੇਲ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Północne Ndebele" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "شمالي ندبیلي" },
				{ LanguageIsoCode.pt, "Ndebele do Norte" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Ndebele de Nord" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Северный Ндебеле" },
				{ LanguageIsoCode.rw, "Amajyaruguru ya Ndebele" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اتر Ndebele" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "උතුරු Ndebele" },
				{ LanguageIsoCode.sk, "Severné Ndebele" },
				{ LanguageIsoCode.sl, "Severni Ndebele" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "North Ndebele" },
				{ LanguageIsoCode.so, "Waqooyiga Ndebele" },
				{ LanguageIsoCode.sq, "Ndebele e Veriut" },
				{ LanguageIsoCode.sr, "Нортх Ндебеле" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Ndebele Leboya" },
				{ LanguageIsoCode.su, "Ndebele kalér" },
				{ LanguageIsoCode.sv, "Norra Ndebele" },
				{ LanguageIsoCode.sw, "Ndebele ya Kaskazini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "வடக்கு Ndebele" },
				{ LanguageIsoCode.te, "ఉత్తర Ndebele" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Ндебели Шимолӣ" },
				{ LanguageIsoCode.th, "นอร์ธเดเบเล" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Demirgazyk Ndebele" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Kuzey Ndebele" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Төньяк Ндебеле" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "North Ndebele" },
				{ LanguageIsoCode.uk, "Північний Ндебеле" },
				{ LanguageIsoCode.ur, "شمالی ندابیلی" },
				{ LanguageIsoCode.uz, "Shimoliy Ndebele" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Bắc Ndebele" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiNdebele saseMntla" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "צפון נדעבעלע" },
				{ LanguageIsoCode.yo, "North Ndebele" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "北恩德贝莱" },
				{ LanguageIsoCode.zu, "IsiNdebele saseNyakatho" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ZW, "North Ndebele (Zimbabwe)" },
			});
	}
}
