namespace HumanLanguages.LanguageNames
{
	public sealed class NDS
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Low German" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "plattysk" },
				{ LanguageIsoCode.af, "Nederduits" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ዝቅተኛ ጀርመንኛ" },
				{ LanguageIsoCode.ar, "ألمانية منخفضة" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Aşağı alman" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "ніжненямецкая" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "долнонемски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "নিম্ন জার্মান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "niskonjemački" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "baix alemany" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Ubos nga Aleman" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Low German" },
				{ LanguageIsoCode.cs, "Nízká němčina" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Isel Almaeneg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Plattdeutsch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Κάτω Γερμανικά" },
				{ LanguageIsoCode.eo, "malaltgermana" },
				{ LanguageIsoCode.es, "bajo alemán" },
				{ LanguageIsoCode.et, "alamsaksa" },
				{ LanguageIsoCode.eu, "Behe alemana" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "آلمانی پایین" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "alasaksalainen" },
				{ LanguageIsoCode.fil, "Mababang Aleman" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Bas allemand" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Nederdútsk" },
				{ LanguageIsoCode.ga, "Íseal-Ghearmáinis" },
				{ LanguageIsoCode.gd, "Gearmailtis ìosal" },
				{ LanguageIsoCode.gl, "baixo alemán" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "લો જર્મન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Ƙananan Jamusanci" },
				{ LanguageIsoCode.haw, "Kelemānia haʻahaʻa" },
				{ LanguageIsoCode.he, "גרמנית נמוכה" },
				{ LanguageIsoCode.hi, "निम्न जर्मन" },
				{ LanguageIsoCode.hr, "donjonjemački" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "alnémet" },
				{ LanguageIsoCode.hy, "ցածր գերմաներեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Jerman rendah" },
				{ LanguageIsoCode.ig, "German dị ala" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Lágþýska" },
				{ LanguageIsoCode.it, "Basso tedesco" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "低地ドイツ語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Low German" },
				{ LanguageIsoCode.ka, "დაბალი გერმანული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Төмен неміс" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "អាល្លឺម៉ង់ទាប" },
				{ LanguageIsoCode.kn, "ಲೋ ಜರ್ಮನ್" },
				{ LanguageIsoCode.ko, "저지 독일어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Төмөнкү немис" },
				{ LanguageIsoCode.la, "Low German" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Nidderdäitsch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ເຍຍລະມັນຕ່ໍາ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Žemutinė vokiečių kalba" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "lejasvācu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Alemà ambany" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Tiamana iti" },
				{ LanguageIsoCode.mk, "долногермански" },
				{ LanguageIsoCode.ml, "താഴ്ന്ന ജർമ്മൻ" },
				{ LanguageIsoCode.mn, "Бага герман" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "कमी जर्मन" },
				{ LanguageIsoCode.ms, "Jerman rendah" },
				{ LanguageIsoCode.mt, "Ġermaniż baxx" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "အနိမ့်ဂျာမန်" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nedertysk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "Low German" },
				{ LanguageIsoCode.ne, "कम जर्मन" },
				{ LanguageIsoCode.nl, "Laag Duits" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ନିମ୍ନ ଜର୍ମାନ" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਘੱਟ ਜਰਮਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Niskoniemiecki" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "ټیټ الماني" },
				{ LanguageIsoCode.pt, "Baixo alemão" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "joasa germană" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Нижненемецкий" },
				{ LanguageIsoCode.rw, "Ikidage cyo hasi" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "گھٽ جرمن" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "පහත් ජර්මානු" },
				{ LanguageIsoCode.sk, "Nízka nemčina" },
				{ LanguageIsoCode.sl, "nizkonemščina" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Low German" },
				{ LanguageIsoCode.so, "Jarmal hooseeya" },
				{ LanguageIsoCode.sq, "gjermanishtja e ulët" },
				{ LanguageIsoCode.sr, "нисконемачки" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sejeremane se tlase" },
				{ LanguageIsoCode.su, "Low Jerman" },
				{ LanguageIsoCode.sv, "lågtyska" },
				{ LanguageIsoCode.sw, "Kijerumani cha chini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "குறைந்த ஜெர்மன்" },
				{ LanguageIsoCode.te, "తక్కువ జర్మన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Олмонии паст" },
				{ LanguageIsoCode.th, "เยอรมันต่ำ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Pes nemes" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Düşük Almanca" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Түбән немец" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Low German" },
				{ LanguageIsoCode.uk, "нижньонімецька" },
				{ LanguageIsoCode.ur, "کم جرمن" },
				{ LanguageIsoCode.uz, "Past nemis" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiếng Hạ Đức" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiJamani esiphantsi" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "נידעריק דייַטש" },
				{ LanguageIsoCode.yo, "German kekere" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "低地德语" },
				{ LanguageIsoCode.zu, "IsiJalimane esiphansi" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.DE, "Low German (Germany)" },
				{ LanguageVariationIsoCode.NL, "Low German (Netherlands)" },
			});
	}
}
