namespace HumanLanguages.LanguageNames
{
	public sealed class NN
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Norwegian Nynorsk" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "norsk nynorsk" },
				{ LanguageIsoCode.af, "Noorse Nynorsk" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "የኖርዌይ ኒኖርስክ" },
				{ LanguageIsoCode.ar, "نينورسك النرويجي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Norveç Nynorsk" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Нарвежскі нюнорск" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "норвежки нюнорск" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "নরওয়েজিয়ান নাইনরস্ক" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Norwegian Nynorsk" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Nynorsk noruec" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Norwegian nga Nynorsk" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Nynorsk norvegese" },
				{ LanguageIsoCode.cs, "Norský Nynorsk" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Norwyeg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Norwegisches Nynorsk" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Νορβηγική Νυνόρσκ" },
				{ LanguageIsoCode.eo, "Norvega Nynorsk" },
				{ LanguageIsoCode.es, "nynorsk noruego" },
				{ LanguageIsoCode.et, "Norra Nynorsk" },
				{ LanguageIsoCode.eu, "Norvegiako nynorsk" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "نینورسک نروژی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Norjalainen Nynorsk" },
				{ LanguageIsoCode.fil, "Norwegian Nynorsk" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Norvégien nynorsk" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Noarsk Nynorsk" },
				{ LanguageIsoCode.ga, "Ioruais Nynorsk" },
				{ LanguageIsoCode.gd, "Nirribhidh" },
				{ LanguageIsoCode.gl, "Nynorsk noruegués" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "નોર્વેજીયન નાયનોર્સ્ક" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Yaren mutanen Norway Nynorsk" },
				{ LanguageIsoCode.haw, "Norewai Nynorsk" },
				{ LanguageIsoCode.he, "נינורסק נורבגי" },
				{ LanguageIsoCode.hi, "नॉर्वेजियन नाइनोर्स्क" },
				{ LanguageIsoCode.hr, "norveški nynorsk" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "norvég Nynorsk" },
				{ LanguageIsoCode.hy, "Նորվեգիայի Նյունորսկ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Nynorsk Norwegia" },
				{ LanguageIsoCode.ig, "Norwegian Nynorsk" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "nýnorska" },
				{ LanguageIsoCode.it, "Nynorsk norvegese" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ノルウェー語ニーノスク" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Nynorsk Norwegia" },
				{ LanguageIsoCode.ka, "ნორვეგიული ნინორსკი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Норвегиялық Нинорск" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ន័រវេសនីន័រស" },
				{ LanguageIsoCode.kn, "ನಾರ್ವೇಜಿಯನ್ ನೈನೋರ್ಸ್ಕ್" },
				{ LanguageIsoCode.ko, "노르웨이 뉘노르스크" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Норвегиялык Нинорск" },
				{ LanguageIsoCode.la, "Norvegica Nynorsk" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Norwegesch Nynorsk" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Norwegian Nynorsk" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Norvegijos Nynorsk" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Norvēģijas Ņnorska" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Norvezy Nynorsk" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Norwegian Nynorsk" },
				{ LanguageIsoCode.mk, "Норвешки Нинорск" },
				{ LanguageIsoCode.ml, "നോർവീജിയൻ നൈനോർസ്ക്" },
				{ LanguageIsoCode.mn, "Норвегийн Нинорск" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "नॉर्वेजियन निनॉर्स्क" },
				{ LanguageIsoCode.ms, "Nynorsk Norway" },
				{ LanguageIsoCode.mt, "Nynorsk Norveġiż" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Norwegian Nynorsk" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "norsk nynorsk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "नर्वेजियन Nynorsk" },
				{ LanguageIsoCode.nl, "Noorse Nynorsk" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ନରୱେଜ୍ ନାଇନୋରସ୍କ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਨਾਰਵੇਜਿਅਨ ਨਿਨੋਰਸਕ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Norweski Nynorsk" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "نارویژی نینورسک" },
				{ LanguageIsoCode.pt, "Norueguês Nynorsk" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Nynorsk norvegian" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Норвежский Нюнорск" },
				{ LanguageIsoCode.rw, "Norvege Nynorsk" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "نارويجن Nynorsk" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "නෝර්වීජියානු Nynorsk" },
				{ LanguageIsoCode.sk, "Nórsky Nynorsk" },
				{ LanguageIsoCode.sl, "norveški nynorsk" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Norwegian Nynorsk" },
				{ LanguageIsoCode.so, "Norwegian Nynorsk" },
				{ LanguageIsoCode.sq, "Nynorsk norvegjez" },
				{ LanguageIsoCode.sr, "норвешки Нинорск" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Norwegian Nynorsk" },
				{ LanguageIsoCode.su, "Nynorsk Norwegia" },
				{ LanguageIsoCode.sv, "norsk nynorsk" },
				{ LanguageIsoCode.sw, "Kinorwe Kipya" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "நார்வேஜியன் நைனார்ஸ்க்" },
				{ LanguageIsoCode.te, "నార్వేజియన్ Nynorsk" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Нинорски Норвегия" },
				{ LanguageIsoCode.th, "นอร์เวย์ นีนอร์สค์" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Norwegiýaly Nynorsk" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Norveç Nynorsk" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Норвегия Нинорск" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "نورۋېگىيە نىنورسك" },
				{ LanguageIsoCode.uk, "норвезький нюнорск" },
				{ LanguageIsoCode.ur, "نارویجن نینورسک" },
				{ LanguageIsoCode.uz, "Norvegiya Nynorsk" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Nynorsk của Na Uy" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Norwegian Nynorsk" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "נאָרוועגיש ניינאָרסק" },
				{ LanguageIsoCode.yo, "Norwegian Nynorsk" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "挪威尼诺斯克语" },
				{ LanguageIsoCode.zu, "I-Norwegian Nynorsk" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.NO, "Norwegian Nynorsk (Norway)" },
			});
	}
}
