namespace HumanLanguages.LanguageNames
{
	public sealed class NQO
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Nâ€™Ko" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nâ€™ko" },
				{ LanguageIsoCode.af, "Nâ€™Ko" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ናኢኮ" },
				{ LanguageIsoCode.ar, "نكو" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Nâ € ™ Ko" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Nâ€™Ко" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Nâ€™Ko" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "না" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Nâ€™Ko" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "N'Ko" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Nâ€™ Ko" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "N'Ko" },
				{ LanguageIsoCode.cs, "Nâ€™Ko" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Na Co" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "N'Ko" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Nâ€™Ko" },
				{ LanguageIsoCode.eo, "Nâ€™Ko" },
				{ LanguageIsoCode.es, "n'ko" },
				{ LanguageIsoCode.et, "Nâ€™Ko" },
				{ LanguageIsoCode.eu, "N'Ko" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "ناکو" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Nâ€™Ko" },
				{ LanguageIsoCode.fil, "Nâ€™Ko" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "N'Ko" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Nâ€™Ko" },
				{ LanguageIsoCode.ga, "Ná Co" },
				{ LanguageIsoCode.gd, "Na Co" },
				{ LanguageIsoCode.gl, "Non Ko" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ના.કો" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Nâ€™Ko" },
				{ LanguageIsoCode.haw, "Nâ€™ Ko" },
				{ LanguageIsoCode.he, "Nâ€™Ko" },
				{ LanguageIsoCode.hi, "ना'को" },
				{ LanguageIsoCode.hr, "Nâ€™Ko" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Nâ€™Ko" },
				{ LanguageIsoCode.hy, "Նա Կո" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Tidak" },
				{ LanguageIsoCode.ig, "Na Ko" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Nâ€™Ko" },
				{ LanguageIsoCode.it, "N'Ko" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "なこ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Nâ€™ Ko" },
				{ LanguageIsoCode.ka, "ნაკო" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Nâ Ko" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ណាកូ" },
				{ LanguageIsoCode.kn, "Nâ€™Ko" },
				{ LanguageIsoCode.ko, "응코" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Nâ Ko" },
				{ LanguageIsoCode.la, "Nâ€™ Ko" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Nâ€™Ko" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Nâ€™Ko" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Nâ€™Ko" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Nâ€™Ko" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Nâ€™ Ko" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Nâ Ko" },
				{ LanguageIsoCode.mk, "На Ко" },
				{ LanguageIsoCode.ml, "Nâ€™Ko" },
				{ LanguageIsoCode.mn, "На Ко" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "ना. को" },
				{ LanguageIsoCode.ms, "Nâ€™Ko" },
				{ LanguageIsoCode.mt, "Nâ€™Ko" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "N'Ko" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nâ€™Ko" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "Nâ€™Ko" },
				{ LanguageIsoCode.nl, "N'Ko" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "Nâ € ™ କୋ" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਨਾ ਕੋ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "N'Ko" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "نه کو" },
				{ LanguageIsoCode.pt, "N'Ko" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "N'Ko" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Н'Ко" },
				{ LanguageIsoCode.rw, "Nâ € ™ Ko" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "نا ڪو" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "Nâ€™Ko" },
				{ LanguageIsoCode.sk, "Nie Ko" },
				{ LanguageIsoCode.sl, "Nâ€™Ko" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Nâ€™Ko" },
				{ LanguageIsoCode.so, "Nâ€™Ko" },
				{ LanguageIsoCode.sq, "Nâ€™Ko" },
				{ LanguageIsoCode.sr, "На€™Ко" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Nâ€™Ko" },
				{ LanguageIsoCode.su, "Nâ€™ Ko" },
				{ LanguageIsoCode.sv, "Nâ€™Ko" },
				{ LanguageIsoCode.sw, "Nâ€™Ko" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "Nâ€™கோ" },
				{ LanguageIsoCode.te, "Nâ€™కో" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "На Ко" },
				{ LanguageIsoCode.th, "น้องโก้" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Â ™ Ko" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "N'Ko" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Ko ™ Ko" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Nâ ™ ™ Ko" },
				{ LanguageIsoCode.uk, "Nâ€™Ko" },
				{ LanguageIsoCode.ur, "Nâ€™Ko" },
				{ LanguageIsoCode.uz, "Na € ™ Ko" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "N'Ko" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Nâ€™Ko" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "ניין" },
				{ LanguageIsoCode.yo, "Nâ€™Ko" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "纳科" },
				{ LanguageIsoCode.zu, "Nâ€™Ko" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.GN, "N’Ko (Guinea)" },
			});
	}
}
