namespace HumanLanguages.LanguageNames
{
	public sealed class NR
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "South Ndebele" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "sydlige ndebele" },
				{ LanguageIsoCode.af, "Suid-Ndebele" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ደቡብ ንደበለ" },
				{ LanguageIsoCode.ar, "جنوب نديبيلي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Cənubi Ndebele" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Паўднёвы Ндэбеле" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Южен Ндебеле" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "দক্ষিণ এনদেবেলে" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "South Ndebele" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Ndebele del sud" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Habagatan Ndebele" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Ndebele Sud" },
				{ LanguageIsoCode.cs, "Jižní Ndebele" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Ndebele De" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Süd-Ndebele" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Νότια Ndebele" },
				{ LanguageIsoCode.eo, "Suda Ndebele" },
				{ LanguageIsoCode.es, "Ndebele del sur" },
				{ LanguageIsoCode.et, "Lõuna-Ndebele" },
				{ LanguageIsoCode.eu, "Hego Ndebele" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "ندبل جنوبی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Etelä-Ndebele" },
				{ LanguageIsoCode.fil, "Timog Ndebele" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Ndebele du Sud" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Súd Ndebele" },
				{ LanguageIsoCode.ga, "Ndebele Theas" },
				{ LanguageIsoCode.gd, "Ndebele a Deas" },
				{ LanguageIsoCode.gl, "Ndebele do Sur" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "દક્ષિણ Ndebele" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "South Ndebele" },
				{ LanguageIsoCode.haw, "Ndebele Hema" },
				{ LanguageIsoCode.he, "דרום נדבלה" },
				{ LanguageIsoCode.hi, "दक्षिण नडेबेले" },
				{ LanguageIsoCode.hr, "Južni Ndebele" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Dél-Ndebele" },
				{ LanguageIsoCode.hy, "Հարավային Նդեբելե" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Ndebele Selatan" },
				{ LanguageIsoCode.ig, "South Ndebele" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Suður-Ndebele" },
				{ LanguageIsoCode.it, "Ndebele meridionale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "南ンデベレ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Ndebele Kidul" },
				{ LanguageIsoCode.ka, "სამხრეთ ნდებელი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Оңтүстік Ндебеле" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Ndebele ខាងត្បូង" },
				{ LanguageIsoCode.kn, "ದಕ್ಷಿಣ ನಡೆಬೆಲೆ" },
				{ LanguageIsoCode.ko, "사우스 은데벨레" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Түштүк Ндебеле" },
				{ LanguageIsoCode.la, "Meridionalis Ndebele" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Süd Ndebele" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ໃຕ້ Ndebele" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Pietų Ndebele" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Dienvidu Ndebele" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Ndebele Atsimo" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Tonga Ndebele" },
				{ LanguageIsoCode.mk, "Јужен Ндебеле" },
				{ LanguageIsoCode.ml, "സൗത്ത് എൻഡെബെലെ" },
				{ LanguageIsoCode.mn, "Өмнөд Недебеле" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "दक्षिण नेबेले" },
				{ LanguageIsoCode.ms, "Ndebele Selatan" },
				{ LanguageIsoCode.mt, "South Ndebele" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "တောင် Ndebele" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Sør-Ndebele" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "दक्षिण नदेबेले" },
				{ LanguageIsoCode.nl, "Zuid-Ndebele" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "South Ndebele" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଦକ୍ଷିଣ Ndebele" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਦੱਖਣੀ ਨਡੇਬੇਲ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Południe Ndebele" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "جنوبي ندبیلي" },
				{ LanguageIsoCode.pt, "Ndebele do Sul" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Ndebele de Sud" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Южный Ндебеле" },
				{ LanguageIsoCode.rw, "Ndebele y'Amajyepfo" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "ڏکڻ Ndebele" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "දකුණු Ndebele" },
				{ LanguageIsoCode.sk, "Južné Ndebele" },
				{ LanguageIsoCode.sl, "Južni Ndebele" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "South Ndebele" },
				{ LanguageIsoCode.so, "Koonfurta Ndebele" },
				{ LanguageIsoCode.sq, "Ndebele e Jugut" },
				{ LanguageIsoCode.sr, "Соутх Ндебеле" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "South Ndebele" },
				{ LanguageIsoCode.su, "Ndebele Kidul" },
				{ LanguageIsoCode.sv, "Södra Ndebele" },
				{ LanguageIsoCode.sw, "Ndebele Kusini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "தெற்கு Ndebele" },
				{ LanguageIsoCode.te, "దక్షిణ Ndebele" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Ндебели Ҷанубӣ" },
				{ LanguageIsoCode.th, "เซาธ์ เอ็นเดเบเล่" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Günorta Ndebele" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Güney Ndebele" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Көньяк Ндебеле" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "South Ndebele" },
				{ LanguageIsoCode.uk, "Південний Ндебеле" },
				{ LanguageIsoCode.ur, "جنوبی ندابیلی" },
				{ LanguageIsoCode.uz, "Janubiy Ndebele" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Nam Ndebele" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiNdebele saseMzantsi" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "דרום נדעבעלע" },
				{ LanguageIsoCode.yo, "South Ndebele" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "南恩德贝莱" },
				{ LanguageIsoCode.zu, "IsiNdebele saseNingizimu" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ZA, "South Ndebele (South Africa)" },
			});
	}
}
