namespace HumanLanguages.LanguageNames
{
	public sealed class NSO
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Sesotho sa Leboa" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "sesotho på leboa" },
				{ LanguageIsoCode.af, "Sesotho in Leboa" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሴሶቶ ሳ ሌቦአ" },
				{ LanguageIsoCode.ar, "سيسوتو سا ليبوا" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Leboa üçün Sesotho" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Сесота са лебоа" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Сесото са Лебоа" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "সেসোথো সা লেবোয়া" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Sesotho sa Leboa" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Sesotho sa Leboa" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Sesotho sa Leboa" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Sesotho à Leboa" },
				{ LanguageIsoCode.cs, "Sesotho sa Leboa" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sesotho a Leboa" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Sesotho sa Leboa" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Sesotho sa Leboa" },
				{ LanguageIsoCode.eo, "Sesotho sa Leboa" },
				{ LanguageIsoCode.es, "Sesotho en Leboa" },
				{ LanguageIsoCode.et, "Sesotho sa Leboa" },
				{ LanguageIsoCode.eu, "Sesotho sa Leboa" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "سسوتو سا لبوا" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Sesotho sa Leboa" },
				{ LanguageIsoCode.fil, "Sesotho sa Leboa" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Sesotho à Leboa" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Sesotho yn Leboa" },
				{ LanguageIsoCode.ga, "Sesotho agus Leboa" },
				{ LanguageIsoCode.gd, "Sesotho ann an Leboa" },
				{ LanguageIsoCode.gl, "Sesotho sa Leboa" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સેસોથો સા લેબોઆ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Sesotho sa Leboa" },
				{ LanguageIsoCode.haw, "Sesotho ma Leboa" },
				{ LanguageIsoCode.he, "ססוטו סה לבואה" },
				{ LanguageIsoCode.hi, "सेसोथो सा लेबोआ" },
				{ LanguageIsoCode.hr, "Sesotho sa Leboa" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Sesotho sa Leboa" },
				{ LanguageIsoCode.hy, "Սեսոտո Սա Լեբոա" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Sesotho di Leboa" },
				{ LanguageIsoCode.ig, "Sesotho na Leboa" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Sesotho í Leboa" },
				{ LanguageIsoCode.it, "Sesotho sa Leboa" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "セソト サ レボア" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Sesotho ing Leboa" },
				{ LanguageIsoCode.ka, "სესოთო სა ლებოა" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Лебоадағы Сесото" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Sesotho នៅ Leboa" },
				{ LanguageIsoCode.kn, "ಸೆಸೊಥೊ ಲೆಬೋವಾ" },
				{ LanguageIsoCode.ko, "세소토 사 레보아" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Sesotho sa Leboa" },
				{ LanguageIsoCode.la, "Sesotho sa Leboa" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Sesotho zu Leboa" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Sesotho ໃນ Leboa" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Sesotho su Leboa" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Sesoto sa Leboa" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Sesotho sa Leboa" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Sesotho i Leboa" },
				{ LanguageIsoCode.mk, "Сесото во Лебоа" },
				{ LanguageIsoCode.ml, "ലെബോവയിലെ സെസോത്തോ" },
				{ LanguageIsoCode.mn, "Лебоагийн Сесото" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "लेबोआ मध्ये सेसोथो" },
				{ LanguageIsoCode.ms, "Sesotho di Leboa" },
				{ LanguageIsoCode.mt, "Sesotho sa Leboa" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Sesotho sa Leboa" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Sesotho på Leboa" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "लेबोआमा सेसोथो" },
				{ LanguageIsoCode.nl, "Sesotho sa Leboa" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସେସୋଥୋ ସା ଲେବୋଆ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਲੇਬੋਆ ਵਿੱਚ ਸੇਸੋਥੋ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Sesotho na Leboa" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "سیسوتو په لیبوا کې" },
				{ LanguageIsoCode.pt, "Sesoto em Leboa" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Sesotho sa Leboa" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Сесото са Лебоа" },
				{ LanguageIsoCode.rw, "Sesotho sa Leboa" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "ليبوا ۾ سيسوٿو" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "සෙසෝතෝ සහ ලෙබෝවා" },
				{ LanguageIsoCode.sk, "Sesotho sa Leboa" },
				{ LanguageIsoCode.sl, "Sesotho sa Leboa" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Sesotho sa Leboa" },
				{ LanguageIsoCode.so, "Sesotho ee Leboa" },
				{ LanguageIsoCode.sq, "Sesoto në Leboa" },
				{ LanguageIsoCode.sr, "Сесото са Лебоа" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sesotho sa Leboa" },
				{ LanguageIsoCode.su, "Sesotho sa Leboa" },
				{ LanguageIsoCode.sv, "Sesotho sa Leboa" },
				{ LanguageIsoCode.sw, "Sesotho sa Leboa" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "செசோதோ சா லெபோவா" },
				{ LanguageIsoCode.te, "సెసోతో లెబోవా" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Сесото дар Лебоа" },
				{ LanguageIsoCode.th, "เซโซโท ซา เลบัว" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Sesotho sa Leboa" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Sesotho sa Leboa" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Лесоа" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Sesotho sa Leboa" },
				{ LanguageIsoCode.uk, "Сесото са Лебоа" },
				{ LanguageIsoCode.ur, "سیسوتھو سا لیبوا۔" },
				{ LanguageIsoCode.uz, "Sesotho, Leboa" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Sesotho sa Leboa" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiSuthu saseLeboa" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "סעסאָטאָ אין לעבאָאָ" },
				{ LanguageIsoCode.yo, "Sesotho sa Leboa" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "塞索托萨莱博阿" },
				{ LanguageIsoCode.zu, "IsiSuthu saseLeboa" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ZA, "Sesotho sa Leboa (South Africa)" },
			});
	}
}
