namespace HumanLanguages.LanguageNames
{
	public sealed class PCM
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Nigerian Pidgin" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nigerianske pidgin" },
				{ LanguageIsoCode.af, "Nigeriese Pidgin" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ናይጄሪያ ፒጂጂን" },
				{ LanguageIsoCode.ar, "النيجيرية بجين" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Nigeriyalı Pidgin" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Нігерыйскі паджын" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Нигерийски пиджин" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "নাইজেরিয়ান পিজিন" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Nigerian Pidgin" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Pidgin nigerià" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Nigerian nga Pidgin" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Pidgin nigerianu" },
				{ LanguageIsoCode.cs, "Nigerijský Pidgin" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Pidgin Nigeria" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Nigerianisches Pidgin" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Νιγηριανός Πίτζιν" },
				{ LanguageIsoCode.eo, "Niĝeria Piĝino" },
				{ LanguageIsoCode.es, "pidgin nigeriano" },
				{ LanguageIsoCode.et, "Nigeeria Pidgin" },
				{ LanguageIsoCode.eu, "Pidgin nigeriarra" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "پیجین نیجریه" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Nigerialainen pidgin" },
				{ LanguageIsoCode.fil, "Nigerian Pidgin" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Pidgin nigérian" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Nigeriaanske Pidgin" },
				{ LanguageIsoCode.ga, "Pidgin na Nigéire" },
				{ LanguageIsoCode.gd, "Pidgin Nigerian" },
				{ LanguageIsoCode.gl, "Pidgin nixeriano" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "નાઇજિરિયન પિડજિન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Pidgin na Najeriya" },
				{ LanguageIsoCode.haw, "Pidgin Nigeria" },
				{ LanguageIsoCode.he, "פידג'ין הניגרי" },
				{ LanguageIsoCode.hi, "नाइजीरियाई पिजिन" },
				{ LanguageIsoCode.hr, "nigerijski pidgin" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "nigériai pidgin" },
				{ LanguageIsoCode.hy, "Նիգերիական Պիդգին" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Pijin Nigeria" },
				{ LanguageIsoCode.ig, "Pidgin Naijiria" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Nígerískur Pidgin" },
				{ LanguageIsoCode.it, "Pidgin nigeriano" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ナイジェリアのピジン" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Pidgin Nigeria" },
				{ LanguageIsoCode.ka, "ნიგერიელი პიჯინი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Нигериялық Пиджин" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "នីហ្សេរីយ៉ា Pidgin" },
				{ LanguageIsoCode.kn, "ನೈಜೀರಿಯನ್ ಪಿಜಿನ್" },
				{ LanguageIsoCode.ko, "나이지리아 피진" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Нигериялык Пиджин" },
				{ LanguageIsoCode.la, "Nigeria Pidgin" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Nigerian Pidgin" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ໄນຈີເຣຍ Pidgin" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Nigerijos Pidginas" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Nigērijas Pidgins" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Pidgin Nizeriana" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Pidgin Nigeria" },
				{ LanguageIsoCode.mk, "Нигериски Пиџин" },
				{ LanguageIsoCode.ml, "നൈജീരിയൻ പിജിൻ" },
				{ LanguageIsoCode.mn, "Нигерийн Пиджин" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "नायजेरियन पिडगिन" },
				{ LanguageIsoCode.ms, "Pidgin Nigeria" },
				{ LanguageIsoCode.mt, "Pidgin Niġerjan" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "နိုင်ဂျီးရီးယား Pidgin" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "nigerianske Pidgin" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "नाइजेरियन पिडगिन" },
				{ LanguageIsoCode.nl, "Nigeriaanse Pidgin" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ନାଇଜେରିଆନ୍ ପିଜିନ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਨਾਈਜੀਰੀਅਨ ਪਿਜਿਨ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Nigeryjski Pidżyn" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "نایجیریا پیډین" },
				{ LanguageIsoCode.pt, "Pidgin nigeriano" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Pidgin nigerian" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Нигерийский пиджин" },
				{ LanguageIsoCode.rw, "Nigeriya Pidgin" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "نائجيرين پڊگن" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "නයිජීරියානු පිජින්" },
				{ LanguageIsoCode.sk, "nigérijský pidgin" },
				{ LanguageIsoCode.sl, "nigerijski pidgin" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Nigerian Pidgin" },
				{ LanguageIsoCode.so, "Pidgin Nigeria" },
				{ LanguageIsoCode.sq, "Nigerian Pidgin" },
				{ LanguageIsoCode.sr, "Нигериан Пидгин" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Pidgin ea Nigeria" },
				{ LanguageIsoCode.su, "Pidgin Nigerian" },
				{ LanguageIsoCode.sv, "nigerianska Pidgin" },
				{ LanguageIsoCode.sw, "Pijini ya Nigeria" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "நைஜீரிய பிட்ஜின்" },
				{ LanguageIsoCode.te, "నైజీరియన్ పిడ్జిన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Пидгини Нигерия" },
				{ LanguageIsoCode.th, "พิดจิ้นไนจีเรีย" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Nigeriýaly Pidgin" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Nijeryalı Pidgin" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Нигерия Пидгин" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Nigerian Pidgin" },
				{ LanguageIsoCode.uk, "Нігерійський піджин" },
				{ LanguageIsoCode.ur, "نائیجیرین پڈگین" },
				{ LanguageIsoCode.uz, "Nigeriyalik Pidgin" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Pidgin Nigeria" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiPidgin saseNigeria" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "ניגעריאַן פּידגין" },
				{ LanguageIsoCode.yo, "Pidgin Naijiria" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "尼日利亚洋泾浜语" },
				{ LanguageIsoCode.zu, "IsiPidgin saseNigeria" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.NG, "Nigerian Pidgin (Nigeria)" },
			});
	}
}
