namespace HumanLanguages.LanguageNames
{
	public sealed class PT
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Portuguese" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "portugisisk" },
				{ LanguageIsoCode.af, "Portugees" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ፖርቹጋልኛ" },
				{ LanguageIsoCode.ar, "البرتغالية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "portuqal" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "партугальская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "португалски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "পর্তুগীজ" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "portugalski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "portuguès" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Portuges" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Portughese" },
				{ LanguageIsoCode.cs, "portugalština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Portiwgaleg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Portugiesisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Πορτογαλικά" },
				{ LanguageIsoCode.eo, "portugala" },
				{ LanguageIsoCode.es, "portugués" },
				{ LanguageIsoCode.et, "portugali keel" },
				{ LanguageIsoCode.eu, "portugesa" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "پرتغالی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Portugalin kieli" },
				{ LanguageIsoCode.fil, "Portuges" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Portugais" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Portegeesk" },
				{ LanguageIsoCode.ga, "Portaingéilis" },
				{ LanguageIsoCode.gd, "Portugalach" },
				{ LanguageIsoCode.gl, "portugués" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "પોર્ટુગીઝ" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Fotigal" },
				{ LanguageIsoCode.haw, "Pukikī" },
				{ LanguageIsoCode.he, "פורטוגזית" },
				{ LanguageIsoCode.hi, "पुर्तगाली" },
				{ LanguageIsoCode.hr, "Portugalski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "portugál" },
				{ LanguageIsoCode.hy, "պորտուգալերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Portugis" },
				{ LanguageIsoCode.ig, "Portuguese" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "portúgalska" },
				{ LanguageIsoCode.it, "portoghese" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ポルトガル語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Portugis" },
				{ LanguageIsoCode.ka, "პორტუგალიური" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "португал тілі" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ព័រទុយហ្គាល់" },
				{ LanguageIsoCode.kn, "ಪೋರ್ಚುಗೀಸ್" },
				{ LanguageIsoCode.ko, "포르투갈 인" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Португалча" },
				{ LanguageIsoCode.la, "Portuguese" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Portugisesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ພາສາປອກຕຸຍການ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "portugalų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "portugāļu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "portogey" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Potiti" },
				{ LanguageIsoCode.mk, "португалски" },
				{ LanguageIsoCode.ml, "പോർച്ചുഗീസ്" },
				{ LanguageIsoCode.mn, "португал" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "पोर्तुगीज" },
				{ LanguageIsoCode.ms, "Portugis" },
				{ LanguageIsoCode.mt, "Portugiż" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ပေါ်တူဂီ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "portugisisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "पोर्चुगिज" },
				{ LanguageIsoCode.nl, "Portugees" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ପର୍ତ୍ତୁଗୀଜ୍" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਪੁਰਤਗਾਲੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "portugalski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "پورتګالي" },
				{ LanguageIsoCode.pt, "Português" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "portugheză" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "португальский" },
				{ LanguageIsoCode.rw, "Igiporutugali" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "پرتگالي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "පෘතුගීසි" },
				{ LanguageIsoCode.sk, "portugalčina" },
				{ LanguageIsoCode.sl, "portugalščina" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiPutukezi" },
				{ LanguageIsoCode.so, "Boortaqiis" },
				{ LanguageIsoCode.sq, "portugeze" },
				{ LanguageIsoCode.sr, "португалски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sepotoketsi" },
				{ LanguageIsoCode.su, "Portugis" },
				{ LanguageIsoCode.sv, "portugisiska" },
				{ LanguageIsoCode.sw, "Kireno" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "போர்த்துகீசியம்" },
				{ LanguageIsoCode.te, "పోర్చుగీస్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "португалӣ" },
				{ LanguageIsoCode.th, "โปรตุเกส" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Portugaliýa" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Portekizce" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Португал" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "پورتۇگال تىلى" },
				{ LanguageIsoCode.uk, "португальська" },
				{ LanguageIsoCode.ur, "پرتگالی" },
				{ LanguageIsoCode.uz, "portugal" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "tiếng Bồ Đào Nha" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiPhuthukezi" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "פּאָרטוגעזיש" },
				{ LanguageIsoCode.yo, "Portuguese" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "葡萄牙语" },
				{ LanguageIsoCode.zu, "IsiPutukezi" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.AO, "Portuguese (Angola)" },
				{ LanguageVariationIsoCode.BR, "Portuguese (Brazil)" },
				{ LanguageVariationIsoCode.CH, "Portuguese (Switzerland)" },
				{ LanguageVariationIsoCode.CV, "Portuguese (Cabo Verde)" },
				{ LanguageVariationIsoCode.GQ, "Portuguese (Equatorial Guinea)" },
				{ LanguageVariationIsoCode.GW, "Portuguese (Guinea-Bissau)" },
				{ LanguageVariationIsoCode.LU, "Portuguese (Luxembourg)" },
				{ LanguageVariationIsoCode.MO, "Portuguese (Macao SAR)" },
				{ LanguageVariationIsoCode.MZ, "Portuguese (Mozambique)" },
				{ LanguageVariationIsoCode.PT, "Portuguese (Portugal)" },
				{ LanguageVariationIsoCode.ST, "Portuguese (São Tomé & Príncipe)" },
				{ LanguageVariationIsoCode.TL, "Portuguese (Timor-Leste)" },
			});
	}
}
