namespace HumanLanguages.LanguageNames
{
	public sealed class RU
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Russian" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "russisk" },
				{ LanguageIsoCode.af, "Russies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ራሺያኛ" },
				{ LanguageIsoCode.ar, "الروسية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "rus" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "рускі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Руски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "রাশিয়ান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "ruski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "rus" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Ruso" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Russu" },
				{ LanguageIsoCode.cs, "ruština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Rwsiaidd" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Russisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Ρωσική" },
				{ LanguageIsoCode.eo, "rusa" },
				{ LanguageIsoCode.es, "ruso" },
				{ LanguageIsoCode.et, "vene keel" },
				{ LanguageIsoCode.eu, "errusiera" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "روسی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Venäjän kieli" },
				{ LanguageIsoCode.fil, "Ruso" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "russe" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Russysk" },
				{ LanguageIsoCode.ga, "Rúisis" },
				{ LanguageIsoCode.gd, "Ruiseanach" },
				{ LanguageIsoCode.gl, "ruso" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "રશિયન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Rashanci" },
				{ LanguageIsoCode.haw, "Lukia" },
				{ LanguageIsoCode.he, "רוּסִי" },
				{ LanguageIsoCode.hi, "रूसी" },
				{ LanguageIsoCode.hr, "ruski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "orosz" },
				{ LanguageIsoCode.hy, "ռուսերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Rusia" },
				{ LanguageIsoCode.ig, "Russian" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Rússneskt" },
				{ LanguageIsoCode.it, "russo" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ロシア" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Rusian" },
				{ LanguageIsoCode.ka, "რუსული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "орыс" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "រុស្សី" },
				{ LanguageIsoCode.kn, "ರಷ್ಯನ್" },
				{ LanguageIsoCode.ko, "러시아인" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Орусча" },
				{ LanguageIsoCode.la, "Russian" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Russesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ພາສາລັດເຊຍ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "rusų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "krievu valoda" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "ROSIANINA" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Ruhia" },
				{ LanguageIsoCode.mk, "руски" },
				{ LanguageIsoCode.ml, "റഷ്യൻ" },
				{ LanguageIsoCode.mn, "орос" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "रशियन" },
				{ LanguageIsoCode.ms, "bahasa Rusia" },
				{ LanguageIsoCode.mt, "Russu" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ရုရှ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "russisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "रुसी" },
				{ LanguageIsoCode.nl, "Russisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "Russian ଷିୟ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਰੂਸੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Rosyjski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "روسي" },
				{ LanguageIsoCode.pt, "russo" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Rusă" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Русский" },
				{ LanguageIsoCode.rw, "Ikirusiya" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "روسي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "රුසියානු" },
				{ LanguageIsoCode.sk, "ruský" },
				{ LanguageIsoCode.sl, "ruski" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiRussian" },
				{ LanguageIsoCode.so, "Ruush" },
				{ LanguageIsoCode.sq, "rusisht" },
				{ LanguageIsoCode.sr, "Руски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Serussia" },
				{ LanguageIsoCode.su, "Rusia" },
				{ LanguageIsoCode.sv, "ryska" },
				{ LanguageIsoCode.sw, "Kirusi" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ரஷ்யன்" },
				{ LanguageIsoCode.te, "రష్యన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "русӣ" },
				{ LanguageIsoCode.th, "ภาษารัสเซีย" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Rus" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Rusça" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Рус" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "رۇسچە" },
				{ LanguageIsoCode.uk, "російський" },
				{ LanguageIsoCode.ur, "روسی" },
				{ LanguageIsoCode.uz, "rus" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "tiếng Nga" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiRashiya" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "רוסיש" },
				{ LanguageIsoCode.yo, "Russian" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "俄语" },
				{ LanguageIsoCode.zu, "IsiRashiya" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.BY, "Russian (Belarus)" },
				{ LanguageVariationIsoCode.KG, "Russian (Kyrgyzstan)" },
				{ LanguageVariationIsoCode.KZ, "Russian (Kazakhstan)" },
				{ LanguageVariationIsoCode.MD, "Russian (Moldova)" },
				{ LanguageVariationIsoCode.RU, "Russian (Russia)" },
				{ LanguageVariationIsoCode.UA, "Russian (Ukraine)" },
			});
	}
}
