namespace HumanLanguages.LanguageNames
{
	public sealed class SE
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Northern Sami" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "nordsamisk" },
				{ LanguageIsoCode.af, "Noord-Sami" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሰሜናዊ ሳሚ" },
				{ LanguageIsoCode.ar, "سامي الشمالي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Şimali Sami" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "паўночныя саамы" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "северни саами" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "উত্তর সামি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Northern Sami" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Sami del Nord" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Northern Sami" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Sami di u Nordu" },
				{ LanguageIsoCode.cs, "Severní Sami" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sami Gogleddol" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Nordsamisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Βόρεια Σάμη" },
				{ LanguageIsoCode.eo, "Norda samea" },
				{ LanguageIsoCode.es, "Sami del norte" },
				{ LanguageIsoCode.et, "põhjasaami" },
				{ LanguageIsoCode.eu, "Ipar samia" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "سامی شمالی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "pohjoissaamelainen" },
				{ LanguageIsoCode.fil, "Hilagang Sami" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Sami du Nord" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Noardlike Samy" },
				{ LanguageIsoCode.ga, "Sáimis Thuaidh" },
				{ LanguageIsoCode.gd, "Sami a Tuath" },
				{ LanguageIsoCode.gl, "Sami do Norte" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ઉત્તરીય સામી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Sami na Arewa" },
				{ LanguageIsoCode.haw, "Sami Akau" },
				{ LanguageIsoCode.he, "צפון סמי" },
				{ LanguageIsoCode.hi, "उत्तरी सामी" },
				{ LanguageIsoCode.hr, "sjeverni Sami" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "északi számi" },
				{ LanguageIsoCode.hy, "Հյուսիսային սամի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Sami Utara" },
				{ LanguageIsoCode.ig, "Northern Sami" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Norður-Samíska" },
				{ LanguageIsoCode.it, "Sami settentrionale" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "北サーミ人" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Sami Utara" },
				{ LanguageIsoCode.ka, "ჩრდილოეთი სამი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Солтүстік сами" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Sami ខាងជើង" },
				{ LanguageIsoCode.kn, "ಉತ್ತರ ಸಾಮಿ" },
				{ LanguageIsoCode.ko, "북부 사미어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Түндүк Сами" },
				{ LanguageIsoCode.la, "Sami septemtrionis" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Nordsamesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ພາກເຫນືອ Sami" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Šiaurės samių" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "ziemeļsāmu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Samy Avaratra" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Sami ki te Raki" },
				{ LanguageIsoCode.mk, "Северен Сами" },
				{ LanguageIsoCode.ml, "വടക്കൻ സാമി" },
				{ LanguageIsoCode.mn, "Хойд Сами" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "उत्तर सामी" },
				{ LanguageIsoCode.ms, "Sami Utara" },
				{ LanguageIsoCode.mt, "Sami tat-Tramuntana" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "မြောက်ပိုင်းဆာမိ" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Nordsamisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "उत्तरी सामी" },
				{ LanguageIsoCode.nl, "Noord-Sami" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଉତ୍ତର ସାମି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਉੱਤਰੀ ਸਾਮੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Północni Samowie" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "شمالي سامي" },
				{ LanguageIsoCode.pt, "Sami do Norte" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Sami de Nord" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Северные саамы" },
				{ LanguageIsoCode.rw, "Amajyaruguru ya Sami" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اتر سامي" },
				{ LanguageIsoCode.se, "davvisámegiella" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "උතුරු සාමි" },
				{ LanguageIsoCode.sk, "Severný Sami" },
				{ LanguageIsoCode.sl, "severni Sami" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Northern Sami" },
				{ LanguageIsoCode.so, "Waqooyiga Sami" },
				{ LanguageIsoCode.sq, "Samiu i veriut" },
				{ LanguageIsoCode.sr, "северни Сами" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Sesami sa Leboya" },
				{ LanguageIsoCode.su, "Sami Kalér" },
				{ LanguageIsoCode.sv, "nordsamiska" },
				{ LanguageIsoCode.sw, "Msami wa Kaskazini" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "வடக்கு சாமி" },
				{ LanguageIsoCode.te, "ఉత్తర సామి" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Сами Шимолӣ" },
				{ LanguageIsoCode.th, "ซามีตอนเหนือ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Demirgazyk Sami" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Kuzey Sami" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Төньяк Сами" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "شىمالىي سامى" },
				{ LanguageIsoCode.uk, "Північні саами" },
				{ LanguageIsoCode.ur, "شمالی سامی" },
				{ LanguageIsoCode.uz, "Shimoliy Sami" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Bắc Sami" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IsiSami saseMntla" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "צפון סעמי" },
				{ LanguageIsoCode.yo, "Ariwa Sami" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "北萨米人" },
				{ LanguageIsoCode.zu, "IsiSami saseNyakatho" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.FI, "Northern Sami (Finland)" },
				{ LanguageVariationIsoCode.NO, "Northern Sami (Norway)" },
				{ LanguageVariationIsoCode.SE, "Northern Sami (Sweden)" },
			});
	}
}
