namespace HumanLanguages.LanguageNames
{
	public sealed class SES
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Koyraboro Senni" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "koyraboro senni" },
				{ LanguageIsoCode.af, "Koyraboro Senni" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ኮይራቦሮ ሰኒ" },
				{ LanguageIsoCode.ar, "كويرابورو سيني" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Koyraboro Senni" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Койрабара Сенні" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Койраборо Сени" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "কয়রাবোরো সেনি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Koyraboro Senni" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Koyraboro Senni" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Koyraboro Senni" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Koyraboro Senni" },
				{ LanguageIsoCode.cs, "Koyraboro Senni" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Koyraboro Senni" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Koyraboro Senni" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Koyraboro Senni" },
				{ LanguageIsoCode.eo, "Koyraboro Senni" },
				{ LanguageIsoCode.es, "Koyraboro Senni" },
				{ LanguageIsoCode.et, "Koyraboro Senni" },
				{ LanguageIsoCode.eu, "Koyraboro Senni" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "کویرابرو سنی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Koyraboro Senni" },
				{ LanguageIsoCode.fil, "Koyraboro Senni" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Koyraboro Senni" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Koyraboro Senni" },
				{ LanguageIsoCode.ga, "sesboro Senni" },
				{ LanguageIsoCode.gd, "Koyraboro Senni" },
				{ LanguageIsoCode.gl, "Koyraboro Senni" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "કોયરાબોરો સેન્ની" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Koyraboro Senni" },
				{ LanguageIsoCode.haw, "Koyraboro Senni" },
				{ LanguageIsoCode.he, "קוירבורו סני" },
				{ LanguageIsoCode.hi, "कोयराबोरो सेन्नी" },
				{ LanguageIsoCode.hr, "Koyraboro Senni" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Koyraboro Senni" },
				{ LanguageIsoCode.hy, "Կոյրաբորո սեննի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Koyraboro Senni" },
				{ LanguageIsoCode.ig, "Koyraboro Senni" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Koyraboro Senni" },
				{ LanguageIsoCode.it, "Koyraboro Senni" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "コイラボロ仙尼" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Koyraboro Senni" },
				{ LanguageIsoCode.ka, "კოირაბორო სენი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Койраборо Сенни" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "កុយរ៉ាបូរ៉ូសេនី" },
				{ LanguageIsoCode.kn, "ಕೊಯ್ರಬೊರೊ ಸೆನ್ನಿ" },
				{ LanguageIsoCode.ko, "코이라보로 센니" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Koyraboro Senni" },
				{ LanguageIsoCode.la, "Koyraboro Senni" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Koyraboro Senni" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Koyraboro Senni" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Koyraboro Senni" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Koiraboro Senni" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Koyraboro Senni" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Koyraboro Senni" },
				{ LanguageIsoCode.mk, "Којраборо сени" },
				{ LanguageIsoCode.ml, "കൊയ്‌റബോറോ സെന്നി" },
				{ LanguageIsoCode.mn, "Койраборо Сенни" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "कोयराबोरो सेन्नी" },
				{ LanguageIsoCode.ms, "Koyraboro Senni" },
				{ LanguageIsoCode.mt, "Koyraboro Senni" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Koyraboro Senni" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Koyraboro Senni" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "कोयराबोरो सेन्नी" },
				{ LanguageIsoCode.nl, "Koyraboro Senni" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "କୋୟାବୋରୋ ସେନି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਕੋਯਰਾਬੋਰੋ ਸੇਨੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Koyraboro Senni" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "Koyraboro Senni" },
				{ LanguageIsoCode.pt, "Koyraboro Senni" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Koyraboro Senni" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Койраборо Сенни" },
				{ LanguageIsoCode.rw, "Koyraboro Senni" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "ڪويرابورو سيني" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "Koyraboro Senni" },
				{ LanguageIsoCode.sk, "Koyraboro Senni" },
				{ LanguageIsoCode.sl, "Koyraboro Senni" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Koyraboro Senni" },
				{ LanguageIsoCode.so, "Koyraboro Senni" },
				{ LanguageIsoCode.sq, "Koyraboro Senni" },
				{ LanguageIsoCode.sr, "Коираборо Сенни" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Koyraboro Senni" },
				{ LanguageIsoCode.su, "Koyraboro Senni" },
				{ LanguageIsoCode.sv, "Koyraboro Senni" },
				{ LanguageIsoCode.sw, "Koyraboro Senni" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "கொய்ராபோரோ சென்னி" },
				{ LanguageIsoCode.te, "కోయరబోరో సెన్నీ" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Койраборо Сенни" },
				{ LanguageIsoCode.th, "โคยราโบโร เซนนิ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Koýraboro Senni" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Koyraboro Senni" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Койраборо Сенни" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "كويرابورو سېننى" },
				{ LanguageIsoCode.uk, "Койраборо Сенні" },
				{ LanguageIsoCode.ur, "کویرابورو سینی۔" },
				{ LanguageIsoCode.uz, "Koyraboro Senni" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Koyraboro Senni" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Koyraboro Senni" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "קויראַבאָראָ סענני" },
				{ LanguageIsoCode.yo, "Koyraboro Senni" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "科伊拉博罗森尼" },
				{ LanguageIsoCode.zu, "Koyraboro Senni" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ML, "Koyraboro Senni (Mali)" },
			});
	}
}
