namespace HumanLanguages.LanguageNames
{
	public sealed class SMJ
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Lule Sami" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "lulesamisk" },
				{ LanguageIsoCode.af, "Lule Sami" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሉሌ ሳሚ" },
				{ LanguageIsoCode.ar, "لولو سامي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Lule Sami" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Люле Самі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Луле Сами" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "লুলে সামি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Lule Sami" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Lule Sami" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Lule Sami" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Lule Sami" },
				{ LanguageIsoCode.cs, "Lule Sami" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Lule Sami" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Lule Sami" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Λούλε Σάμι" },
				{ LanguageIsoCode.eo, "Lule Sami" },
				{ LanguageIsoCode.es, "lule sami" },
				{ LanguageIsoCode.et, "Lule Sami" },
				{ LanguageIsoCode.eu, "Lule Sami" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "لوله سامی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Lule Sami" },
				{ LanguageIsoCode.fil, "Lule Sami" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Lule Sami" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Lule Sami" },
				{ LanguageIsoCode.ga, "Lule Sami" },
				{ LanguageIsoCode.gd, "Lule Sami" },
				{ LanguageIsoCode.gl, "Lule Sami" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "લુલે સામી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Lule Sami" },
				{ LanguageIsoCode.haw, "Lule Sami" },
				{ LanguageIsoCode.he, "לולה סמי" },
				{ LanguageIsoCode.hi, "लूले सामी" },
				{ LanguageIsoCode.hr, "Lule Sami" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Lule Sami" },
				{ LanguageIsoCode.hy, "Լյուլե Սամի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Lule Sami" },
				{ LanguageIsoCode.ig, "Lule Sami" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Lule Sami" },
				{ LanguageIsoCode.it, "Lulé Sami" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "ルレ・サミ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Lule Sami" },
				{ LanguageIsoCode.ka, "ლულე სამი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Луле Сами" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Lule Sami" },
				{ LanguageIsoCode.kn, "ಲುಲೆ ಸಾಮಿ" },
				{ LanguageIsoCode.ko, "룰레 사미" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Lule Sami" },
				{ LanguageIsoCode.la, "Lule Sami" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Lule Sami" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Lule Sami" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Lule Sami" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Lule Sami" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Lule Samy" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Rule Sami" },
				{ LanguageIsoCode.mk, "Луле Сами" },
				{ LanguageIsoCode.ml, "ലുലെ സാമി" },
				{ LanguageIsoCode.mn, "Луле Сами" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "लुले सामी" },
				{ LanguageIsoCode.ms, "Lule Sami" },
				{ LanguageIsoCode.mt, "Lule Sami" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Lule Sami" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "lulesamisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "लुले सामी" },
				{ LanguageIsoCode.nl, "Lule Sami" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଲୁଲେ ସାମି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਲੂਲੇ ਸਾਮੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Lule Sami" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "لول سمیع" },
				{ LanguageIsoCode.pt, "Lule Sami" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Lule Sami" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Луле Сами" },
				{ LanguageIsoCode.rw, "Lule Sami" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "لولي سامي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ලුලේ සාමි" },
				{ LanguageIsoCode.sk, "Lule Sami" },
				{ LanguageIsoCode.sl, "Lule Sami" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Lule Sami" },
				{ LanguageIsoCode.so, "Lule Sami" },
				{ LanguageIsoCode.sq, "Lule Sami" },
				{ LanguageIsoCode.sr, "Луле Сами" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Lule Sami" },
				{ LanguageIsoCode.su, "Lule Sami" },
				{ LanguageIsoCode.sv, "lulesamiska" },
				{ LanguageIsoCode.sw, "Lule Sami" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "லுலே சாமி" },
				{ LanguageIsoCode.te, "లులే సామి" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Луле Сами" },
				{ LanguageIsoCode.th, "ลูเล่ ซามี" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Lule Sami" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Lüle Sami" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Люль Сами" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Lule Sami" },
				{ LanguageIsoCode.uk, "Луле Самі" },
				{ LanguageIsoCode.ur, "لولے سمیع" },
				{ LanguageIsoCode.uz, "Lule Sami" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Lule Sami" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Lule Sami" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "לולע סאַמי" },
				{ LanguageIsoCode.yo, "Lule Sami" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "吕勒萨米人" },
				{ LanguageIsoCode.zu, "Lule Sami" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.NO, "Lule Sami (Norway)" },
				{ LanguageVariationIsoCode.SE, "Lule Sami (Sweden)" },
			});
	}
}
