namespace HumanLanguages.LanguageNames
{
	public sealed class SMN
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Inari Sami" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "inari sami" },
				{ LanguageIsoCode.af, "Inari Sami" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ኢናሪ ሳሚ" },
				{ LanguageIsoCode.ar, "إيناري سامي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "İnari Sami" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Інары саамскі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Инари Сами" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "ইনারি সামি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Inari Sami" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Inari Sami" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Inari Sami" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Inari Sami" },
				{ LanguageIsoCode.cs, "Inari Sami" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sami Inari" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Inari Sami" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Ινάρι Σάμι" },
				{ LanguageIsoCode.eo, "Inari samea" },
				{ LanguageIsoCode.es, "Inari Sami" },
				{ LanguageIsoCode.et, "Inari saami" },
				{ LanguageIsoCode.eu, "Inari samia" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "ایناری سامی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Inari Sami" },
				{ LanguageIsoCode.fil, "Inari Sami" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Inari Sami" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Inari Sami" },
				{ LanguageIsoCode.ga, "Inari Sami" },
				{ LanguageIsoCode.gd, "Sami Inari" },
				{ LanguageIsoCode.gl, "Inari Sami" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "ઇનારી સામી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Inari Sami" },
				{ LanguageIsoCode.haw, "Inari Sami" },
				{ LanguageIsoCode.he, "אינארי סמי" },
				{ LanguageIsoCode.hi, "इनारी सामी" },
				{ LanguageIsoCode.hr, "Inari Sami" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Inari Sami" },
				{ LanguageIsoCode.hy, "Ինարի Սամի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Inari Sami" },
				{ LanguageIsoCode.ig, "Inari Sami" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Inari Sami" },
				{ LanguageIsoCode.it, "Inari Sami" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "イナリ・サミ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Inari Sami" },
				{ LanguageIsoCode.ka, "ინარი სამი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Инари Сами" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "អ៊ីណារី សាមី" },
				{ LanguageIsoCode.kn, "ಇನ್ಯಾರಿ ಸಾಮಿ" },
				{ LanguageIsoCode.ko, "이나리 사미" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Инари Сами" },
				{ LanguageIsoCode.la, "Inari Sami" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Inari Sami" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Inari Sami" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Inari Sami" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Inari Sami" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Inari Samy" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Inari Sami" },
				{ LanguageIsoCode.mk, "Инари Сами" },
				{ LanguageIsoCode.ml, "ഇനാരി സാമി" },
				{ LanguageIsoCode.mn, "Инари Сами" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "इनारी सामी" },
				{ LanguageIsoCode.ms, "Inari Sami" },
				{ LanguageIsoCode.mt, "Inari Sami" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Inari Sami" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Enare samisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "इनारी सामी" },
				{ LanguageIsoCode.nl, "Inari Sami" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଇନାରୀ ସାମି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਇਨਾਰਿ ਸਾਮੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Inari Sami" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "اناري سمیع" },
				{ LanguageIsoCode.pt, "Inari Sami" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Inari Sami" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Инари Сами" },
				{ LanguageIsoCode.rw, "Inari Sami" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اناري سامي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ඉනාරි සාමි" },
				{ LanguageIsoCode.sk, "Inari Sami" },
				{ LanguageIsoCode.sl, "Inari Sami" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "anarâškielâ" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Inari Sami" },
				{ LanguageIsoCode.so, "Inari Sami" },
				{ LanguageIsoCode.sq, "Inari Sami" },
				{ LanguageIsoCode.sr, "Инари Сами" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Inari Sami" },
				{ LanguageIsoCode.su, "Inari Sami" },
				{ LanguageIsoCode.sv, "Enare Sami" },
				{ LanguageIsoCode.sw, "Inari Sami" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "இன்னாரி சாமி" },
				{ LanguageIsoCode.te, "ఇనారి సామి" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Инари Сами" },
				{ LanguageIsoCode.th, "อินาริ ซามิ" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Inari Sami" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "İnari Sami" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Инари Сами" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Inari Sami" },
				{ LanguageIsoCode.uk, "Інарі Самі" },
				{ LanguageIsoCode.ur, "اناری سمیع" },
				{ LanguageIsoCode.uz, "Inari Sami" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Inari Sami" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Inari Sami" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "ינאַרי סאַמי" },
				{ LanguageIsoCode.yo, "Inari Sami" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "伊纳里萨米" },
				{ LanguageIsoCode.zu, "Inari Sami" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.FI, "Inari Sami (Finland)" },
			});
	}
}
