namespace HumanLanguages.LanguageNames
{
	public sealed class SMS
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Skolt Sami" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "skoltesamisk" },
				{ LanguageIsoCode.af, "Skolt Sami" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ስኮልት ሳሚ" },
				{ LanguageIsoCode.ar, "سكولت سامي" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Skolt Sami" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Скольт саамскі" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Сколт Сами" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "স্কল্ট সামি" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Skolt Sami" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Skolt Sami" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Skolt Sami" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Skolt Sami" },
				{ LanguageIsoCode.cs, "Skolt Sami" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Sgolt Sami" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Skolt Sami" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Skolt Sami" },
				{ LanguageIsoCode.eo, "Skolt Samia" },
				{ LanguageIsoCode.es, "Skolt Sami" },
				{ LanguageIsoCode.et, "koltasaami" },
				{ LanguageIsoCode.eu, "Skolt Sami" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "اسکولت سامی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "koltansaame" },
				{ LanguageIsoCode.fil, "Skolt Sami" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Skolt Sami" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Skolt Sami" },
				{ LanguageIsoCode.ga, "Skolt Sami" },
				{ LanguageIsoCode.gd, "Sgil Sami" },
				{ LanguageIsoCode.gl, "Skolt Sami" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સ્કોલ્ટ સામી" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Skolt Sami" },
				{ LanguageIsoCode.haw, "Skolt Sami" },
				{ LanguageIsoCode.he, "סקולט סמי" },
				{ LanguageIsoCode.hi, "स्कोल्ट सामी" },
				{ LanguageIsoCode.hr, "Skolt Sami" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "kolt számi" },
				{ LanguageIsoCode.hy, "Սկոլտ Սամի" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Skolt Sami" },
				{ LanguageIsoCode.ig, "Skolt Sami" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Skolt Sami" },
				{ LanguageIsoCode.it, "Skolt Sami" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "スコルト・サミ" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Skolt Sami" },
				{ LanguageIsoCode.ka, "სკოლტ სამი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Сколт Сами" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "Skolt Sami" },
				{ LanguageIsoCode.kn, "ಸ್ಕೋಲ್ಟ್ ಸಾಮಿ" },
				{ LanguageIsoCode.ko, "스콜트 사미어" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Skolt Sami" },
				{ LanguageIsoCode.la, "Skolt Sami" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Skolt Sami" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ສະກັອດສະມິ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Koltos samių" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "koltas sāmu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Skolt Samy" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Skolt Sami" },
				{ LanguageIsoCode.mk, "Сколт Сами" },
				{ LanguageIsoCode.ml, "സ്കോൾട്ട് സാമി" },
				{ LanguageIsoCode.mn, "Сколт Сами" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "स्कॉल्ट सामी" },
				{ LanguageIsoCode.ms, "Skolt Sami" },
				{ LanguageIsoCode.mt, "Skolt Sami" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Skolt Sami" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "skoltesamisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "स्कोल्ट सामी" },
				{ LanguageIsoCode.nl, "Skolt Sami" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସ୍କୋଲ୍ଟ ସାମି |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਸਕੋਲਟ ਸਾਮੀ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Skolt Sami" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "سکالټ سمیع" },
				{ LanguageIsoCode.pt, "Skolt Sami" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Skolt Sami" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Скольт-саамы" },
				{ LanguageIsoCode.rw, "Skolt Sami" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "اسڪالر سامي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "ස්කොල්ට් සාමි" },
				{ LanguageIsoCode.sk, "Skolt Sami" },
				{ LanguageIsoCode.sl, "Skolt Sami" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Skolt Sami" },
				{ LanguageIsoCode.so, "Skolt Sami" },
				{ LanguageIsoCode.sq, "Skolt Sami" },
				{ LanguageIsoCode.sr, "Сколт Сами" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Skolt Sami" },
				{ LanguageIsoCode.su, "Skolt Sami" },
				{ LanguageIsoCode.sv, "skoltsamiska" },
				{ LanguageIsoCode.sw, "Skolt Sami" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "ஸ்கோல்ட் சாமி" },
				{ LanguageIsoCode.te, "స్కోల్ట్ సామి" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Сколт Сами" },
				{ LanguageIsoCode.th, "สโคลท์ ซามี" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Skolt Sami" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Skolt Sami" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Сколт Сами" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Skolt Sami" },
				{ LanguageIsoCode.uk, "Скольт Самі" },
				{ LanguageIsoCode.ur, "سکولٹ سمیع" },
				{ LanguageIsoCode.uz, "Skolt Sami" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Skolt Sami" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "Skolt Sami" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "סקול סעמי" },
				{ LanguageIsoCode.yo, "Skolt Sami" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "斯科尔特萨米人" },
				{ LanguageIsoCode.zu, "Skolt Sami" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.FI, "Skolt Sami (Finland)" },
			});
	}
}
