namespace HumanLanguages.LanguageNames
{
	public sealed class SR
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Serbian" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "serbisk" },
				{ LanguageIsoCode.af, "Serwies" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ሰሪቢያን" },
				{ LanguageIsoCode.ar, "الصربية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "serb" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "сербская" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "сръбски" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "সার্বিয়ান" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "srpski" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "serbi" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Serbiano" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Serbianu" },
				{ LanguageIsoCode.cs, "srbština" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Serbeg" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "serbisch" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Σέρβος" },
				{ LanguageIsoCode.eo, "serba" },
				{ LanguageIsoCode.es, "serbio" },
				{ LanguageIsoCode.et, "serblane" },
				{ LanguageIsoCode.eu, "serbiarra" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "صربی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "serbia" },
				{ LanguageIsoCode.fil, "Serbian" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "serbe" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Servysk" },
				{ LanguageIsoCode.ga, "Seirbis" },
				{ LanguageIsoCode.gd, "Serbianach" },
				{ LanguageIsoCode.gl, "serbio" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સર્બિયન" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Serbian" },
				{ LanguageIsoCode.haw, "ʻŌlelo Serbia" },
				{ LanguageIsoCode.he, "סרבית" },
				{ LanguageIsoCode.hi, "सर्बियाई" },
				{ LanguageIsoCode.hr, "srpski" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "szerb" },
				{ LanguageIsoCode.hy, "սերբերեն" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Orang Serbia" },
				{ LanguageIsoCode.ig, "Asụsụ Serbian" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "serbneska" },
				{ LanguageIsoCode.it, "serbo" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "セルビア語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "basa Serbia" },
				{ LanguageIsoCode.ka, "სერბული" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "серб" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ស៊ែប៊ី" },
				{ LanguageIsoCode.kn, "ಸರ್ಬಿಯನ್" },
				{ LanguageIsoCode.ko, "세르비아 사람" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Сербче" },
				{ LanguageIsoCode.la, "Serbian" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "serbesch" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ເຊີເບຍ" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "serbų" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "serbu" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "serbianina" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Serbian" },
				{ LanguageIsoCode.mk, "српски" },
				{ LanguageIsoCode.ml, "സെർബിയൻ" },
				{ LanguageIsoCode.mn, "Серб" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "सर्बियन" },
				{ LanguageIsoCode.ms, "bahasa Serbia" },
				{ LanguageIsoCode.mt, "Serb" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "ဆားဘီးယား" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "serbisk" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "सर्बियाई" },
				{ LanguageIsoCode.nl, "Servisch" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସର୍ବିଆ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਸਰਬੀਆਈ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "serbski" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "صربي" },
				{ LanguageIsoCode.pt, "sérvio" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "sârb" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "сербский" },
				{ LanguageIsoCode.rw, "Igiseribiya" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "سربيائي" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "සර්බියානු" },
				{ LanguageIsoCode.sk, "srbský" },
				{ LanguageIsoCode.sl, "srbsko" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "ChiSebhiya" },
				{ LanguageIsoCode.so, "Seerbiyaan" },
				{ LanguageIsoCode.sq, "serb" },
				{ LanguageIsoCode.sr, "Српски" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Seserbia" },
				{ LanguageIsoCode.su, "Sérbia" },
				{ LanguageIsoCode.sv, "serbiska" },
				{ LanguageIsoCode.sw, "Kiserbia" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "செர்பியன்" },
				{ LanguageIsoCode.te, "సెర్బియన్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "сербӣ" },
				{ LanguageIsoCode.th, "เซอร์เบีย" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Serb" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Sırpça" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Серб" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "سېربىيە" },
				{ LanguageIsoCode.uk, "сербська" },
				{ LanguageIsoCode.ur, "سربیائی" },
				{ LanguageIsoCode.uz, "serb" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "tiếng Serbia" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "isiSebhiya" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "סערביש" },
				{ LanguageIsoCode.yo, "Ede Serbia" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "塞尔维亚" },
				{ LanguageIsoCode.zu, "IsiSerbia" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.CYRL, "Serbian (Cyrillic)" },
				{ LanguageVariationIsoCode.BA, "Serbian (Cyrillic, Bosnia & Herzegovina)" },
				{ LanguageVariationIsoCode.ME, "Serbian (Cyrillic, Montenegro)" },
				{ LanguageVariationIsoCode.RS, "Serbian (Cyrillic, Serbia)" },
				{ LanguageVariationIsoCode.XK, "Serbian (Cyrillic, Kosovo)" },
				{ LanguageVariationIsoCode.LATN, "Serbian (Latin)" },
			});
	}
}
