namespace HumanLanguages.LanguageNames
{
	public sealed class TZM
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Central Atlas Tamazight" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "central atlas tamazight" },
				{ LanguageIsoCode.af, "Sentrale Atlas Tamazight" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "ማዕከላዊ አትላስ Tamazight" },
				{ LanguageIsoCode.ar, "الأطلس الأوسط أمازيغية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Mərkəzi Atlas Tamazight" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Цэнтральны атлас Тамазігхт" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Централен атлас Tamazight" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "সেন্ট্রাল অ্যাটলাস তামাজাইট" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Central Atlas Tamazight" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Atles central Tamazight" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Central Atlas Tamazight" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Atlas centrale Tamazight" },
				{ LanguageIsoCode.cs, "Centrální Atlas Tamazight" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Atlas Canolog Tamazight" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Zentralatlas Tamazight" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Κεντρικός Άτλας Tamazight" },
				{ LanguageIsoCode.eo, "Centra Atlaso Tamazight" },
				{ LanguageIsoCode.es, "Tamazight del Atlas Central" },
				{ LanguageIsoCode.et, "Kesk-Atlas Tamazight" },
				{ LanguageIsoCode.eu, "Erdialdeko Atlas Tamazight" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "اطلس مرکزی تامازیت" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Keski-Atlas Tamazight" },
				{ LanguageIsoCode.fil, "Central Atlas Tamazight" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Tamazight de l'Atlas Central" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Sintrale Atlas Tamazight" },
				{ LanguageIsoCode.ga, "Lárnach Atlas Tamazight" },
				{ LanguageIsoCode.gd, "Meadhan Atlas Tamazight" },
				{ LanguageIsoCode.gl, "Atlas Central Tamazight" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સેન્ટ્રલ એટલાસ Tamazight" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Central Atlas Tamazight" },
				{ LanguageIsoCode.haw, "Central Atlas Tamazight" },
				{ LanguageIsoCode.he, "אטלס מרכזי טמאזייט" },
				{ LanguageIsoCode.hi, "सेंट्रल एटलस टैमाज़ाइट" },
				{ LanguageIsoCode.hr, "Centralni atlas Tamazight" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Közép-Atlas Tamazight" },
				{ LanguageIsoCode.hy, "Կենտրոնական ատլաս Թամազայթ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Atlas Pusat Tamazight" },
				{ LanguageIsoCode.ig, "Central Atlas Tamazight" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Mið Atlas Tamazight" },
				{ LanguageIsoCode.it, "Atlante centrale Tamazight" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "セントラル・アトラス・タマジト州" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Atlas Tengah Tamazight" },
				{ LanguageIsoCode.ka, "ცენტრალური ატლასი თამაზითი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Орталық Атлас Tamazight" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "កណ្តាល Atlas Tamazight" },
				{ LanguageIsoCode.kn, "ಕೇಂದ್ರ ಅಟ್ಲಾಸ್ ತಮಜೈಟ್" },
				{ LanguageIsoCode.ko, "센트럴 아틀라스 타마지트" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Борбордук Атлас Tamazight" },
				{ LanguageIsoCode.la, "Atlas Centralis Tamazight" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Zentral Atlas Tamazight" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "Central Atlas Tamazight" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Centrinis Tamazight atlasas" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Centrālais Tamazita atlants" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Central Atlas Tamazight" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Central Atlas Tamazight" },
				{ LanguageIsoCode.mk, "Централен Атлас Тамазит" },
				{ LanguageIsoCode.ml, "സെൻട്രൽ അറ്റ്ലസ് തമസൈറ്റ്" },
				{ LanguageIsoCode.mn, "Төв Атлас Tamazight" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "सेंट्रल ॲटलस टॅमाझिट" },
				{ LanguageIsoCode.ms, "Tamazight Atlas Tengah" },
				{ LanguageIsoCode.mt, "Atlas Ċentrali Tamazight" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Central Atlas Tamazight" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Sentralatlas Tamazight" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "केन्द्रीय एटलस Tamazight" },
				{ LanguageIsoCode.nl, "Centrale Atlas Tamazight" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ସେଣ୍ଟ୍ରାଲ୍ ଆଟଲାସ୍ ଟମାଜାଇଟ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਕੇਂਦਰੀ ਐਟਲਸ ਟੈਮਾਜ਼ਾਈਟ" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Centralny Atlas Tamazight" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "مرکزي اطلس تمازائٹ" },
				{ LanguageIsoCode.pt, "Atlas Central Tamazight" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Atlasul central Tamazight" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Центральный Атлас Тамазайт" },
				{ LanguageIsoCode.rw, "Hagati ya Atlas Tamazight" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "مرڪزي Atlas Tamazight" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "මධ්යම ඇට්ලස් Tamazight" },
				{ LanguageIsoCode.sk, "Centrálny Atlas Tamazight" },
				{ LanguageIsoCode.sl, "Centralni atlas Tamazight" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Central Atlas Tamazight" },
				{ LanguageIsoCode.so, "Bartamaha Atlas Tamazight" },
				{ LanguageIsoCode.sq, "Atlasi Qendror Tamazight" },
				{ LanguageIsoCode.sr, "Централ Атлас Тамазигхт" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Central Atlas Tamazight" },
				{ LanguageIsoCode.su, "Tengah Atlas Tamazight" },
				{ LanguageIsoCode.sv, "Central Atlas Tamazight" },
				{ LanguageIsoCode.sw, "Atlasi ya Kati ya Tamazight" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "மத்திய அட்லஸ் Tamazight" },
				{ LanguageIsoCode.te, "సెంట్రల్ అట్లాస్ తమజైట్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Атласи марказӣ Tamazight" },
				{ LanguageIsoCode.th, "เซ็นทรัล แอตลาส ทามาไซท์" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Merkezi Atlas Tamazight" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Merkezi Atlas Tamazight" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Centralзәк Атлас Тамазайт" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "Central Atlas Tamazight" },
				{ LanguageIsoCode.uk, "Центральний атлас Тамазігхт" },
				{ LanguageIsoCode.ur, "سینٹرل اٹلس تمازائٹ" },
				{ LanguageIsoCode.uz, "Markaziy Atlas Tamazight" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Trung tâm Atlas Tamazight" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "IAtlasi esembindini yeTamazight" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "סענטראַל אַטלאַס טאַמאַזיגהט" },
				{ LanguageIsoCode.yo, "Central Atlas Tamazight" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "塔马泽特中央阿特拉斯酒店" },
				{ LanguageIsoCode.zu, "I-Central Atlas Tamazight" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.ARAB, "Central Atlas Tamazight (Arabic)" },
				{ LanguageVariationIsoCode.MA, "Central Atlas Tamazight (Arabic, Morocco)" },
				{ LanguageVariationIsoCode.DZ, "Central Atlas Tamazight (Algeria)" },
				{ LanguageVariationIsoCode.TFNG, "Central Atlas Tamazight (Tifinagh)" },
			});
	}
}
