namespace HumanLanguages.LanguageNames
{
	public sealed class ZGH
	{
		public static LanguageProperties LanguageProperties => new(
			LanguageNames:
			new Dictionary<LanguageIsoCode, string>()
			{
				{ LanguageIsoCode.en, "Standard Moroccan Tamazight" },
				{ LanguageIsoCode.aa, "" },
				{ LanguageIsoCode.da, "standard marokkansk tamazight" },
				{ LanguageIsoCode.af, "Standaard Marokkaanse Tamazight" },
				{ LanguageIsoCode.agq, "" },
				{ LanguageIsoCode.ak, "" },
				{ LanguageIsoCode.am, "መደበኛ የሞሮኮ Tamazight" },
				{ LanguageIsoCode.ar, "الأمازيغية المغربية القياسية" },
				{ LanguageIsoCode.arn, "" },
				{ LanguageIsoCode.@as, "" },
				{ LanguageIsoCode.asa, "" },
				{ LanguageIsoCode.ast, "" },
				{ LanguageIsoCode.az, "Standart Mərakeş Tamazight" },
				{ LanguageIsoCode.ba, "" },
				{ LanguageIsoCode.bas, "" },
				{ LanguageIsoCode.be, "Стандартны мараканскі тамазігт" },
				{ LanguageIsoCode.bem, "" },
				{ LanguageIsoCode.bez, "" },
				{ LanguageIsoCode.bg, "Стандартен марокански тамазигт" },
				{ LanguageIsoCode.bin, "" },
				{ LanguageIsoCode.bm, "" },
				{ LanguageIsoCode.bn, "স্ট্যান্ডার্ড মরক্কোর Tamazight" },
				{ LanguageIsoCode.bo, "" },
				{ LanguageIsoCode.br, "" },
				{ LanguageIsoCode.brx, "" },
				{ LanguageIsoCode.bs, "Standardni marokanski Tamazight" },
				{ LanguageIsoCode.byn, "" },
				{ LanguageIsoCode.ca, "Tamazight marroquí estàndard" },
				{ LanguageIsoCode.ccp, "" },
				{ LanguageIsoCode.ce, "" },
				{ LanguageIsoCode.ceb, "Standard nga Moroccan Tamazight" },
				{ LanguageIsoCode.cgg, "" },
				{ LanguageIsoCode.chr, "" },
				{ LanguageIsoCode.ckb, "" },
				{ LanguageIsoCode.co, "Tamazight maroccu standard" },
				{ LanguageIsoCode.cs, "Standardní marocký tamazight" },
				{ LanguageIsoCode.cu, "" },
				{ LanguageIsoCode.cy, "Tamazight Moroco Safonol" },
				{ LanguageIsoCode.dav, "" },
				{ LanguageIsoCode.de, "Standard-marokkanisches Tamazight" },
				{ LanguageIsoCode.dje, "" },
				{ LanguageIsoCode.doi, "" },
				{ LanguageIsoCode.dsb, "" },
				{ LanguageIsoCode.dua, "" },
				{ LanguageIsoCode.dv, "" },
				{ LanguageIsoCode.dz, "" },
				{ LanguageIsoCode.ebu, "" },
				{ LanguageIsoCode.ee, "" },
				{ LanguageIsoCode.el, "Τυποποιημένο Μαροκινό Ταμαζίτ" },
				{ LanguageIsoCode.eo, "Norma maroka tamazigo" },
				{ LanguageIsoCode.es, "Tamazight marroquí estándar" },
				{ LanguageIsoCode.et, "Tavaline Maroko Tamazight" },
				{ LanguageIsoCode.eu, "Marokoko tamazight estandarra" },
				{ LanguageIsoCode.ewo, "" },
				{ LanguageIsoCode.fa, "Tamazight استاندارد مراکشی" },
				{ LanguageIsoCode.ff, "" },
				{ LanguageIsoCode.fi, "Tavallinen marokkolainen Tamazight" },
				{ LanguageIsoCode.fil, "Karaniwang Moroccan Tamazight" },
				{ LanguageIsoCode.fo, "" },
				{ LanguageIsoCode.fr, "Tamazight marocain standard" },
				{ LanguageIsoCode.fur, "" },
				{ LanguageIsoCode.fy, "Standert Marokkaanske Tamazight" },
				{ LanguageIsoCode.ga, "Tamazight Mharacó caighdeánach" },
				{ LanguageIsoCode.gd, "Tamazight àbhaisteach Moroccan" },
				{ LanguageIsoCode.gl, "Tamazight marroquí estándar" },
				{ LanguageIsoCode.gn, "" },
				{ LanguageIsoCode.gsw, "" },
				{ LanguageIsoCode.gu, "સ્ટાન્ડર્ડ મોરોક્કન Tamazight" },
				{ LanguageIsoCode.guz, "" },
				{ LanguageIsoCode.gv, "" },
				{ LanguageIsoCode.ha, "Tamazight Standard na Morocco" },
				{ LanguageIsoCode.haw, "Tamazight Moroccan maʻamau" },
				{ LanguageIsoCode.he, "Tamazight מרוקאי סטנדרטי" },
				{ LanguageIsoCode.hi, "मानक मोरक्कन टैमाज़ाइट" },
				{ LanguageIsoCode.hr, "Standardni marokanski tamazight" },
				{ LanguageIsoCode.hsb, "" },
				{ LanguageIsoCode.hu, "Normál marokkói Tamazight" },
				{ LanguageIsoCode.hy, "Ստանդարտ մարոկկյան թամազայթ" },
				{ LanguageIsoCode.ia, "" },
				{ LanguageIsoCode.ibb, "" },
				{ LanguageIsoCode.id, "Tamazight Maroko standar" },
				{ LanguageIsoCode.ig, "Ọkọlọtọ Moroccan Tamazight" },
				{ LanguageIsoCode.ii, "" },
				{ LanguageIsoCode.@is, "Standard Marokkó Tamazight" },
				{ LanguageIsoCode.it, "Tamazight marocchino standard" },
				{ LanguageIsoCode.iu, "" },
				{ LanguageIsoCode.ja, "標準モロッコ タマジト語" },
				{ LanguageIsoCode.jgo, "" },
				{ LanguageIsoCode.jmc, "" },
				{ LanguageIsoCode.jv, "Standar Moroccan Tamazight" },
				{ LanguageIsoCode.ka, "სტანდარტული მაროკოული თამაზისტი" },
				{ LanguageIsoCode.kab, "" },
				{ LanguageIsoCode.kam, "" },
				{ LanguageIsoCode.kde, "" },
				{ LanguageIsoCode.kea, "" },
				{ LanguageIsoCode.khq, "" },
				{ LanguageIsoCode.ki, "" },
				{ LanguageIsoCode.kk, "Стандартты Марокко Tamazight" },
				{ LanguageIsoCode.kkj, "" },
				{ LanguageIsoCode.kl, "" },
				{ LanguageIsoCode.kln, "" },
				{ LanguageIsoCode.km, "ស្តង់ដារម៉ារ៉ុក Tamazight" },
				{ LanguageIsoCode.kn, "ಸ್ಟ್ಯಾಂಡರ್ಡ್ ಮೊರೊಕನ್ ತಮಜೈಟ್" },
				{ LanguageIsoCode.ko, "표준 모로코 타마지트" },
				{ LanguageIsoCode.kok, "" },
				{ LanguageIsoCode.kr, "" },
				{ LanguageIsoCode.ks, "" },
				{ LanguageIsoCode.ksb, "" },
				{ LanguageIsoCode.ksf, "" },
				{ LanguageIsoCode.ksh, "" },
				{ LanguageIsoCode.kw, "" },
				{ LanguageIsoCode.ky, "Стандарттык Марокко Tamazight" },
				{ LanguageIsoCode.la, "Latin Moroccan Tamazight" },
				{ LanguageIsoCode.lag, "" },
				{ LanguageIsoCode.lb, "Standard marokkaneschen Tamazight" },
				{ LanguageIsoCode.lg, "" },
				{ LanguageIsoCode.lkt, "" },
				{ LanguageIsoCode.ln, "" },
				{ LanguageIsoCode.lo, "ມາດຕະຖານ Moroccan Tamazight" },
				{ LanguageIsoCode.lrc, "" },
				{ LanguageIsoCode.lt, "Standartinis Maroko Tamazight" },
				{ LanguageIsoCode.luo, "" },
				{ LanguageIsoCode.luy, "" },
				{ LanguageIsoCode.lv, "Standarta Marokas Tamazight" },
				{ LanguageIsoCode.mai, "" },
				{ LanguageIsoCode.mas, "" },
				{ LanguageIsoCode.mer, "" },
				{ LanguageIsoCode.mfe, "" },
				{ LanguageIsoCode.mg, "Standard Moroccan Tamazight" },
				{ LanguageIsoCode.mgo, "" },
				{ LanguageIsoCode.mi, "Paerewa Moroccan Tamazight" },
				{ LanguageIsoCode.mk, "Стандарден марокански Тамазит" },
				{ LanguageIsoCode.ml, "സ്റ്റാൻഡേർഡ് മൊറോക്കൻ തമസൈറ്റ്" },
				{ LanguageIsoCode.mn, "Стандарт Марокко Tamazight" },
				{ LanguageIsoCode.mni, "" },
				{ LanguageIsoCode.moh, "" },
				{ LanguageIsoCode.mr, "मानक मोरोक्कन Tamazight" },
				{ LanguageIsoCode.ms, "Tamazight Maghribi standard" },
				{ LanguageIsoCode.mt, "Standard Marokkin Tamazight" },
				{ LanguageIsoCode.mua, "" },
				{ LanguageIsoCode.my, "Standard Moroccan Tamazight" },
				{ LanguageIsoCode.mzn, "" },
				{ LanguageIsoCode.naq, "" },
				{ LanguageIsoCode.nb, "Standard marokkansk Tamazight" },
				{ LanguageIsoCode.nd, "" },
				{ LanguageIsoCode.nds, "" },
				{ LanguageIsoCode.ne, "मानक मोरक्कन Tamazight" },
				{ LanguageIsoCode.nl, "Standaard Marokkaanse Tamazight" },
				{ LanguageIsoCode.nmg, "" },
				{ LanguageIsoCode.nn, "" },
				{ LanguageIsoCode.nnh, "" },
				{ LanguageIsoCode.nqo, "" },
				{ LanguageIsoCode.nr, "" },
				{ LanguageIsoCode.nso, "" },
				{ LanguageIsoCode.nus, "" },
				{ LanguageIsoCode.nyn, "" },
				{ LanguageIsoCode.oc, "" },
				{ LanguageIsoCode.om, "" },
				{ LanguageIsoCode.or, "ଷ୍ଟାଣ୍ଡାର୍ଡ ମୋରୋକୋ ଟମାଜାଇଟ୍ |" },
				{ LanguageIsoCode.os, "" },
				{ LanguageIsoCode.pa, "ਮਿਆਰੀ ਮੋਰੱਕੋ Tamazight" },
				{ LanguageIsoCode.pap, "" },
				{ LanguageIsoCode.pcm, "" },
				{ LanguageIsoCode.pl, "Standardowy marokański tamazight" },
				{ LanguageIsoCode.prg, "" },
				{ LanguageIsoCode.ps, "معیاري مراکش تمازائٹ" },
				{ LanguageIsoCode.pt, "Tamazight marroquino padrão" },
				{ LanguageIsoCode.qu, "" },
				{ LanguageIsoCode.quc, "" },
				{ LanguageIsoCode.rm, "" },
				{ LanguageIsoCode.rn, "" },
				{ LanguageIsoCode.ro, "Tamazight marocan standard" },
				{ LanguageIsoCode.rof, "" },
				{ LanguageIsoCode.ru, "Стандартный марокканский тамазайт" },
				{ LanguageIsoCode.rw, "Bisanzwe Maroc Tamazight" },
				{ LanguageIsoCode.rwk, "" },
				{ LanguageIsoCode.sa, "" },
				{ LanguageIsoCode.sah, "" },
				{ LanguageIsoCode.saq, "" },
				{ LanguageIsoCode.sat, "" },
				{ LanguageIsoCode.sbp, "" },
				{ LanguageIsoCode.sd, "معياري مراکش Tamazight" },
				{ LanguageIsoCode.se, "" },
				{ LanguageIsoCode.seh, "" },
				{ LanguageIsoCode.ses, "" },
				{ LanguageIsoCode.sg, "" },
				{ LanguageIsoCode.shi, "" },
				{ LanguageIsoCode.si, "සම්මත මොරොක්කෝ Tamazight" },
				{ LanguageIsoCode.sk, "Štandardný marocký tamazight" },
				{ LanguageIsoCode.sl, "Standardni maroški tamazit" },
				{ LanguageIsoCode.sma, "" },
				{ LanguageIsoCode.smj, "" },
				{ LanguageIsoCode.smn, "" },
				{ LanguageIsoCode.sms, "" },
				{ LanguageIsoCode.sn, "Standard Moroccan Tamazight" },
				{ LanguageIsoCode.so, "Heerka Tamazight Morocco" },
				{ LanguageIsoCode.sq, "Tamazight standard maroken" },
				{ LanguageIsoCode.sr, "Стандардни марокански Тамазигхт" },
				{ LanguageIsoCode.ss, "" },
				{ LanguageIsoCode.ssy, "" },
				{ LanguageIsoCode.st, "Tamazight ea Morocco e tloaelehileng" },
				{ LanguageIsoCode.su, "Standar Maroko Tamazight" },
				{ LanguageIsoCode.sv, "Standard marockansk Tamazight" },
				{ LanguageIsoCode.sw, "Tamazight ya Morocco ya kawaida" },
				{ LanguageIsoCode.syr, "" },
				{ LanguageIsoCode.ta, "நிலையான மொராக்கோ டமாசைட்" },
				{ LanguageIsoCode.te, "ప్రామాణిక మొరాకో తమజైట్" },
				{ LanguageIsoCode.teo, "" },
				{ LanguageIsoCode.tg, "Стандарти Марокаш Tamazight" },
				{ LanguageIsoCode.th, "Tamazight โมร็อกโกมาตรฐาน" },
				{ LanguageIsoCode.ti, "" },
				{ LanguageIsoCode.tig, "" },
				{ LanguageIsoCode.tk, "Standart Marokko Tamazight" },
				{ LanguageIsoCode.tn, "" },
				{ LanguageIsoCode.to, "" },
				{ LanguageIsoCode.tr, "Standart Fas Tamazight" },
				{ LanguageIsoCode.ts, "" },
				{ LanguageIsoCode.tt, "Стандарт Марокко Тамазайт" },
				{ LanguageIsoCode.twq, "" },
				{ LanguageIsoCode.tzm, "" },
				{ LanguageIsoCode.ug, "ئۆلچەملىك ماراكەش تامازايت" },
				{ LanguageIsoCode.uk, "Стандартний марокканський тамазігхт" },
				{ LanguageIsoCode.ur, "معیاری مراکش تمازائٹ" },
				{ LanguageIsoCode.uz, "Standart Marokash Tamazight" },
				{ LanguageIsoCode.vai, "" },
				{ LanguageIsoCode.ve, "" },
				{ LanguageIsoCode.vi, "Tiêu chuẩn Tamazight Ma-rốc" },
				{ LanguageIsoCode.vo, "" },
				{ LanguageIsoCode.vun, "" },
				{ LanguageIsoCode.wae, "" },
				{ LanguageIsoCode.wal, "" },
				{ LanguageIsoCode.wo, "" },
				{ LanguageIsoCode.xh, "ITamazight yaseMoroccan eqhelekileyo" },
				{ LanguageIsoCode.xog, "" },
				{ LanguageIsoCode.yav, "" },
				{ LanguageIsoCode.yi, "נאָרמאַל מאָראָקקאַן טאַמאַזיגהט" },
				{ LanguageIsoCode.yo, "Standard Moroccan Tamazight" },
				{ LanguageIsoCode.zgh, "" },
				{ LanguageIsoCode.zh, "标准摩洛哥塔马齐特" },
				{ LanguageIsoCode.zu, "I-Standard Moroccan Tamazight" },
			},
			VariationNativeNames:
			new Dictionary<LanguageVariationIsoCode, string>()
			{
				{ LanguageVariationIsoCode.MA, "Standard Moroccan Tamazight (Morocco)" },
			});
	}
}
